#!/usr/bin/env bash
# 00-setup.sh — sanity-check that everything the real-EVM suite depends
# on is in place:
#   - ADMIN_API_KEY env var
#   - CDP credentials (COINBASE_CDP_API_KEY_NAME / _SECRET)
#   - .env.evm-sepolia (test wallet mnemonic, mode 600)
#   - suverse-pay /health reachable
#   - coinbase-cdp registered with the eip155:84532 capability
#   - test wallet funded (ETH for gas, USDC for transfers)
#   - resource API key bootstrapped for step 06 (/facilitator/settle)
#
# Fails fast with a specific message rather than producing confusing
# downstream errors. Does NOT start any services.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/_lib.sh"

step_header "00-setup" "verify gateway, creds, wallet funding, and bootstrap resource key"

require_admin_key
pass "ADMIN_API_KEY set"

if [[ -z "${COINBASE_CDP_API_KEY_NAME:-}" || -z "${COINBASE_CDP_API_KEY_SECRET:-}" ]]; then
  fail "COINBASE_CDP_API_KEY_NAME / _SECRET not set — source $SMOKE_REVM_ROOT/.env first"
fi
pass "CDP credentials present in environment"

if [[ ! -f "$SMOKE_REVM_ROOT/.env.evm-sepolia" ]]; then
  fail ".env.evm-sepolia missing — generate with packages/signers/evm/scripts/gen-evm-sepolia-wallet.mts"
fi
test_addr=$(grep '^EVM_TESTNET_ADDRESS=' "$SMOKE_REVM_ROOT/.env.evm-sepolia" | cut -d= -f2)
if [[ -z "$test_addr" ]]; then
  fail ".env.evm-sepolia present but no EVM_TESTNET_ADDRESS — regenerate the wallet file"
fi
pass "test wallet address: $test_addr"

if ! curl -sf -o /dev/null --max-time 3 "$BASE_URL/health"; then
  fail "suverse-pay /health not reachable at $BASE_URL — start the gateway with .env sourced"
fi
pass "suverse-pay reachable at $BASE_URL"

# Confirm CDP is registered + advertises Base Sepolia. If CDP env vars
# weren't sourced when the gateway booted, the adapter is skipped and
# downstream steps will fail with route_unsupported — catch it here.
providers_body=$(curl -s "$BASE_URL/providers" -H "Authorization: Bearer $ADMIN_API_KEY")
if ! echo "$providers_body" | jq -e '.providers[] | select(.id=="coinbase-cdp")' >/dev/null; then
  fail "coinbase-cdp not registered — gateway was started without CDP env vars sourced"
fi
if ! echo "$providers_body" | jq -e '.providers[] | select(.id=="coinbase-cdp") | .capabilities[] | select(.network=="eip155:84532")' >/dev/null; then
  fail "coinbase-cdp registered but eip155:84532 capability missing — apps/api/src/index.ts not rebuilt?"
fi
pass "coinbase-cdp registered and advertises eip155:84532 (Base Sepolia)"

# On-chain balance probe — confirm the wallet can actually pay.
eth_hex=$(curl -s -X POST "$SMOKE_REVM_RPC" -H "Content-Type: application/json" \
  -d "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"$test_addr\",\"latest\"],\"id\":1}" \
  | jq -r '.result')
if [[ -z "$eth_hex" || "$eth_hex" == "null" || "$eth_hex" == "0x0" ]]; then
  fail "wallet ETH balance is zero on Base Sepolia — fund via Coinbase CDP faucet"
fi
pass "wallet has ETH for gas on Base Sepolia ($eth_hex wei)"

addr_lc="${test_addr,,}"
addr_no0x="${addr_lc#0x}"
addr_padded="000000000000000000000000$addr_no0x"
usdc_hex=$(curl -s -X POST "$SMOKE_REVM_RPC" -H "Content-Type: application/json" \
  -d "{\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"to\":\"$SMOKE_REVM_USDC\",\"data\":\"0x70a08231$addr_padded\"},\"latest\"],\"id\":1}" \
  | jq -r '.result')
usdc_dec=$((16#${usdc_hex#0x}))
if (( usdc_dec < SMOKE_REVM_AMOUNT_ATOMIC * 3 )); then
  fail "wallet USDC balance ($usdc_dec atomic) too low — need at least $((SMOKE_REVM_AMOUNT_ATOMIC * 3)) for steps 04 + 06 with headroom"
fi
pass "wallet USDC balance: $usdc_dec atomic (= $(awk "BEGIN{printf \"%.6f\", $usdc_dec / 1000000}") USDC)"

# Bootstrap a fresh resource key for step 06. Re-bootstrapped every run
# so a previously revoked key never sticks around.
rm -f "$SMOKE_REVM_RESOURCE_KEY_FILE" "$SMOKE_REVM_RESOURCE_KEY_ID_FILE"
if [[ -z "${DATABASE_URL:-}" ]]; then
  fail "DATABASE_URL not set — source $SMOKE_REVM_ROOT/.env first"
fi
cd "$SMOKE_REVM_ROOT"
boot_out=$(DATABASE_URL="$DATABASE_URL" \
  pnpm --silent --filter @suverse-pay/db run bootstrap-resource-key \
    -- --label "real-evm-smoke" --rate-limit 60 --monthly-cap null 2>&1)
plain=$(printf '%s\n' "$boot_out" | awk '/^    [a-f0-9]{64}$/{gsub(/^    /,""); print; exit}')
keyid=$(printf '%s\n' "$boot_out" | awk -F': +' '/^  id: /{print $2; exit}')
if [[ -z "$plain" || -z "$keyid" ]]; then
  printf '%s\n' "$boot_out" >&2
  fail "could not parse plaintext or id from bootstrap-resource-key output"
fi
printf '%s' "$plain" > "$SMOKE_REVM_RESOURCE_KEY_FILE"
printf '%s' "$keyid" > "$SMOKE_REVM_RESOURCE_KEY_ID_FILE"
chmod 600 "$SMOKE_REVM_RESOURCE_KEY_FILE"
pass "bootstrapped resource key for /facilitator/settle: $keyid (60 req/min)"

# Clear per-run state files (fixtures regenerated by 04/06, idem/tx files
# by 04/06).
rm -f "$SMOKE_REVM_IDEM_FILE" "$SMOKE_REVM_PAYMENT_ID_FILE" \
      "$SMOKE_REVM_TX_FILE" "$SMOKE_REVM_FAC_TX_FILE" \
      "$SMOKE_REVM_FIXTURE_INTERNAL" "$SMOKE_REVM_FIXTURE_FACILITATOR"
pass "cleared per-run state in $SMOKE_REVM_TMP"
