#!/usr/bin/env bash
# GENERATED by wrap-batch.mjs — deploy + auto-index for batch batch-e2e.
# Run after author -> probe -> wrap-batch. This is the step that makes the
# batch DISCOVERABLE: it settles every endpoint once so CDP Bazaar indexes it.
set -euo pipefail
REPO="/home/govhub/suverse-pay"
DB="$(grep -hoP '^DATABASE_URL=\K.*' /etc/suverse-pay/proxy.env | tr -d '"')"
echo "1/4 dry-run seed (rollback)"; sed 's/^COMMIT;/ROLLBACK;/' "$REPO/scripts/seed/insert-batch-e2e.sql" | psql "$DB" -v ON_ERROR_STOP=1 -q
echo "2/4 apply seed";            psql "$DB" -v ON_ERROR_STOP=1 -q -f "$REPO/scripts/seed/insert-batch-e2e.sql"
echo "3/4 restart proxy";         kill "$(systemctl show -p MainPID --value suverse-pay-proxy.service)"; sleep 6
echo "4/4 per-endpoint indexing settle (auto)"
PAYER_BASE_PRIVATE_KEY_PATH=${PAYER_BASE_PRIVATE_KEY_PATH:-/etc/suverse-pay/base-payer.key} \
  node "$REPO/apps/proxy/scripts/index-batch.mjs" --batch batch-e2e --delay 3000 --poll
