/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-011".
 * Do not hand-edit — re-run the pipeline. 13 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_011: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_npm_package",
    "slug": "suverse-npm-package",
    "category": "dev-tools",
    "sourceLabel": "npm registry",
    "upstreamMethod": "GET",
    "urlTemplate": "https://registry.npmjs.org/{pkg}/latest",
    "timeoutMs": 10000,
    "params": {
      "pkg": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9][a-z0-9._-]{0,120}$",
        "transform": "lower",
        "description": "Unscoped npm package name, e.g. express, react, lodash.",
        "example": "express"
      }
    },
    "pick": [
      "name",
      "version",
      "description",
      "license",
      "homepage",
      "repository",
      "dependencies",
      "devDependencies",
      "engines",
      "dist",
      "keywords"
    ]
  },
  {
    "handlerName": "suverse_npm_downloads",
    "slug": "suverse-npm-downloads",
    "category": "dev-tools",
    "sourceLabel": "npm registry",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.npmjs.org/downloads/point/{period}/{pkg}",
    "timeoutMs": 10000,
    "params": {
      "period": {
        "in": "path",
        "required": false,
        "type": "string",
        "enum": [
          "last-day",
          "last-week",
          "last-month"
        ],
        "default": "last-week",
        "description": "Download window. One of last-day, last-week, last-month. Default last-week.",
        "example": "last-week"
      },
      "pkg": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9][a-z0-9._-]{0,120}$",
        "transform": "lower",
        "description": "Unscoped npm package name, e.g. express.",
        "example": "express"
      }
    }
  },
  {
    "handlerName": "suverse_pypi_package",
    "slug": "suverse-pypi-package",
    "category": "dev-tools",
    "sourceLabel": "PyPI",
    "upstreamMethod": "GET",
    "urlTemplate": "https://pypi.org/pypi/{pkg}/json",
    "timeoutMs": 10000,
    "params": {
      "pkg": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,120}$",
        "description": "PyPI project name, e.g. requests, numpy, django.",
        "example": "requests"
      }
    },
    "pick": [
      "info",
      "urls",
      "vulnerabilities"
    ]
  },
  {
    "handlerName": "suverse_crates_crate",
    "slug": "suverse-crates-crate",
    "category": "dev-tools",
    "sourceLabel": "crates.io",
    "upstreamMethod": "GET",
    "urlTemplate": "https://crates.io/api/v1/crates/{name}",
    "headers": {
      "User-Agent": "suverse-x402-proxy/1.0 (https://proxy.suverse.io)"
    },
    "timeoutMs": 12000,
    "params": {
      "name": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,64}$",
        "description": "crates.io crate name, e.g. serde, tokio, rand.",
        "example": "serde"
      }
    },
    "pick": [
      "crate",
      "categories",
      "keywords"
    ]
  },
  {
    "handlerName": "suverse_rubygems_gem",
    "slug": "suverse-rubygems-gem",
    "category": "dev-tools",
    "sourceLabel": "RubyGems",
    "upstreamMethod": "GET",
    "urlTemplate": "https://rubygems.org/api/v1/gems/{name}.json",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,64}$",
        "description": "RubyGems gem name, e.g. rails, sinatra, puma.",
        "example": "rails"
      }
    }
  },
  {
    "handlerName": "suverse_maven_artifact",
    "slug": "suverse-maven-artifact",
    "category": "dev-tools",
    "sourceLabel": "Maven Central",
    "upstreamMethod": "GET",
    "urlTemplate": "https://search.maven.org/solrsearch/select",
    "timeoutMs": 25000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "q",
        "description": "Search query. Free text (guava) or field-scoped (g:com.google.guava, a:junit-jupiter).",
        "example": "g:com.google.guava"
      },
      "rows": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "rows",
        "default": 10,
        "description": "Maximum results to return, 1-50. Default 10.",
        "example": 10
      }
    },
    "staticQuery": {
      "wt": "json"
    },
    "pick": [
      "response",
      "responseHeader"
    ]
  },
  {
    "handlerName": "suverse_osv_vuln_detail",
    "slug": "suverse-osv-vuln-detail",
    "category": "security",
    "sourceLabel": "OSV.dev",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.osv.dev/v1/vulns/{id}",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{2,64}$",
        "description": "Vulnerability identifier, e.g. GHSA-jf85-cpcp-j695, CVE-2021-44228, PYSEC-2021-76.",
        "example": "GHSA-jf85-cpcp-j695"
      }
    }
  },
  {
    "handlerName": "suverse_depsdev_package",
    "slug": "suverse-depsdev-package",
    "category": "dev-tools",
    "sourceLabel": "deps.dev",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.deps.dev/v3alpha/systems/{system}/packages/{pkg}",
    "timeoutMs": 12000,
    "params": {
      "system": {
        "in": "path",
        "required": true,
        "type": "string",
        "enum": [
          "npm",
          "pypi",
          "cargo",
          "go",
          "maven",
          "nuget"
        ],
        "transform": "lower",
        "description": "Package ecosystem: npm, pypi, cargo, go, maven or nuget.",
        "example": "npm"
      },
      "pkg": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,120}$",
        "description": "Package name within that ecosystem, e.g. express, requests, serde.",
        "example": "express"
      }
    }
  },
  {
    "handlerName": "suverse_ossf_scorecard",
    "slug": "suverse-ossf-scorecard",
    "category": "security",
    "sourceLabel": "OpenSSF Scorecard",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.securityscorecards.dev/projects/github.com/{owner}/{repo}",
    "timeoutMs": 15000,
    "params": {
      "owner": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,60}$",
        "description": "GitHub organisation or user that owns the repository.",
        "example": "expressjs"
      },
      "repo": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,80}$",
        "description": "GitHub repository name.",
        "example": "express"
      }
    }
  },
  {
    "handlerName": "suverse_ripe_prefix_overview",
    "slug": "suverse-ripe-prefix-overview",
    "category": "network-intel",
    "sourceLabel": "RIPEstat",
    "upstreamMethod": "GET",
    "urlTemplate": "https://stat.ripe.net/data/prefix-overview/data.json",
    "timeoutMs": 12000,
    "params": {
      "resource": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "resource",
        "description": "IPv4/IPv6 address or CIDR prefix, e.g. 8.8.8.8 or 8.8.8.0/24.",
        "example": "8.8.8.8"
      }
    }
  },
  {
    "handlerName": "suverse_ripe_routing_history",
    "slug": "suverse-ripe-routing-history",
    "category": "network-intel",
    "sourceLabel": "RIPEstat",
    "upstreamMethod": "GET",
    "urlTemplate": "https://stat.ripe.net/data/routing-history/data.json",
    "timeoutMs": 20000,
    "params": {
      "resource": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "resource",
        "description": "CIDR prefix or AS number, e.g. 8.8.8.0/24 or AS15169.",
        "example": "8.8.8.0/24"
      },
      "max_rows": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "max_rows",
        "default": 10,
        "description": "Maximum history rows to return, 1-50. Default 10 to keep the response compact.",
        "example": 10
      },
      "starttime": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "starttime",
        "description": "Optional ISO date to start the history window, e.g. 2026-01-01. Narrows a large result.",
        "example": "2026-01-01"
      }
    }
  },
  {
    "handlerName": "suverse_ripe_abuse_contact",
    "slug": "suverse-ripe-abuse-contact",
    "category": "network-intel",
    "sourceLabel": "RIPEstat",
    "upstreamMethod": "GET",
    "urlTemplate": "https://stat.ripe.net/data/abuse-contact-finder/data.json",
    "timeoutMs": 12000,
    "params": {
      "resource": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "resource",
        "description": "IP address, CIDR prefix or AS number, e.g. 8.8.8.8, 8.8.8.0/24 or AS15169.",
        "example": "8.8.8.8"
      }
    }
  },
  {
    "handlerName": "suverse_ripe_rpki_validation",
    "slug": "suverse-ripe-rpki-validation",
    "category": "network-intel",
    "sourceLabel": "RIPEstat",
    "upstreamMethod": "GET",
    "urlTemplate": "https://stat.ripe.net/data/rpki-validation/data.json",
    "timeoutMs": 12000,
    "params": {
      "resource": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "resource",
        "description": "Autonomous system number claiming the origin, e.g. AS15169 or 15169.",
        "example": "AS15169"
      },
      "prefix": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "prefix",
        "description": "CIDR prefix being validated, e.g. 8.8.8.0/24.",
        "example": "8.8.8.0/24"
      }
    }
  }
];
