/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-001".
 * Do not hand-edit — re-run the pipeline. 24 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_001: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_treasury_avg_rates",
    "slug": "suverse-treasury-avg-rates",
    "category": "treasury",
    "sourceLabel": "treasury.fiscaldata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/avg_interest_rates",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {},
    "staticQuery": {
      "sort": "-record_date",
      "page[size]": "16",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_treasury_debt_to_penny",
    "slug": "suverse-treasury-debt-to-penny",
    "category": "treasury",
    "sourceLabel": "treasury.fiscaldata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {},
    "staticQuery": {
      "sort": "-record_date",
      "page[size]": "1",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_treasury_exchange_rates",
    "slug": "suverse-treasury-exchange-rates",
    "category": "treasury",
    "sourceLabel": "treasury.fiscaldata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "query",
        "upstreamName": "filter",
        "required": false,
        "type": "string",
        "description": "Optional country name filter passed to the Treasury filter param, e.g. country:eq:Canada",
        "example": "country:eq:Canada"
      }
    },
    "staticQuery": {
      "sort": "-effective_date",
      "page[size]": "20",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_macro_indicator",
    "slug": "suverse-macro-indicator",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/{indicator}",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper",
        "description": "ISO 2 or 3 letter country code, e.g. US, GBR, JPN",
        "example": "US"
      },
      "indicator": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9.]{3,40}$",
        "transform": "upper",
        "description": "World Bank indicator code, e.g. NY.GDP.MKTP.CD for GDP",
        "example": "NY.GDP.MKTP.CD"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "60"
    }
  },
  {
    "handlerName": "suverse_macro_gdp",
    "slug": "suverse-macro-gdp",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NY.GDP.MKTP.CD",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper",
        "description": "ISO 2 or 3 letter country code, e.g. US, GBR, JPN",
        "example": "US"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_macro_cpi_inflation",
    "slug": "suverse-macro-cpi-inflation",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/FP.CPI.TOTL.ZG",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper",
        "description": "ISO 2 or 3 letter country code, e.g. US, GBR, JPN",
        "example": "US"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_macro_unemployment",
    "slug": "suverse-macro-unemployment",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SL.UEM.TOTL.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper",
        "description": "ISO 2 or 3 letter country code, e.g. US, GBR, JPN",
        "example": "US"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_sec_company_concept",
    "slug": "suverse-sec-company-concept",
    "category": "sec-filings",
    "sourceLabel": "sec.edgar",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.sec.gov/api/xbrl/companyconcept/CIK{cik}/{taxonomy}/{tag}.json",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "cik": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{1,10}$",
        "transform": "pad10",
        "description": "SEC Central Index Key, digits only, zero padded to 10 automatically. Apple is 320193",
        "example": "320193"
      },
      "taxonomy": {
        "in": "path",
        "required": false,
        "type": "string",
        "default": "us-gaap",
        "pattern": "^[a-z-]+$",
        "description": "XBRL taxonomy, defaults to us-gaap",
        "example": "us-gaap"
      },
      "tag": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2,60}$",
        "description": "XBRL concept tag, e.g. Revenues, Assets, NetIncomeLoss",
        "example": "Revenues"
      }
    }
  },
  {
    "handlerName": "suverse_sec_company_facts",
    "slug": "suverse-sec-company-facts",
    "category": "sec-filings",
    "sourceLabel": "sec.edgar",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 15000,
    "params": {
      "cik": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{1,10}$",
        "transform": "pad10",
        "description": "SEC Central Index Key, digits only, zero padded to 10 automatically. Apple is 320193",
        "example": "320193"
      }
    }
  },
  {
    "handlerName": "suverse_sec_submissions",
    "slug": "suverse-sec-submissions",
    "category": "sec-filings",
    "sourceLabel": "sec.edgar",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.sec.gov/submissions/CIK{cik}.json",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "cik": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{1,10}$",
        "transform": "pad10",
        "description": "SEC Central Index Key, digits only, zero padded to 10 automatically. Apple is 320193",
        "example": "320193"
      }
    }
  },
  {
    "handlerName": "suverse_weather_current",
    "slug": "suverse-weather-current",
    "category": "weather",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.open-meteo.com/v1/forecast",
    "timeoutMs": 8000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude between -90 and 90",
        "example": 40.71
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude between -180 and 180",
        "example": -74.01
      }
    },
    "staticQuery": {
      "current_weather": "true"
    }
  },
  {
    "handlerName": "suverse_weather_forecast",
    "slug": "suverse-weather-forecast",
    "category": "weather",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.open-meteo.com/v1/forecast",
    "timeoutMs": 8000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude between -90 and 90",
        "example": 40.71
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude between -180 and 180",
        "example": -74.01
      }
    },
    "staticQuery": {
      "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum",
      "timezone": "auto",
      "forecast_days": "7"
    }
  },
  {
    "handlerName": "suverse_weather_historical",
    "slug": "suverse-weather-historical",
    "category": "weather",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://archive-api.open-meteo.com/v1/archive",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude between -90 and 90",
        "example": 40.71
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude between -180 and 180",
        "example": -74.01
      },
      "start_date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Start date YYYY-MM-DD",
        "example": "2025-01-01"
      },
      "end_date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "End date YYYY-MM-DD",
        "example": "2025-01-31"
      }
    },
    "staticQuery": {
      "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum",
      "timezone": "auto"
    }
  },
  {
    "handlerName": "suverse_air_quality",
    "slug": "suverse-air-quality",
    "category": "weather",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://air-quality-api.open-meteo.com/v1/air-quality",
    "timeoutMs": 8000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude between -90 and 90",
        "example": 40.71
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude between -180 and 180",
        "example": -74.01
      }
    },
    "staticQuery": {
      "hourly": "pm10,pm2_5,carbon_monoxide,ozone,nitrogen_dioxide",
      "timezone": "auto",
      "forecast_days": "1"
    }
  },
  {
    "handlerName": "suverse_marine_forecast",
    "slug": "suverse-marine-forecast",
    "category": "weather",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://marine-api.open-meteo.com/v1/marine",
    "timeoutMs": 8000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Coastal latitude between -90 and 90",
        "example": 40.5
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Coastal longitude between -180 and 180",
        "example": -69.5
      }
    },
    "staticQuery": {
      "hourly": "wave_height,wave_direction,wave_period",
      "timezone": "auto",
      "forecast_days": "1"
    }
  },
  {
    "handlerName": "suverse_weather_alerts",
    "slug": "suverse-weather-alerts",
    "category": "weather",
    "sourceLabel": "nws.weather.gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.weather.gov/alerts/active",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {
      "area": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z]{2}$",
        "transform": "upper",
        "description": "Two letter US state or territory code, e.g. CA, TX, FL",
        "example": "CA"
      }
    },
    "staticQuery": {}
  },
  {
    "handlerName": "suverse_cve_lookup",
    "slug": "suverse-cve-lookup",
    "category": "cybersecurity",
    "sourceLabel": "nvd.nist",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.nvd.nist.gov/rest/json/cves/2.0",
    "timeoutMs": 12000,
    "params": {
      "cve_id": {
        "in": "query",
        "upstreamName": "cveId",
        "required": true,
        "type": "string",
        "pattern": "^CVE-[0-9]{4}-[0-9]{4,}$",
        "transform": "upper",
        "description": "CVE identifier, e.g. CVE-2021-44228",
        "example": "CVE-2021-44228"
      }
    }
  },
  {
    "handlerName": "suverse_cve_search",
    "slug": "suverse-cve-search",
    "category": "cybersecurity",
    "sourceLabel": "nvd.nist",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.nvd.nist.gov/rest/json/cves/2.0",
    "timeoutMs": 12000,
    "params": {
      "keyword": {
        "in": "query",
        "upstreamName": "keywordSearch",
        "required": true,
        "type": "string",
        "pattern": "^.{2,80}$",
        "description": "Keyword to search CVE descriptions, e.g. log4j, openssl, apache",
        "example": "log4j"
      }
    },
    "staticQuery": {
      "resultsPerPage": "20"
    }
  },
  {
    "handlerName": "suverse_cisa_kev",
    "slug": "suverse-cisa-kev",
    "category": "cybersecurity",
    "sourceLabel": "cisa.kev",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json",
    "timeoutMs": 15000,
    "params": {}
  },
  {
    "handlerName": "suverse_sports_team",
    "slug": "suverse-sports-team",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/searchteams.php",
    "timeoutMs": 10000,
    "params": {
      "team": {
        "in": "query",
        "upstreamName": "t",
        "required": true,
        "type": "string",
        "pattern": "^.{2,60}$",
        "description": "Team name to search, e.g. Arsenal, Lakers, Yankees",
        "example": "Arsenal"
      }
    }
  },
  {
    "handlerName": "suverse_sports_league_table",
    "slug": "suverse-sports-league-table",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/lookuptable.php",
    "timeoutMs": 10000,
    "params": {
      "league_id": {
        "in": "query",
        "upstreamName": "l",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{3,7}$",
        "description": "TheSportsDB numeric league id, e.g. 4328 for English Premier League",
        "example": "4328"
      },
      "season": {
        "in": "query",
        "upstreamName": "s",
        "required": false,
        "type": "string",
        "pattern": "^[0-9]{4}(-[0-9]{4})?$",
        "description": "Season, e.g. 2025-2026",
        "example": "2025-2026"
      }
    }
  },
  {
    "handlerName": "suverse_sports_events_day",
    "slug": "suverse-sports-events-day",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/eventsday.php",
    "timeoutMs": 10000,
    "params": {
      "date": {
        "in": "query",
        "upstreamName": "d",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Date YYYY-MM-DD",
        "example": "2026-06-19"
      },
      "sport": {
        "in": "query",
        "upstreamName": "s",
        "required": false,
        "type": "string",
        "pattern": "^[A-Za-z_ ]{3,30}$",
        "description": "Optional sport filter, e.g. Soccer, Basketball, Baseball",
        "example": "Soccer"
      }
    }
  },
  {
    "handlerName": "suverse_mlb_schedule",
    "slug": "suverse-mlb-schedule",
    "category": "sports",
    "sourceLabel": "mlb.statsapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://statsapi.mlb.com/api/v1/schedule",
    "timeoutMs": 10000,
    "params": {
      "date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Date YYYY-MM-DD",
        "example": "2026-06-19"
      }
    },
    "staticQuery": {
      "sportId": "1"
    }
  },
  {
    "handlerName": "suverse_mlb_standings",
    "slug": "suverse-mlb-standings",
    "category": "sports",
    "sourceLabel": "mlb.statsapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://statsapi.mlb.com/api/v1/standings",
    "timeoutMs": 10000,
    "params": {
      "season": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Season year YYYY",
        "example": "2026"
      }
    },
    "staticQuery": {
      "leagueId": "103,104"
    }
  }
];
