/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-015".
 * Do not hand-edit — re-run the pipeline. 12 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_015: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_espn_scoreboard",
    "slug": "suverse-espn-scoreboard",
    "category": "sports",
    "sourceLabel": "ESPN",
    "upstreamMethod": "GET",
    "urlTemplate": "https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/scoreboard",
    "timeoutMs": 20000,
    "params": {
      "sport": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z-]{3,20}$",
        "transform": "lower",
        "description": "ESPN sport slug, e.g. soccer, basketball, football, baseball, hockey.",
        "example": "soccer"
      },
      "league": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9._-]{2,24}$",
        "transform": "lower",
        "description": "ESPN league slug, e.g. eng.1 for the Premier League, nba, nfl, mlb, nhl.",
        "example": "eng.1"
      }
    }
  },
  {
    "handlerName": "suverse_espn_teams",
    "slug": "suverse-espn-teams",
    "category": "sports",
    "sourceLabel": "ESPN",
    "upstreamMethod": "GET",
    "urlTemplate": "https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/teams",
    "timeoutMs": 25000,
    "params": {
      "sport": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z-]{3,20}$",
        "transform": "lower",
        "description": "ESPN sport slug, e.g. basketball, football, soccer.",
        "example": "basketball"
      },
      "league": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9._-]{2,24}$",
        "transform": "lower",
        "description": "ESPN league slug, e.g. nba, nfl, eng.1.",
        "example": "nba"
      }
    }
  },
  {
    "handlerName": "suverse_f1_race_results",
    "slug": "suverse-f1-race-results",
    "category": "sports",
    "sourceLabel": "Jolpica-F1",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jolpi.ca/ergast/f1/{season}/{round}/results.json",
    "timeoutMs": 20000,
    "params": {
      "season": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(19[5-9][0-9]|20[0-9]{2})$",
        "description": "Championship season year, e.g. 2025.",
        "example": "2025"
      },
      "round": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^([1-9]|1[0-9]|2[0-4])$",
        "description": "Round number within the season, 1-24.",
        "example": "1"
      }
    }
  },
  {
    "handlerName": "suverse_f1_driver_standings",
    "slug": "suverse-f1-driver-standings",
    "category": "sports",
    "sourceLabel": "Jolpica-F1",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jolpi.ca/ergast/f1/{season}/driverStandings.json",
    "timeoutMs": 20000,
    "params": {
      "season": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(19[5-9][0-9]|20[0-9]{2})$",
        "description": "Championship season year, e.g. 2025.",
        "example": "2025"
      }
    }
  },
  {
    "handlerName": "suverse_chesscom_player_stats",
    "slug": "suverse-chesscom-player-stats",
    "category": "games",
    "sourceLabel": "Chess.com",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.chess.com/pub/player/{username}/stats",
    "timeoutMs": 20000,
    "params": {
      "username": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{2,30}$",
        "transform": "lower",
        "description": "Chess.com username.",
        "example": "hikaru"
      }
    }
  },
  {
    "handlerName": "suverse_chesscom_player_profile",
    "slug": "suverse-chesscom-player-profile",
    "category": "games",
    "sourceLabel": "Chess.com",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.chess.com/pub/player/{username}",
    "timeoutMs": 20000,
    "params": {
      "username": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{2,30}$",
        "transform": "lower",
        "description": "Chess.com username.",
        "example": "hikaru"
      }
    }
  },
  {
    "handlerName": "suverse_bundesliga_table",
    "slug": "suverse-bundesliga-table",
    "category": "sports",
    "sourceLabel": "OpenLigaDB",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.openligadb.de/getbltable/{league}/{season}",
    "timeoutMs": 20000,
    "params": {
      "league": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9]{2,10}$",
        "transform": "lower",
        "description": "OpenLigaDB league shortcut, e.g. bl1 (Bundesliga), bl2, bl3, dfb.",
        "example": "bl1"
      },
      "season": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^20[0-9]{2}$",
        "description": "Season start year, e.g. 2025 for the 2025/26 season.",
        "example": "2025"
      }
    }
  },
  {
    "handlerName": "suverse_steam_app_details",
    "slug": "suverse-steam-app-details",
    "category": "games",
    "sourceLabel": "Steam Storefront",
    "upstreamMethod": "GET",
    "urlTemplate": "https://store.steampowered.com/api/appdetails",
    "timeoutMs": 25000,
    "params": {
      "appids": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "appids",
        "pattern": "^[0-9]{1,8}$",
        "description": "Steam application id, e.g. 440 for Team Fortress 2, 730 for Counter-Strike 2.",
        "example": "440"
      },
      "cc": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "cc",
        "pattern": "^[A-Za-z]{2}$",
        "transform": "lower",
        "default": "us",
        "description": "Two-letter country code controlling the price currency. Default us.",
        "example": "us"
      }
    }
  },
  {
    "handlerName": "suverse_steam_player_count",
    "slug": "suverse-steam-player-count",
    "category": "games",
    "sourceLabel": "Steam Web API",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.steampowered.com/ISteamUserStats/GetNumberOfCurrentPlayers/v1/",
    "timeoutMs": 20000,
    "params": {
      "appid": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "appid",
        "pattern": "^[0-9]{1,8}$",
        "description": "Steam application id, e.g. 440, 730, 570.",
        "example": "440"
      }
    }
  },
  {
    "handlerName": "suverse_steamspy_app_stats",
    "slug": "suverse-steamspy-app-stats",
    "category": "games",
    "sourceLabel": "SteamSpy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://steamspy.com/api.php",
    "timeoutMs": 25000,
    "params": {
      "appid": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "appid",
        "pattern": "^[0-9]{1,8}$",
        "description": "Steam application id, e.g. 440, 730, 570.",
        "example": "440"
      }
    },
    "staticQuery": {
      "request": "appdetails"
    }
  },
  {
    "handlerName": "suverse_scryfall_card_search",
    "slug": "suverse-scryfall-card-search",
    "category": "games",
    "sourceLabel": "Scryfall",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.scryfall.com/cards/search",
    "headers": {
      "User-Agent": "suverse-x402-proxy/1.0 (https://proxy.suverse.io)",
      "Accept": "application/json"
    },
    "timeoutMs": 20000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "q",
        "description": "Scryfall search query. Supports full syntax, e.g. lightning bolt, or c:red t:instant cmc=1.",
        "example": "lightning bolt"
      },
      "order": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "order",
        "enum": [
          "name",
          "set",
          "released",
          "rarity",
          "usd",
          "edhrec"
        ],
        "description": "Sort order for results.",
        "example": "name"
      }
    }
  },
  {
    "handlerName": "suverse_deck_of_cards_shuffle",
    "slug": "suverse-deck-of-cards-shuffle",
    "category": "games",
    "sourceLabel": "Deck of Cards API",
    "upstreamMethod": "GET",
    "urlTemplate": "https://deckofcardsapi.com/api/deck/new/shuffle/",
    "timeoutMs": 20000,
    "params": {
      "deck_count": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "deck_count",
        "default": 1,
        "description": "How many standard 52-card decks to combine and shuffle, 1-20. Default 1.",
        "example": 1
      }
    }
  }
];
