/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-004".
 * Do not hand-edit — re-run the pipeline. 100 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_004: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_civic_nonprofit_search",
    "slug": "suverse-civic-nonprofit-search",
    "category": "civic",
    "sourceLabel": "propublica",
    "upstreamMethod": "GET",
    "urlTemplate": "https://projects.propublica.org/nonprofits/api/v2/search.json",
    "timeoutMs": 12000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search term (organization name or keyword)",
        "example": "red cross"
      }
    }
  },
  {
    "handlerName": "suverse_civic_nonprofit_org",
    "slug": "suverse-civic-nonprofit-org",
    "category": "civic",
    "sourceLabel": "propublica",
    "upstreamMethod": "GET",
    "urlTemplate": "https://projects.propublica.org/nonprofits/api/v2/organizations/{ein}.json",
    "timeoutMs": 12000,
    "params": {
      "ein": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{9}$",
        "description": "9-digit Employer Identification Number, no dash",
        "example": "530196605"
      }
    }
  },
  {
    "handlerName": "suverse_civic_fedreg_docs_by_type",
    "slug": "suverse-civic-fedreg-docs-by-type",
    "category": "civic",
    "sourceLabel": "federalregister",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.federalregister.gov/api/v1/documents.json",
    "timeoutMs": 12000,
    "params": {
      "type": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "conditions[type][]",
        "enum": [
          "RULE",
          "PRORULE",
          "NOTICE",
          "PRESDOCU"
        ],
        "transform": "upper",
        "description": "Document type code",
        "example": "PRESDOCU"
      }
    },
    "staticQuery": {
      "per_page": "20"
    }
  },
  {
    "handlerName": "suverse_civic_fedreg_public_inspection",
    "slug": "suverse-civic-fedreg-public-inspection",
    "category": "civic",
    "sourceLabel": "federalregister",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.federalregister.gov/api/v1/public-inspection-documents/current.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_civic_fedreg_agency",
    "slug": "suverse-civic-fedreg-agency",
    "category": "civic",
    "sourceLabel": "federalregister",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.federalregister.gov/api/v1/agencies/{slug}.json",
    "timeoutMs": 12000,
    "params": {
      "slug": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z0-9-]+$",
        "description": "Federal Register agency slug",
        "example": "environmental-protection-agency"
      }
    }
  },
  {
    "handlerName": "suverse_veh_mpg_years",
    "slug": "suverse-veh-mpg-years",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/vehicle/menu/year",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_veh_mpg_makes",
    "slug": "suverse-veh-mpg-makes",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/vehicle/menu/make",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Model year",
        "example": "2024"
      }
    }
  },
  {
    "handlerName": "suverse_veh_mpg_models",
    "slug": "suverse-veh-mpg-models",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/vehicle/menu/model",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Model year",
        "example": "2024"
      },
      "make": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Vehicle make",
        "example": "Toyota"
      }
    }
  },
  {
    "handlerName": "suverse_veh_mpg_detail",
    "slug": "suverse-veh-mpg-detail",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/vehicle/{id}",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]+$",
        "description": "FuelEconomy.gov vehicle ID",
        "example": "47368"
      }
    }
  },
  {
    "handlerName": "suverse_veh_emissions",
    "slug": "suverse-veh-emissions",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/vehicle/emissions/{id}",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]+$",
        "description": "FuelEconomy.gov vehicle ID",
        "example": "47368"
      }
    }
  },
  {
    "handlerName": "suverse_veh_fuel_prices",
    "slug": "suverse-veh-fuel-prices",
    "category": "vehicles",
    "sourceLabel": "fueleconomy",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fueleconomy.gov/ws/rest/fuelprices",
    "headers": {
      "accept": "application/json"
    },
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_energy_uk_generation_mix",
    "slug": "suverse-energy-uk-generation-mix",
    "category": "energy",
    "sourceLabel": "carbonintensity",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.carbonintensity.org.uk/generation",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_game_deals",
    "slug": "suverse-game-deals",
    "category": "games",
    "sourceLabel": "cheapshark",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.cheapshark.com/api/1.0/deals",
    "timeoutMs": 12000,
    "params": {
      "storeID": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Filter by CheapShark store ID (e.g. 1=Steam)",
        "example": "1"
      },
      "upperPrice": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Maximum sale price in USD",
        "example": "15"
      },
      "sortBy": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Sort field: Deal Rating, Title, Savings, Price, Metacritic",
        "example": "Savings"
      },
      "title": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Filter deals by game title substring",
        "example": "witcher"
      }
    },
    "staticQuery": {
      "pageSize": "20"
    }
  },
  {
    "handlerName": "suverse_game_stores",
    "slug": "suverse-game-stores",
    "category": "games",
    "sourceLabel": "cheapshark",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.cheapshark.com/api/1.0/stores",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_game_price_search",
    "slug": "suverse-game-price-search",
    "category": "games",
    "sourceLabel": "cheapshark",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.cheapshark.com/api/1.0/games",
    "timeoutMs": 12000,
    "params": {
      "title": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Game title to search for",
        "example": "witcher"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_game_free_list",
    "slug": "suverse-game-free-list",
    "category": "games",
    "sourceLabel": "freetogame",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.freetogame.com/api/games",
    "timeoutMs": 12000,
    "params": {
      "platform": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "pc",
          "browser",
          "all"
        ],
        "description": "Platform filter",
        "example": "pc"
      },
      "sort-by": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Sort: release-date, popularity, alphabetical, relevance",
        "example": "popularity"
      }
    }
  },
  {
    "handlerName": "suverse_game_free_by_category",
    "slug": "suverse-game-free-by-category",
    "category": "games",
    "sourceLabel": "freetogame",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.freetogame.com/api/games",
    "timeoutMs": 12000,
    "params": {
      "category": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Genre/category, e.g. shooter, mmorpg, strategy, card, racing, moba",
        "example": "shooter"
      }
    }
  },
  {
    "handlerName": "suverse_game_free_detail",
    "slug": "suverse-game-free-detail",
    "category": "games",
    "sourceLabel": "freetogame",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.freetogame.com/api/game",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "FreeToGame game ID",
        "example": "452"
      }
    }
  },
  {
    "handlerName": "suverse_anime_top",
    "slug": "suverse-anime-top",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/top/anime",
    "timeoutMs": 12000,
    "params": {
      "type": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Filter by type: tv, movie, ova, special, ona, music",
        "example": "tv"
      },
      "filter": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "airing, upcoming, bypopularity or favorite",
        "example": "bypopularity"
      }
    },
    "staticQuery": {
      "limit": "15"
    }
  },
  {
    "handlerName": "suverse_anime_search",
    "slug": "suverse-anime-search",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/anime",
    "timeoutMs": 12000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Anime title search query",
        "example": "naruto"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_anime_season_now",
    "slug": "suverse-anime-season-now",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/seasons/now",
    "timeoutMs": 12000,
    "params": {
      "filter": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Filter by type: tv, movie, ova, special, ona, music",
        "example": "tv"
      }
    },
    "staticQuery": {
      "limit": "20"
    }
  },
  {
    "handlerName": "suverse_anime_detail",
    "slug": "suverse-anime-detail",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/anime/{id}",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "MyAnimeList anime ID",
        "example": "1"
      }
    }
  },
  {
    "handlerName": "suverse_anime_manga_search",
    "slug": "suverse-anime-manga-search",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/manga",
    "timeoutMs": 12000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Manga title search query",
        "example": "berserk"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_anime_character_search",
    "slug": "suverse-anime-character-search",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/characters",
    "timeoutMs": 12000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Character name search query",
        "example": "goku"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_anime_schedule",
    "slug": "suverse-anime-schedule",
    "category": "anime",
    "sourceLabel": "jikan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.jikan.moe/v4/schedules",
    "timeoutMs": 12000,
    "params": {
      "filter": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
          "sunday",
          "unknown",
          "other"
        ],
        "description": "Weekday filter",
        "example": "monday"
      }
    },
    "staticQuery": {
      "limit": "20"
    }
  },
  {
    "handlerName": "suverse_geo_osrm_route",
    "slug": "suverse-geo-osrm-route",
    "category": "geo",
    "sourceLabel": "osrm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://router.project-osrm.org/route/v1/driving/{coords}",
    "timeoutMs": 12000,
    "params": {
      "coords": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Semicolon-separated lon,lat pairs (at least two), e.g. start;end",
        "example": "13.388,52.517;13.397,52.529"
      }
    },
    "staticQuery": {
      "overview": "false"
    }
  },
  {
    "handlerName": "suverse_geo_osrm_nearest",
    "slug": "suverse-geo-osrm-nearest",
    "category": "geo",
    "sourceLabel": "osrm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://router.project-osrm.org/nearest/v1/driving/{coord}",
    "timeoutMs": 12000,
    "params": {
      "coord": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "A single lon,lat coordinate to snap",
        "example": "13.388,52.517"
      },
      "number": {
        "in": "query",
        "required": false,
        "type": "integer",
        "default": "1",
        "description": "Number of nearest segments to return",
        "example": "3"
      }
    }
  },
  {
    "handlerName": "suverse_geo_reverse_bdc",
    "slug": "suverse-geo-reverse-bdc",
    "category": "geo",
    "sourceLabel": "bigdatacloud",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api-bdc.io/data/reverse-geocode-client",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude in decimal degrees",
        "example": "52.517"
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude in decimal degrees",
        "example": "13.388"
      }
    },
    "staticQuery": {
      "localityLanguage": "en"
    }
  },
  {
    "handlerName": "suverse_geo_zip_germany",
    "slug": "suverse-geo-zip-germany",
    "category": "geo",
    "sourceLabel": "zippopotam",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.zippopotam.us/de/{postcode}",
    "timeoutMs": 12000,
    "params": {
      "postcode": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "German postal code (5 digits)",
        "example": "10117"
      }
    }
  },
  {
    "handlerName": "suverse_geo_place_by_name",
    "slug": "suverse-geo-place-by-name",
    "category": "geo",
    "sourceLabel": "zippopotam",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.zippopotam.us/us/{state}/{city}",
    "timeoutMs": 12000,
    "params": {
      "state": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Two-letter US state abbreviation",
        "example": "ny"
      },
      "city": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "City name (URL-encode spaces)",
        "example": "new york"
      }
    }
  },
  {
    "handlerName": "suverse_time_by_zone",
    "slug": "suverse-time-by-zone",
    "category": "time",
    "sourceLabel": "timeapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://timeapi.io/api/time/current/zone",
    "timeoutMs": 12000,
    "params": {
      "timeZone": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "IANA timezone identifier",
        "example": "Europe/Berlin"
      }
    }
  },
  {
    "handlerName": "suverse_time_by_coordinate",
    "slug": "suverse-time-by-coordinate",
    "category": "time",
    "sourceLabel": "timeapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://timeapi.io/api/time/current/coordinate",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude in decimal degrees",
        "example": "52.5"
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude in decimal degrees",
        "example": "13.4"
      }
    }
  },
  {
    "handlerName": "suverse_time_by_ip",
    "slug": "suverse-time-by-ip",
    "category": "time",
    "sourceLabel": "timeapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://timeapi.io/api/time/current/ip",
    "timeoutMs": 12000,
    "params": {
      "ipAddress": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "IPv4 or IPv6 address",
        "example": "8.8.8.8"
      }
    }
  },
  {
    "handlerName": "suverse_time_available_zones",
    "slug": "suverse-time-available-zones",
    "category": "time",
    "sourceLabel": "timeapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://timeapi.io/api/timezone/availabletimezones",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_net_ip_geo",
    "slug": "suverse-net-ip-geo",
    "category": "net",
    "sourceLabel": "ip-api",
    "upstreamMethod": "GET",
    "urlTemplate": "http://ip-api.com/json/{ip}",
    "timeoutMs": 12000,
    "params": {
      "ip": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "IPv4 or IPv6 address to geolocate",
        "example": "8.8.8.8"
      }
    },
    "staticQuery": {
      "fields": "status,message,country,countryCode,region,regionName,city,zip,lat,lon,timezone,isp,org,as,query"
    }
  },
  {
    "handlerName": "suverse_net_client_ip",
    "slug": "suverse-net-client-ip",
    "category": "net",
    "sourceLabel": "bigdatacloud",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api-bdc.io/data/client-ip",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_net_dns_mx",
    "slug": "suverse-net-dns-mx",
    "category": "net",
    "sourceLabel": "google-doh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://dns.google/resolve",
    "timeoutMs": 12000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Domain name to look up MX records for",
        "example": "gmail.com"
      }
    },
    "staticQuery": {
      "type": "MX"
    }
  },
  {
    "handlerName": "suverse_net_dns_txt",
    "slug": "suverse-net-dns-txt",
    "category": "net",
    "sourceLabel": "cloudflare-doh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://cloudflare-dns.com/dns-query",
    "headers": {
      "accept": "application/dns-json"
    },
    "timeoutMs": 12000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Domain name to look up TXT records for",
        "example": "cloudflare.com"
      }
    },
    "staticQuery": {
      "type": "TXT"
    }
  },
  {
    "handlerName": "suverse_health_covid_vaccine_country",
    "slug": "suverse-health-covid-vaccine-country",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/vaccine/coverage/countries/{country}",
    "timeoutMs": 12000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Country name, ISO2 or ISO3 code",
        "example": "USA"
      },
      "lastdays": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "30",
        "description": "Number of trailing days to return (or 'all')",
        "example": "30"
      }
    },
    "staticQuery": {
      "fullData": "false"
    }
  },
  {
    "handlerName": "suverse_health_covid_us_state",
    "slug": "suverse-health-covid-us-state",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/states/{state}",
    "timeoutMs": 12000,
    "params": {
      "state": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Full US state name",
        "example": "California"
      }
    }
  },
  {
    "handlerName": "suverse_health_covid_countries_all",
    "slug": "suverse-health-covid-countries-all",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/countries",
    "timeoutMs": 12000,
    "params": {
      "sort": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "Field to sort countries by (cases, deaths, tests, ...)",
        "example": "cases"
      }
    }
  },
  {
    "handlerName": "suverse_health_icd9_diagnosis",
    "slug": "suverse-health-icd9-diagnosis",
    "category": "health",
    "sourceLabel": "clinicaltables-nlm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/icd9cm_dx/v3/search",
    "timeoutMs": 12000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Free-text search term",
        "example": "diabetes"
      }
    }
  },
  {
    "handlerName": "suverse_health_loinc_search",
    "slug": "suverse-health-loinc-search",
    "category": "health",
    "sourceLabel": "clinicaltables-nlm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/loinc_items/v3/search",
    "timeoutMs": 12000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Free-text search term",
        "example": "glucose"
      }
    }
  },
  {
    "handlerName": "suverse_health_disease_names",
    "slug": "suverse-health-disease-names",
    "category": "health",
    "sourceLabel": "clinicaltables-nlm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/disease_names/v3/search",
    "timeoutMs": 12000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Free-text search term",
        "example": "asthma"
      }
    }
  },
  {
    "handlerName": "suverse_health_procedures_search",
    "slug": "suverse-health-procedures-search",
    "category": "health",
    "sourceLabel": "clinicaltables-nlm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/procedures/v3/search",
    "timeoutMs": 12000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Free-text search term",
        "example": "biopsy"
      }
    }
  },
  {
    "handlerName": "suverse_bio_pubmed_search",
    "slug": "suverse-bio-pubmed-search",
    "category": "genomics",
    "sourceLabel": "ncbi-eutils",
    "upstreamMethod": "GET",
    "urlTemplate": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
    "timeoutMs": 12000,
    "params": {
      "term": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "PubMed search term",
        "example": "crispr"
      },
      "retmax": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "10",
        "description": "Max number of PMIDs to return",
        "example": "5"
      }
    },
    "staticQuery": {
      "db": "pubmed",
      "retmode": "json"
    }
  },
  {
    "handlerName": "suverse_bio_pubmed_summary",
    "slug": "suverse-bio-pubmed-summary",
    "category": "genomics",
    "sourceLabel": "ncbi-eutils",
    "upstreamMethod": "GET",
    "urlTemplate": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "One or more PubMed PMIDs (comma-separated)",
        "example": "38000000"
      }
    },
    "staticQuery": {
      "db": "pubmed",
      "retmode": "json"
    }
  },
  {
    "handlerName": "suverse_bio_ncbi_gene_summary",
    "slug": "suverse-bio-ncbi-gene-summary",
    "category": "genomics",
    "sourceLabel": "ncbi-eutils",
    "upstreamMethod": "GET",
    "urlTemplate": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "NCBI Entrez Gene ID",
        "example": "672"
      }
    },
    "staticQuery": {
      "db": "gene",
      "retmode": "json"
    }
  },
  {
    "handlerName": "suverse_bio_ncbi_snp_summary",
    "slug": "suverse-bio-ncbi-snp-summary",
    "category": "genomics",
    "sourceLabel": "ncbi-eutils",
    "upstreamMethod": "GET",
    "urlTemplate": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "dbSNP rsID number (without rs prefix)",
        "example": "328"
      }
    },
    "staticQuery": {
      "db": "snp",
      "retmode": "json"
    }
  },
  {
    "handlerName": "suverse_bio_ensembl_gene_lookup",
    "slug": "suverse-bio-ensembl-gene-lookup",
    "category": "genomics",
    "sourceLabel": "ensembl",
    "upstreamMethod": "GET",
    "urlTemplate": "https://rest.ensembl.org/lookup/symbol/homo_sapiens/{symbol}",
    "timeoutMs": 12000,
    "params": {
      "symbol": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Human gene HGNC symbol",
        "example": "BRCA2"
      }
    },
    "staticQuery": {
      "content-type": "application/json"
    }
  },
  {
    "handlerName": "suverse_bio_ensembl_gene_phenotypes",
    "slug": "suverse-bio-ensembl-gene-phenotypes",
    "category": "genomics",
    "sourceLabel": "ensembl",
    "upstreamMethod": "GET",
    "urlTemplate": "https://rest.ensembl.org/phenotype/gene/homo_sapiens/{symbol}",
    "timeoutMs": 12000,
    "params": {
      "symbol": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Human gene HGNC symbol",
        "example": "BRCA2"
      }
    },
    "staticQuery": {
      "content-type": "application/json"
    }
  },
  {
    "handlerName": "suverse_kb_media_list",
    "slug": "suverse-kb-media-list",
    "category": "knowledge",
    "sourceLabel": "wikimedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://en.wikipedia.org/api/rest_v1/page/media-list/{title}",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "title": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^.{1,120}$",
        "description": "Article title",
        "example": "Albert_Einstein"
      }
    }
  },
  {
    "handlerName": "suverse_kb_featured_feed",
    "slug": "suverse-kb-featured-feed",
    "category": "knowledge",
    "sourceLabel": "wikimedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://en.wikipedia.org/api/rest_v1/feed/featured/{year}/{month}/{day}",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Four-digit year",
        "example": "2024"
      },
      "month": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(0[1-9]|1[0-2])$",
        "description": "Two-digit month 01-12",
        "example": "06"
      },
      "day": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(0[1-9]|[12][0-9]|3[01])$",
        "description": "Two-digit day 01-31",
        "example": "01"
      }
    }
  },
  {
    "handlerName": "suverse_kb_pageviews_article",
    "slug": "suverse-kb-pageviews-article",
    "category": "knowledge",
    "sourceLabel": "wikimedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/{article}/daily/{start}/{end}",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "article": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^.{1,120}$",
        "description": "Article title (underscores for spaces)",
        "example": "Bitcoin"
      },
      "start": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{8}$",
        "description": "Start date YYYYMMDD",
        "example": "20240101"
      },
      "end": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{8}$",
        "description": "End date YYYYMMDD",
        "example": "20240131"
      }
    }
  },
  {
    "handlerName": "suverse_kb_pageviews_top",
    "slug": "suverse-kb-pageviews-top",
    "category": "knowledge",
    "sourceLabel": "wikimedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/en.wikipedia/all-access/{year}/{month}/{day}",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Four-digit year",
        "example": "2024"
      },
      "month": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(0[1-9]|1[0-2])$",
        "description": "Two-digit month 01-12",
        "example": "06"
      },
      "day": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^(0[1-9]|[12][0-9]|3[01])$",
        "description": "Two-digit day 01-31",
        "example": "01"
      }
    }
  },
  {
    "handlerName": "suverse_kb_new_pages",
    "slug": "suverse-kb-new-pages",
    "category": "knowledge",
    "sourceLabel": "wikimedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://wikimedia.org/api/rest_v1/metrics/edited-pages/new/en.wikipedia/all-editor-types/content/daily/{start}/{end}",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "start": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{8}$",
        "description": "Start date YYYYMMDD",
        "example": "20240101"
      },
      "end": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{8}$",
        "description": "End date YYYYMMDD",
        "example": "20240107"
      }
    }
  },
  {
    "handlerName": "suverse_kb_wikidata_entity",
    "slug": "suverse-kb-wikidata-entity",
    "category": "knowledge",
    "sourceLabel": "wikidata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.wikidata.org/w/api.php",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 12000,
    "params": {
      "ids": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^Q[0-9]+(\\|Q[0-9]+)*$",
        "description": "One or more Wikidata Q-ids, pipe-separated",
        "example": "Q42"
      }
    },
    "staticQuery": {
      "action": "wbgetentities",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_word_means_like",
    "slug": "suverse-word-means-like",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "ml": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word or phrase to find similar meanings for",
        "example": "ocean"
      }
    }
  },
  {
    "handlerName": "suverse_word_rhymes",
    "slug": "suverse-word-rhymes",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "rel_rhy": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word to find rhymes for",
        "example": "blue"
      }
    }
  },
  {
    "handlerName": "suverse_word_synonyms",
    "slug": "suverse-word-synonyms",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "rel_syn": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word to find synonyms for",
        "example": "fast"
      }
    }
  },
  {
    "handlerName": "suverse_word_antonyms",
    "slug": "suverse-word-antonyms",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "rel_ant": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word to find antonyms for",
        "example": "hot"
      }
    }
  },
  {
    "handlerName": "suverse_lang_translate_pair",
    "slug": "suverse-lang-translate-pair",
    "category": "language",
    "sourceLabel": "mymemory",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.mymemory.translated.net/get",
    "timeoutMs": 12000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Text to translate",
        "example": "guten tag"
      },
      "langpair": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[a-z]{2}\\|[a-z]{2}$",
        "description": "Source and target ISO 639-1 codes joined by a pipe, e.g. de|en",
        "example": "de|en"
      }
    }
  },
  {
    "handlerName": "suverse_word_sounds_like",
    "slug": "suverse-word-sounds-like",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "sl": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word or phonetic spelling to match by sound",
        "example": "jirraf"
      }
    }
  },
  {
    "handlerName": "suverse_ocean_tide_predictions",
    "slug": "suverse-ocean-tide-predictions",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS station id",
        "example": "9414290"
      },
      "units": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "english",
          "metric"
        ],
        "default": "english",
        "description": "Unit system",
        "example": "english"
      }
    },
    "staticQuery": {
      "product": "predictions",
      "application": "suverse-pay",
      "date": "today",
      "datum": "MLLW",
      "interval": "hilo",
      "time_zone": "lst_ldt",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_ocean_water_level",
    "slug": "suverse-ocean-water-level",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS station id",
        "example": "9414290"
      },
      "units": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "english",
          "metric"
        ],
        "default": "english",
        "description": "Unit system",
        "example": "english"
      }
    },
    "staticQuery": {
      "product": "water_level",
      "application": "suverse-pay",
      "date": "today",
      "datum": "MLLW",
      "time_zone": "lst_ldt",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_ocean_water_temp",
    "slug": "suverse-ocean-water-temp",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS station id with a water-temperature sensor",
        "example": "8454000"
      },
      "units": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "english",
          "metric"
        ],
        "default": "english",
        "description": "Unit system",
        "example": "english"
      }
    },
    "staticQuery": {
      "product": "water_temperature",
      "application": "suverse-pay",
      "date": "today",
      "time_zone": "lst_ldt",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_ocean_wind",
    "slug": "suverse-ocean-wind",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS station id",
        "example": "9414290"
      },
      "units": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "english",
          "metric"
        ],
        "default": "english",
        "description": "Unit system",
        "example": "english"
      }
    },
    "staticQuery": {
      "product": "wind",
      "application": "suverse-pay",
      "date": "today",
      "time_zone": "lst_ldt",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_ocean_currents_predictions",
    "slug": "suverse-ocean-currents-predictions",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS current station id",
        "example": "SFB1203"
      },
      "units": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "english",
          "metric"
        ],
        "default": "english",
        "description": "Unit system",
        "example": "english"
      }
    },
    "staticQuery": {
      "product": "currents_predictions",
      "application": "suverse-pay",
      "date": "today",
      "time_zone": "lst_ldt",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_ocean_station_info",
    "slug": "suverse-ocean-station-info",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/{station}.json",
    "timeoutMs": 12000,
    "params": {
      "station": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9A-Za-z]+$",
        "description": "NOAA CO-OPS station id",
        "example": "9414290"
      }
    }
  },
  {
    "handlerName": "suverse_ocean_stations_list",
    "slug": "suverse-ocean-stations-list",
    "category": "marine",
    "sourceLabel": "noaa-coops",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json",
    "timeoutMs": 12000,
    "params": {
      "type": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "waterlevels",
          "currents",
          "currentpredictions",
          "tidepredictions"
        ],
        "default": "waterlevels",
        "description": "Station product type filter",
        "example": "waterlevels"
      }
    }
  },
  {
    "handlerName": "suverse_ocean_wave_forecast",
    "slug": "suverse-ocean-wave-forecast",
    "category": "marine",
    "sourceLabel": "open-meteo-marine",
    "upstreamMethod": "GET",
    "urlTemplate": "https://marine-api.open-meteo.com/v1/marine",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude (decimal degrees)",
        "example": "37.8"
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude (decimal degrees)",
        "example": "-122.5"
      }
    },
    "staticQuery": {
      "hourly": "wave_height,wave_period,wave_direction,wind_wave_height,swell_wave_height",
      "timezone": "auto"
    }
  },
  {
    "handlerName": "suverse_ocean_wave_daily",
    "slug": "suverse-ocean-wave-daily",
    "category": "marine",
    "sourceLabel": "open-meteo-marine",
    "upstreamMethod": "GET",
    "urlTemplate": "https://marine-api.open-meteo.com/v1/marine",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude (decimal degrees)",
        "example": "37.8"
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude (decimal degrees)",
        "example": "-122.5"
      }
    },
    "staticQuery": {
      "daily": "wave_height_max,wave_direction_dominant,wave_period_max",
      "timezone": "auto"
    }
  },
  {
    "handlerName": "suverse_avwx_metar",
    "slug": "suverse-avwx-metar",
    "category": "aviation",
    "sourceLabel": "aviationweather-gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aviationweather.gov/api/data/metar",
    "timeoutMs": 12000,
    "params": {
      "ids": {
        "in": "query",
        "required": true,
        "type": "string",
        "transform": "upper",
        "description": "One or more ICAO ids, comma-separated",
        "example": "KJFK"
      }
    },
    "staticQuery": {
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_avwx_taf",
    "slug": "suverse-avwx-taf",
    "category": "aviation",
    "sourceLabel": "aviationweather-gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aviationweather.gov/api/data/taf",
    "timeoutMs": 12000,
    "params": {
      "ids": {
        "in": "query",
        "required": true,
        "type": "string",
        "transform": "upper",
        "description": "One or more ICAO ids, comma-separated",
        "example": "KJFK"
      }
    },
    "staticQuery": {
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_avwx_pirep",
    "slug": "suverse-avwx-pirep",
    "category": "aviation",
    "sourceLabel": "aviationweather-gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aviationweather.gov/api/data/pirep",
    "timeoutMs": 12000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "transform": "upper",
        "description": "ICAO airport id to center the search on",
        "example": "KJFK"
      }
    },
    "staticQuery": {
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_avwx_airsigmet",
    "slug": "suverse-avwx-airsigmet",
    "category": "aviation",
    "sourceLabel": "aviationweather-gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aviationweather.gov/api/data/airsigmet",
    "timeoutMs": 12000,
    "params": {
      "hazard": {
        "in": "query",
        "required": false,
        "type": "string",
        "enum": [
          "conv",
          "turb",
          "ice",
          "ifr"
        ],
        "description": "Optional hazard type filter",
        "example": "conv"
      }
    },
    "staticQuery": {
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_rel_prayer_times",
    "slug": "suverse-rel-prayer-times",
    "category": "religion",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/timingsByAddress",
    "timeoutMs": 12000,
    "params": {
      "address": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "City, address or place name to resolve",
        "example": "London,UK"
      },
      "method": {
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 2,
        "description": "Prayer calculation method id (e.g. 2=ISNA, 3=MWL)",
        "example": 2
      }
    }
  },
  {
    "handlerName": "suverse_rel_prayer_times_coords",
    "slug": "suverse-rel-prayer-times-coords",
    "category": "religion",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/timings/{date}",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Gregorian date as DD-MM-YYYY",
        "example": "20-06-2026"
      },
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude in decimal degrees",
        "example": 51.5
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude in decimal degrees",
        "example": -0.12
      },
      "method": {
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 2,
        "description": "Prayer calculation method id",
        "example": 2
      }
    }
  },
  {
    "handlerName": "suverse_rel_qibla_direction",
    "slug": "suverse-rel-qibla-direction",
    "category": "religion",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/qibla/{latitude}/{longitude}",
    "timeoutMs": 12000,
    "params": {
      "latitude": {
        "in": "path",
        "required": true,
        "type": "number",
        "description": "Latitude in decimal degrees",
        "example": 51.5
      },
      "longitude": {
        "in": "path",
        "required": true,
        "type": "number",
        "description": "Longitude in decimal degrees",
        "example": -0.12
      }
    }
  },
  {
    "handlerName": "suverse_rel_quran_ayah",
    "slug": "suverse-rel-quran-ayah",
    "category": "religion",
    "sourceLabel": "alquran-cloud",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.alquran.cloud/v1/ayah/{number}/{edition}",
    "timeoutMs": 12000,
    "params": {
      "number": {
        "in": "path",
        "required": true,
        "type": "integer",
        "description": "Global ayah number (1-6236)",
        "example": 262
      },
      "edition": {
        "in": "path",
        "required": false,
        "type": "string",
        "default": "en.asad",
        "description": "Edition identifier (e.g. en.asad, quran-uthmani)",
        "example": "en.asad"
      }
    }
  },
  {
    "handlerName": "suverse_rel_quran_surah",
    "slug": "suverse-rel-quran-surah",
    "category": "religion",
    "sourceLabel": "alquran-cloud",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.alquran.cloud/v1/surah/{number}/{edition}",
    "timeoutMs": 12000,
    "params": {
      "number": {
        "in": "path",
        "required": true,
        "type": "integer",
        "description": "Surah number (1-114)",
        "example": 2
      },
      "edition": {
        "in": "path",
        "required": false,
        "type": "string",
        "default": "en.asad",
        "description": "Edition identifier (e.g. en.asad, quran-uthmani)",
        "example": "en.asad"
      }
    }
  },
  {
    "handlerName": "suverse_rel_quran_99_names",
    "slug": "suverse-rel-quran-99-names",
    "category": "religion",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/asmaAlHusna",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_rel_bible_verse",
    "slug": "suverse-rel-bible-verse",
    "category": "religion",
    "sourceLabel": "bible-api",
    "upstreamMethod": "GET",
    "urlTemplate": "https://bible-api.com/{reference}",
    "timeoutMs": 12000,
    "params": {
      "reference": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Verse or passage reference (URL-encoded), e.g. 'John 3:16'",
        "example": "John 3:16"
      },
      "translation": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "web",
        "description": "Translation id (e.g. web, kjv)",
        "example": "kjv"
      }
    }
  },
  {
    "handlerName": "suverse_rel_bible_random",
    "slug": "suverse-rel-bible-random",
    "category": "religion",
    "sourceLabel": "bible-api",
    "upstreamMethod": "GET",
    "urlTemplate": "https://bible-api.com/data/{translation}/random",
    "timeoutMs": 12000,
    "params": {
      "translation": {
        "in": "path",
        "required": false,
        "type": "string",
        "default": "web",
        "description": "Translation id (e.g. web, kjv)",
        "example": "web"
      }
    }
  },
  {
    "handlerName": "suverse_cal_hijri_from_gregorian",
    "slug": "suverse-cal-hijri-from-gregorian",
    "category": "calendar",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/gToH/{date}",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Gregorian date as DD-MM-YYYY",
        "example": "20-06-2026"
      }
    }
  },
  {
    "handlerName": "suverse_cal_gregorian_from_hijri",
    "slug": "suverse-cal-gregorian-from-hijri",
    "category": "calendar",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/hToG/{date}",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Hijri date as DD-MM-YYYY",
        "example": "15-12-1447"
      }
    }
  },
  {
    "handlerName": "suverse_cal_prayer_month",
    "slug": "suverse-cal-prayer-month",
    "category": "calendar",
    "sourceLabel": "aladhan",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.aladhan.com/v1/calendar/{year}/{month}",
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "path",
        "required": true,
        "type": "integer",
        "description": "Gregorian year",
        "example": 2026
      },
      "month": {
        "in": "path",
        "required": true,
        "type": "integer",
        "description": "Gregorian month (1-12)",
        "example": 6
      },
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude in decimal degrees",
        "example": 51.5
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude in decimal degrees",
        "example": -0.12
      },
      "method": {
        "in": "query",
        "required": false,
        "type": "integer",
        "default": 2,
        "description": "Prayer calculation method id",
        "example": 2
      }
    }
  },
  {
    "handlerName": "suverse_cal_hebrew_date",
    "slug": "suverse-cal-hebrew-date",
    "category": "calendar",
    "sourceLabel": "hebcal",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.hebcal.com/converter",
    "timeoutMs": 12000,
    "params": {
      "gy": {
        "in": "query",
        "required": true,
        "type": "integer",
        "description": "Gregorian year",
        "example": 2026
      },
      "gm": {
        "in": "query",
        "required": true,
        "type": "integer",
        "description": "Gregorian month (1-12)",
        "example": 6
      },
      "gd": {
        "in": "query",
        "required": true,
        "type": "integer",
        "description": "Gregorian day of month",
        "example": 20
      }
    },
    "staticQuery": {
      "cfg": "json",
      "g2h": "1"
    }
  },
  {
    "handlerName": "suverse_space_people_in_space",
    "slug": "suverse-space-people-in-space",
    "category": "space",
    "sourceLabel": "opennotify",
    "upstreamMethod": "GET",
    "urlTemplate": "http://api.open-notify.org/astros.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_space_close_approaches",
    "slug": "suverse-space-close-approaches",
    "category": "space",
    "sourceLabel": "jpl-ssd",
    "upstreamMethod": "GET",
    "urlTemplate": "https://ssd-api.jpl.nasa.gov/cad.api",
    "timeoutMs": 14000,
    "params": {
      "date-min": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Start date (YYYY-MM-DD)",
        "example": "2026-01-01"
      },
      "date-max": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "End date (YYYY-MM-DD)",
        "example": "2026-12-31"
      },
      "dist-max": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "0.05",
        "description": "Maximum approach distance in astronomical units",
        "example": "0.05"
      }
    }
  },
  {
    "handlerName": "suverse_space_fireballs",
    "slug": "suverse-space-fireballs",
    "category": "space",
    "sourceLabel": "jpl-ssd",
    "upstreamMethod": "GET",
    "urlTemplate": "https://ssd-api.jpl.nasa.gov/fireball.api",
    "timeoutMs": 14000,
    "params": {
      "limit": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "20",
        "description": "Maximum number of fireball records to return",
        "example": "20"
      }
    }
  },
  {
    "handlerName": "suverse_space_impact_risk",
    "slug": "suverse-space-impact-risk",
    "category": "space",
    "sourceLabel": "jpl-ssd",
    "upstreamMethod": "GET",
    "urlTemplate": "https://ssd-api.jpl.nasa.gov/sentry.api",
    "timeoutMs": 14000,
    "params": {}
  },
  {
    "handlerName": "suverse_space_accessible_asteroids",
    "slug": "suverse-space-accessible-asteroids",
    "category": "space",
    "sourceLabel": "jpl-ssd",
    "upstreamMethod": "GET",
    "urlTemplate": "https://ssd-api.jpl.nasa.gov/nhats.api",
    "timeoutMs": 14000,
    "params": {}
  },
  {
    "handlerName": "suverse_space_neo_tracking",
    "slug": "suverse-space-neo-tracking",
    "category": "space",
    "sourceLabel": "jpl-ssd",
    "upstreamMethod": "GET",
    "urlTemplate": "https://ssd-api.jpl.nasa.gov/scout.api",
    "timeoutMs": 14000,
    "params": {}
  },
  {
    "handlerName": "suverse_space_moon_phases",
    "slug": "suverse-space-moon-phases",
    "category": "space",
    "sourceLabel": "usno",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aa.usno.navy.mil/api/moon/phases/date",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Start date (YYYY-MM-DD)",
        "example": "2026-06-20"
      },
      "nump": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "4",
        "description": "Number of upcoming phases to return",
        "example": "4"
      }
    }
  },
  {
    "handlerName": "suverse_space_seasons",
    "slug": "suverse-space-seasons",
    "category": "space",
    "sourceLabel": "usno",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aa.usno.navy.mil/api/seasons",
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Four-digit year",
        "example": "2026"
      }
    }
  },
  {
    "handlerName": "suverse_space_solar_eclipses",
    "slug": "suverse-space-solar-eclipses",
    "category": "space",
    "sourceLabel": "usno",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aa.usno.navy.mil/api/eclipses/solar/year",
    "timeoutMs": 12000,
    "params": {
      "year": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}$",
        "description": "Four-digit year",
        "example": "2026"
      }
    }
  },
  {
    "handlerName": "suverse_space_sun_moon_times",
    "slug": "suverse-space-sun-moon-times",
    "category": "space",
    "sourceLabel": "usno",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aa.usno.navy.mil/api/rstt/oneday",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Date (YYYY-MM-DD)",
        "example": "2026-06-20"
      },
      "coords": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Latitude,longitude in decimal degrees",
        "example": "38.9,-77.0"
      }
    }
  },
  {
    "handlerName": "suverse_space_sidereal_time",
    "slug": "suverse-space-sidereal-time",
    "category": "space",
    "sourceLabel": "usno",
    "upstreamMethod": "GET",
    "urlTemplate": "https://aa.usno.navy.mil/api/siderealtime",
    "timeoutMs": 12000,
    "params": {
      "date": {
        "in": "query",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "description": "Date (YYYY-MM-DD)",
        "example": "2026-06-20"
      },
      "coords": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Latitude,longitude in decimal degrees",
        "example": "38.9,-77.0"
      },
      "time": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Universal time HH:MM:SS",
        "example": "12:00:00"
      }
    },
    "staticQuery": {
      "reps": "1",
      "intv_mag": "1",
      "intv_unit": "hours"
    }
  },
  {
    "handlerName": "suverse_space_iss_orbit",
    "slug": "suverse-space-iss-orbit",
    "category": "space",
    "sourceLabel": "wheretheiss",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.wheretheiss.at/v1/satellites/25544",
    "timeoutMs": 12000,
    "params": {}
  }
];
