/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-013".
 * Do not hand-edit — re-run the pipeline. 10 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_013: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_usaspending_agencies",
    "slug": "suverse-usaspending-agencies",
    "category": "government",
    "sourceLabel": "USAspending",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.usaspending.gov/api/v2/references/toptier_agencies/",
    "timeoutMs": 20000,
    "params": {}
  },
  {
    "handlerName": "suverse_usaspending_agency_budget",
    "slug": "suverse-usaspending-agency-budget",
    "category": "government",
    "sourceLabel": "USAspending",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.usaspending.gov/api/v2/agency/{code}/budgetary_resources/",
    "timeoutMs": 20000,
    "params": {
      "code": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[0-9]{3}$",
        "description": "Three-digit federal toptier agency code, e.g. 012 for Agriculture, 097 for Defense.",
        "example": "012"
      }
    }
  },
  {
    "handlerName": "suverse_ukpolice_forces",
    "slug": "suverse-ukpolice-forces",
    "category": "government",
    "sourceLabel": "data.police.uk",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.police.uk/api/forces",
    "timeoutMs": 15000,
    "params": {}
  },
  {
    "handlerName": "suverse_ukpolice_force_detail",
    "slug": "suverse-ukpolice-force-detail",
    "category": "government",
    "sourceLabel": "data.police.uk",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.police.uk/api/forces/{force}",
    "timeoutMs": 15000,
    "params": {
      "force": {
        "in": "path",
        "required": true,
        "type": "string",
        "pattern": "^[a-z-]{3,60}$",
        "transform": "lower",
        "description": "UK police force identifier, e.g. metropolitan, west-midlands, greater-manchester.",
        "example": "metropolitan"
      }
    }
  },
  {
    "handlerName": "suverse_ukpolice_crime_categories",
    "slug": "suverse-ukpolice-crime-categories",
    "category": "government",
    "sourceLabel": "data.police.uk",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.police.uk/api/crime-categories",
    "timeoutMs": 15000,
    "params": {
      "date": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "date",
        "pattern": "^[0-9]{4}-[0-9]{2}$",
        "description": "Month in YYYY-MM form. Omit for the latest available month.",
        "example": "2026-05"
      }
    }
  },
  {
    "handlerName": "suverse_ukpolice_crimes_at_location",
    "slug": "suverse-ukpolice-crimes-at-location",
    "category": "government",
    "sourceLabel": "data.police.uk",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.police.uk/api/crimes-at-location",
    "timeoutMs": 20000,
    "params": {
      "lat": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "lat",
        "description": "Latitude in decimal degrees.",
        "example": "51.5074"
      },
      "lng": {
        "in": "query",
        "required": true,
        "type": "string",
        "upstreamName": "lng",
        "description": "Longitude in decimal degrees.",
        "example": "-0.1278"
      },
      "date": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "date",
        "pattern": "^[0-9]{4}-[0-9]{2}$",
        "description": "Month in YYYY-MM form. Omit for the latest available month.",
        "example": "2026-05"
      }
    }
  },
  {
    "handlerName": "suverse_ecb_policy_rate",
    "slug": "suverse-ecb-policy-rate",
    "category": "finance",
    "sourceLabel": "ECB Data Portal",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data-api.ecb.europa.eu/service/data/FM/D.U2.EUR.4F.KR.MRR_FR.LEV",
    "timeoutMs": 20000,
    "params": {
      "lastNObservations": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "lastNObservations",
        "default": 10,
        "description": "How many of the most recent observations to return, 1-500. Default 10.",
        "example": 10
      }
    },
    "staticQuery": {
      "format": "jsondata"
    }
  },
  {
    "handlerName": "suverse_ecb_yield_curve_10y",
    "slug": "suverse-ecb-yield-curve-10y",
    "category": "finance",
    "sourceLabel": "ECB Data Portal",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data-api.ecb.europa.eu/service/data/YC/B.U2.EUR.4F.G_N_A.SV_C_YM.SR_10Y",
    "timeoutMs": 20000,
    "params": {
      "lastNObservations": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "lastNObservations",
        "default": 10,
        "description": "How many of the most recent observations to return, 1-500. Default 10.",
        "example": 10
      }
    },
    "staticQuery": {
      "format": "jsondata"
    }
  },
  {
    "handlerName": "suverse_cftc_commitments_of_traders",
    "slug": "suverse-cftc-commitments-of-traders",
    "category": "finance",
    "sourceLabel": "CFTC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://publicreporting.cftc.gov/resource/6dca-aqww.json",
    "timeoutMs": 25000,
    "params": {
      "where": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "$where",
        "description": "Optional Socrata filter, e.g. market_and_exchange_names like '%GOLD%'. Omit for the most recent rows.",
        "example": "market_and_exchange_names like '%GOLD%'"
      },
      "limit": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "$limit",
        "default": 20,
        "description": "Maximum rows to return, 1-500. Default 20.",
        "example": 20
      }
    }
  },
  {
    "handlerName": "suverse_l2beat_scaling_summary",
    "slug": "suverse-l2beat-scaling-summary",
    "category": "crypto",
    "sourceLabel": "L2Beat",
    "upstreamMethod": "GET",
    "urlTemplate": "https://l2beat.com/api/scaling/summary",
    "timeoutMs": 25000,
    "params": {}
  }
];
