/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-003".
 * Do not hand-edit — re-run the pipeline. 100 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_003: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_wb_pop_density",
    "slug": "suverse-wb-pop-density",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/EN.POP.DNST",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_life_expectancy",
    "slug": "suverse-wb-life-expectancy",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.DYN.LE00.IN",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_gdp_per_capita",
    "slug": "suverse-wb-gdp-per-capita",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NY.GDP.PCAP.CD",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_gni_per_capita",
    "slug": "suverse-wb-gni-per-capita",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NY.GNP.PCAP.CD",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_poverty_headcount",
    "slug": "suverse-wb-poverty-headcount",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SI.POV.DDAY",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_gdp_growth",
    "slug": "suverse-wb-gdp-growth",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NY.GDP.MKTP.KD.ZG",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_exports_share",
    "slug": "suverse-wb-exports-share",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NE.EXP.GNFS.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_imports_share",
    "slug": "suverse-wb-imports-share",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NE.IMP.GNFS.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_fdi_inflows",
    "slug": "suverse-wb-fdi-inflows",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/BX.KLT.DINV.CD.WD",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_co2_per_capita",
    "slug": "suverse-wb-co2-per-capita",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/EN.ATM.CO2E.PC",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_internet_users",
    "slug": "suverse-wb-internet-users",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/IT.NET.USER.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_mobile_subscriptions",
    "slug": "suverse-wb-mobile-subscriptions",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/IT.CEL.SETS.P2",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_urban_population",
    "slug": "suverse-wb-urban-population",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.URB.TOTL.IN.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_gov_debt",
    "slug": "suverse-wb-gov-debt",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/GC.DOD.TOTL.GD.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_labor_force",
    "slug": "suverse-wb-labor-force",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SL.TLF.TOTL.IN",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_health_expenditure",
    "slug": "suverse-wb-health-expenditure",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SH.XPD.CHEX.GD.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_military_expenditure",
    "slug": "suverse-wb-military-expenditure",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/MS.MIL.XPND.GD.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_electricity_access",
    "slug": "suverse-wb-electricity-access",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/EG.ELC.ACCS.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_renewable_energy",
    "slug": "suverse-wb-renewable-energy",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/EG.FEC.RNEW.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_tertiary_enrollment",
    "slug": "suverse-wb-tertiary-enrollment",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SE.TER.ENRR",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_agriculture_value",
    "slug": "suverse-wb-agriculture-value",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NV.AGR.TOTL.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_manufacturing_value",
    "slug": "suverse-wb-manufacturing-value",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NV.IND.MANF.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_services_value",
    "slug": "suverse-wb-services-value",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/NV.SRV.TOTL.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_tax_revenue",
    "slug": "suverse-wb-tax-revenue",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/GC.TAX.TOTL.GD.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_birth_rate",
    "slug": "suverse-wb-birth-rate",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.DYN.CBRT.IN",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_death_rate",
    "slug": "suverse-wb-death-rate",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.DYN.CDRT.IN",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_fertility_rate",
    "slug": "suverse-wb-fertility-rate",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.DYN.TFRT.IN",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_population_growth",
    "slug": "suverse-wb-population-growth",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SP.POP.GROW",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_real_interest_rate",
    "slug": "suverse-wb-real-interest-rate",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/FR.INR.RINR",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_wb_youth_unemployment",
    "slug": "suverse-wb-youth-unemployment",
    "category": "macro",
    "sourceLabel": "worldbank",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.worldbank.org/v2/country/{country}/indicator/SL.UEM.1524.ZS",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISO 2 or 3 letter country code",
        "example": "US",
        "pattern": "^[A-Za-z]{2,3}$",
        "transform": "upper"
      }
    },
    "staticQuery": {
      "format": "json",
      "per_page": "30"
    }
  },
  {
    "handlerName": "suverse_nlm_icd10cm",
    "slug": "suverse-nlm-icd10cm",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/icd10cm/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "diabetes"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_nlm_conditions",
    "slug": "suverse-nlm-conditions",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/conditions/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "asthma"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_nlm_rxterms",
    "slug": "suverse-nlm-rxterms",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/rxterms/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "metformin"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_nlm_npi_individual",
    "slug": "suverse-nlm-npi-individual",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/npi_idv/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "john smith"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_nlm_npi_organization",
    "slug": "suverse-nlm-npi-organization",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/npi_org/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "mayo clinic"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_nlm_hcpcs",
    "slug": "suverse-nlm-hcpcs",
    "category": "health",
    "sourceLabel": "nlm-clinicaltables",
    "upstreamMethod": "GET",
    "urlTemplate": "https://clinicaltables.nlm.nih.gov/api/hcpcs/v3/search",
    "timeoutMs": 10000,
    "params": {
      "terms": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search terms",
        "example": "wheelchair"
      }
    },
    "staticQuery": {
      "maxList": "10"
    }
  },
  {
    "handlerName": "suverse_openfda_drug_ndc",
    "slug": "suverse-openfda-drug-ndc",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/drug/ndc.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_openfda_device_510k",
    "slug": "suverse-openfda-device-510k",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/device/510k.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_openfda_device_classification",
    "slug": "suverse-openfda-device-classification",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/device/classification.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_openfda_food_event",
    "slug": "suverse-openfda-food-event",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/food/event.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_openfda_tobacco_problem",
    "slug": "suverse-openfda-tobacco-problem",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/tobacco/problem.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_openfda_animalvet_event",
    "slug": "suverse-openfda-animalvet-event",
    "category": "health",
    "sourceLabel": "openfda",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fda.gov/animalandveterinary/event.json",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": false,
        "type": "string",
        "description": "openFDA search expression",
        "example": ""
      }
    },
    "staticQuery": {
      "limit": "5"
    }
  },
  {
    "handlerName": "suverse_rxnorm_approximate",
    "slug": "suverse-rxnorm-approximate",
    "category": "health",
    "sourceLabel": "rxnorm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://rxnav.nlm.nih.gov/REST/approximateTerm.json",
    "timeoutMs": 10000,
    "params": {
      "term": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Drug name term",
        "example": "ibuprofin"
      }
    },
    "staticQuery": {
      "maxEntries": "5"
    }
  },
  {
    "handlerName": "suverse_rxnorm_spelling",
    "slug": "suverse-rxnorm-spelling",
    "category": "health",
    "sourceLabel": "rxnorm",
    "upstreamMethod": "GET",
    "urlTemplate": "https://rxnav.nlm.nih.gov/REST/spellingsuggestions.json",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Drug name",
        "example": "ibuprofin"
      }
    }
  },
  {
    "handlerName": "suverse_disease_covid_global",
    "slug": "suverse-disease-covid-global",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/all",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_disease_covid_historical",
    "slug": "suverse-disease-covid-historical",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/historical/{country}",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Country name or ISO code",
        "example": "USA"
      }
    },
    "staticQuery": {
      "lastdays": "30"
    }
  },
  {
    "handlerName": "suverse_disease_vaccine_coverage",
    "slug": "suverse-disease-vaccine-coverage",
    "category": "health",
    "sourceLabel": "disease.sh",
    "upstreamMethod": "GET",
    "urlTemplate": "https://disease.sh/v3/covid-19/vaccine/coverage/countries/{country}",
    "timeoutMs": 10000,
    "params": {
      "country": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Country name or ISO code",
        "example": "USA"
      }
    },
    "staticQuery": {
      "lastdays": "30"
    }
  },
  {
    "handlerName": "suverse_openlibrary_search",
    "slug": "suverse-openlibrary-search",
    "category": "books",
    "sourceLabel": "openlibrary",
    "upstreamMethod": "GET",
    "urlTemplate": "https://openlibrary.org/search.json",
    "timeoutMs": 10000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search query",
        "example": "the hobbit"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_openlibrary_isbn",
    "slug": "suverse-openlibrary-isbn",
    "category": "books",
    "sourceLabel": "openlibrary",
    "upstreamMethod": "GET",
    "urlTemplate": "https://openlibrary.org/isbn/{isbn}.json",
    "timeoutMs": 10000,
    "params": {
      "isbn": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "ISBN-10 or ISBN-13",
        "example": "9780261103283",
        "pattern": "^[0-9Xx-]{10,17}$"
      }
    }
  },
  {
    "handlerName": "suverse_openlibrary_subject",
    "slug": "suverse-openlibrary-subject",
    "category": "books",
    "sourceLabel": "openlibrary",
    "upstreamMethod": "GET",
    "urlTemplate": "https://openlibrary.org/subjects/{subject}.json",
    "timeoutMs": 10000,
    "params": {
      "subject": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Subject keyword",
        "example": "science_fiction",
        "transform": "lower",
        "pattern": "^[a-zA-Z_]+$"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_openlibrary_authors",
    "slug": "suverse-openlibrary-authors",
    "category": "books",
    "sourceLabel": "openlibrary",
    "upstreamMethod": "GET",
    "urlTemplate": "https://openlibrary.org/search/authors.json",
    "timeoutMs": 10000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Author name",
        "example": "tolkien"
      }
    }
  },
  {
    "handlerName": "suverse_gutenberg_books",
    "slug": "suverse-gutenberg-books",
    "category": "books",
    "sourceLabel": "gutendex",
    "upstreamMethod": "GET",
    "urlTemplate": "https://gutendex.com/books",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search query",
        "example": "shakespeare"
      }
    }
  },
  {
    "handlerName": "suverse_wiki_random",
    "slug": "suverse-wiki-random",
    "category": "knowledge",
    "sourceLabel": "wikipedia",
    "upstreamMethod": "GET",
    "urlTemplate": "https://en.wikipedia.org/api/rest_v1/page/random/summary",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_wikidata_search",
    "slug": "suverse-wikidata-search",
    "category": "knowledge",
    "sourceLabel": "wikidata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.wikidata.org/w/api.php",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Entity label to search",
        "example": "Ethereum"
      }
    },
    "staticQuery": {
      "action": "wbsearchentities",
      "language": "en",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_dictionary",
    "slug": "suverse-dictionary",
    "category": "language",
    "sourceLabel": "dictionaryapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.dictionaryapi.dev/api/v2/entries/en/{word}",
    "timeoutMs": 10000,
    "params": {
      "word": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "English word",
        "example": "serendipity",
        "pattern": "^[a-zA-Z-]{1,40}$",
        "transform": "lower"
      }
    }
  },
  {
    "handlerName": "suverse_datamuse_related",
    "slug": "suverse-datamuse-related",
    "category": "language",
    "sourceLabel": "datamuse",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.datamuse.com/words",
    "timeoutMs": 10000,
    "params": {
      "ml": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Word to find associations for",
        "example": "ocean"
      }
    }
  },
  {
    "handlerName": "suverse_openalex_sources",
    "slug": "suverse-openalex-sources",
    "category": "academic",
    "sourceLabel": "openalex",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.openalex.org/sources",
    "timeoutMs": 10000,
    "params": {
      "search": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Source name",
        "example": "nature"
      }
    },
    "staticQuery": {
      "per-page": "10",
      "mailto": "data@suverse.io"
    }
  },
  {
    "handlerName": "suverse_meal_search",
    "slug": "suverse-meal-search",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/search.php",
    "timeoutMs": 10000,
    "params": {
      "s": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Meal name",
        "example": "arrabiata"
      }
    }
  },
  {
    "handlerName": "suverse_meal_lookup",
    "slug": "suverse-meal-lookup",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/lookup.php",
    "timeoutMs": 10000,
    "params": {
      "i": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Meal id",
        "example": "52771",
        "pattern": "^[0-9]{4,7}$"
      }
    }
  },
  {
    "handlerName": "suverse_meal_random",
    "slug": "suverse-meal-random",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/random.php",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_meal_by_category",
    "slug": "suverse-meal-by-category",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/filter.php",
    "timeoutMs": 10000,
    "params": {
      "c": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Category, e.g. Seafood, Dessert, Vegetarian",
        "example": "Seafood",
        "pattern": "^[A-Za-z ]{3,20}$"
      }
    }
  },
  {
    "handlerName": "suverse_meal_by_ingredient",
    "slug": "suverse-meal-by-ingredient",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/filter.php",
    "timeoutMs": 10000,
    "params": {
      "i": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Main ingredient",
        "example": "chicken_breast",
        "pattern": "^[A-Za-z_ ]{3,30}$"
      }
    }
  },
  {
    "handlerName": "suverse_meal_categories",
    "slug": "suverse-meal-categories",
    "category": "food",
    "sourceLabel": "themealdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.themealdb.com/api/json/v1/1/categories.php",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_cocktail_search",
    "slug": "suverse-cocktail-search",
    "category": "food",
    "sourceLabel": "thecocktaildb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thecocktaildb.com/api/json/v1/1/search.php",
    "timeoutMs": 10000,
    "params": {
      "s": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Cocktail name",
        "example": "margarita"
      }
    }
  },
  {
    "handlerName": "suverse_cocktail_random",
    "slug": "suverse-cocktail-random",
    "category": "food",
    "sourceLabel": "thecocktaildb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thecocktaildb.com/api/json/v1/1/random.php",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_cocktail_by_ingredient",
    "slug": "suverse-cocktail-by-ingredient",
    "category": "food",
    "sourceLabel": "thecocktaildb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thecocktaildb.com/api/json/v1/1/filter.php",
    "timeoutMs": 10000,
    "params": {
      "i": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Ingredient",
        "example": "Gin",
        "pattern": "^[A-Za-z ]{2,30}$"
      }
    }
  },
  {
    "handlerName": "suverse_food_barcode",
    "slug": "suverse-food-barcode",
    "category": "food",
    "sourceLabel": "openfoodfacts",
    "upstreamMethod": "GET",
    "urlTemplate": "https://world.openfoodfacts.org/api/v2/product/{barcode}.json",
    "timeoutMs": 10000,
    "params": {
      "barcode": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Product barcode (EAN/UPC)",
        "example": "737628064502",
        "pattern": "^[0-9]{8,14}$"
      }
    }
  },
  {
    "handlerName": "suverse_sports_player",
    "slug": "suverse-sports-player",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/searchplayers.php",
    "timeoutMs": 10000,
    "params": {
      "p": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Player name",
        "example": "Messi"
      }
    }
  },
  {
    "handlerName": "suverse_sports_leagues",
    "slug": "suverse-sports-leagues",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/all_leagues.php",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_sports_next_events",
    "slug": "suverse-sports-next-events",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/eventsnext.php",
    "timeoutMs": 10000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Team id",
        "example": "133604",
        "pattern": "^[0-9]{5,8}$"
      }
    }
  },
  {
    "handlerName": "suverse_sports_last_events",
    "slug": "suverse-sports-last-events",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/eventslast.php",
    "timeoutMs": 10000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Team id",
        "example": "133604",
        "pattern": "^[0-9]{5,8}$"
      }
    }
  },
  {
    "handlerName": "suverse_sports_league_detail",
    "slug": "suverse-sports-league-detail",
    "category": "sports",
    "sourceLabel": "thesportsdb",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.thesportsdb.com/api/v1/json/3/lookupleague.php",
    "timeoutMs": 10000,
    "params": {
      "id": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "League id",
        "example": "4328",
        "pattern": "^[0-9]{3,7}$"
      }
    }
  },
  {
    "handlerName": "suverse_nhl_standings",
    "slug": "suverse-nhl-standings",
    "category": "sports",
    "sourceLabel": "nhl",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api-web.nhle.com/v1/standings/now",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_nhl_scores",
    "slug": "suverse-nhl-scores",
    "category": "sports",
    "sourceLabel": "nhl",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api-web.nhle.com/v1/score/{date}",
    "timeoutMs": 10000,
    "params": {
      "date": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Date YYYY-MM-DD",
        "example": "2026-01-15",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
      }
    }
  },
  {
    "handlerName": "suverse_reverse_geocode",
    "slug": "suverse-reverse-geocode",
    "category": "geo",
    "sourceLabel": "bigdatacloud",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.bigdatacloud.net/data/reverse-geocode-client",
    "timeoutMs": 10000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude",
        "example": 48.85
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude",
        "example": 2.35
      }
    },
    "staticQuery": {
      "localityLanguage": "en"
    }
  },
  {
    "handlerName": "suverse_country_by_name",
    "slug": "suverse-country-by-name",
    "category": "geo",
    "sourceLabel": "restcountries",
    "upstreamMethod": "GET",
    "urlTemplate": "https://restcountries.com/v3.1/name/{name}",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Country name",
        "example": "france",
        "pattern": "^[A-Za-z ]{2,40}$",
        "transform": "lower"
      }
    },
    "staticQuery": {
      "fields": "name,capital,region,population,currencies,languages"
    }
  },
  {
    "handlerName": "suverse_countries_by_region",
    "slug": "suverse-countries-by-region",
    "category": "geo",
    "sourceLabel": "restcountries",
    "upstreamMethod": "GET",
    "urlTemplate": "https://restcountries.com/v3.1/region/{region}",
    "timeoutMs": 10000,
    "params": {
      "region": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Region, e.g. europe, asia, africa",
        "example": "europe",
        "pattern": "^[A-Za-z]{3,15}$",
        "transform": "lower"
      }
    },
    "staticQuery": {
      "fields": "name,capital,population"
    }
  },
  {
    "handlerName": "suverse_sunrise_sunset",
    "slug": "suverse-sunrise-sunset",
    "category": "geo",
    "sourceLabel": "sunrise-sunset",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.sunrise-sunset.org/json",
    "timeoutMs": 10000,
    "params": {
      "lat": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude",
        "example": 36.72
      },
      "lng": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude",
        "example": -4.42
      }
    },
    "staticQuery": {
      "formatted": "0"
    }
  },
  {
    "handlerName": "suverse_uk_postcode",
    "slug": "suverse-uk-postcode",
    "category": "geo",
    "sourceLabel": "postcodes.io",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.postcodes.io/postcodes/{postcode}",
    "timeoutMs": 10000,
    "params": {
      "postcode": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "UK postcode",
        "example": "SW1A1AA",
        "pattern": "^[A-Za-z0-9 ]{5,8}$"
      }
    }
  },
  {
    "handlerName": "suverse_us_address_geocode",
    "slug": "suverse-us-address-geocode",
    "category": "geo",
    "sourceLabel": "census",
    "upstreamMethod": "GET",
    "urlTemplate": "https://geocoding.geo.census.gov/geocoder/locations/onelineaddress",
    "timeoutMs": 10000,
    "params": {
      "address": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "One-line US street address",
        "example": "1600 Pennsylvania Ave NW, Washington DC"
      }
    },
    "staticQuery": {
      "benchmark": "Public_AR_Current",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_river_discharge",
    "slug": "suverse-river-discharge",
    "category": "geo",
    "sourceLabel": "open-meteo",
    "upstreamMethod": "GET",
    "urlTemplate": "https://flood-api.open-meteo.com/v1/flood",
    "timeoutMs": 10000,
    "params": {
      "latitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Latitude",
        "example": 52.52
      },
      "longitude": {
        "in": "query",
        "required": true,
        "type": "number",
        "description": "Longitude",
        "example": 13.41
      }
    },
    "staticQuery": {
      "daily": "river_discharge"
    }
  },
  {
    "handlerName": "suverse_federal_register_search",
    "slug": "suverse-federal-register-search",
    "category": "government",
    "sourceLabel": "federalregister",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.federalregister.gov/api/v1/documents.json",
    "timeoutMs": 10000,
    "params": {
      "term": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search term",
        "example": "artificial intelligence",
        "upstreamName": "conditions[term]"
      }
    },
    "staticQuery": {
      "per_page": "10",
      "conditions[term]": ""
    }
  },
  {
    "handlerName": "suverse_federal_agencies",
    "slug": "suverse-federal-agencies",
    "category": "government",
    "sourceLabel": "federalregister",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.federalregister.gov/api/v1/agencies",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_name_age",
    "slug": "suverse-name-age",
    "category": "social",
    "sourceLabel": "agify",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.agify.io",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "First name",
        "example": "michael"
      }
    }
  },
  {
    "handlerName": "suverse_name_gender",
    "slug": "suverse-name-gender",
    "category": "social",
    "sourceLabel": "genderize",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.genderize.io",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "First name",
        "example": "alex"
      }
    }
  },
  {
    "handlerName": "suverse_name_nationality",
    "slug": "suverse-name-nationality",
    "category": "social",
    "sourceLabel": "nationalize",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.nationalize.io",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "First name",
        "example": "wei"
      }
    }
  },
  {
    "handlerName": "suverse_bls_series",
    "slug": "suverse-bls-series",
    "category": "macro",
    "sourceLabel": "bls",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.bls.gov/publicAPI/v1/timeseries/data/{seriesid}",
    "timeoutMs": 10000,
    "params": {
      "seriesid": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "BLS series id, e.g. CUUR0000SA0 (CPI-U)",
        "example": "CUUR0000SA0",
        "pattern": "^[A-Za-z0-9]{6,20}$"
      }
    }
  },
  {
    "handlerName": "suverse_coinbase_rates",
    "slug": "suverse-coinbase-rates",
    "category": "forex",
    "sourceLabel": "coinbase",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.coinbase.com/v2/exchange-rates",
    "timeoutMs": 10000,
    "params": {
      "currency": {
        "in": "query",
        "required": false,
        "type": "string",
        "default": "USD",
        "pattern": "^[A-Za-z]{2,6}$",
        "transform": "upper",
        "description": "Base currency code",
        "example": "USD"
      }
    }
  },
  {
    "handlerName": "suverse_treasury_gold_reserves",
    "slug": "suverse-treasury-gold-reserves",
    "category": "treasury",
    "sourceLabel": "treasury.fiscaldata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/gold_reserve",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {},
    "staticQuery": {
      "sort": "-record_date",
      "page[size]": "20",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_treasury_savings_bonds",
    "slug": "suverse-treasury-savings-bonds",
    "category": "treasury",
    "sourceLabel": "treasury.fiscaldata",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/savings_bonds_pcs",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {},
    "staticQuery": {
      "sort": "-record_date",
      "page[size]": "12",
      "format": "json"
    }
  },
  {
    "handlerName": "suverse_sec_tickers",
    "slug": "suverse-sec-tickers",
    "category": "sec-filings",
    "sourceLabel": "sec.edgar",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.sec.gov/files/company_tickers.json",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 15000,
    "params": {}
  },
  {
    "handlerName": "suverse_sec_frames",
    "slug": "suverse-sec-frames",
    "category": "sec-filings",
    "sourceLabel": "sec.edgar",
    "upstreamMethod": "GET",
    "urlTemplate": "https://data.sec.gov/api/xbrl/frames/us-gaap/{tag}/USD/CY{period}.json",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 15000,
    "params": {
      "tag": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "XBRL concept tag",
        "example": "Assets",
        "pattern": "^[A-Za-z]{2,60}$"
      },
      "period": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Period, e.g. 2023Q4I or 2023",
        "example": "2023Q4I",
        "pattern": "^[0-9]{4}(Q[1-4]I?)?$"
      }
    }
  },
  {
    "handlerName": "suverse_quakes_week_major",
    "slug": "suverse-quakes-week-major",
    "category": "science",
    "sourceLabel": "usgs",
    "upstreamMethod": "GET",
    "urlTemplate": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_usgs_streamflow",
    "slug": "suverse-usgs-streamflow",
    "category": "science",
    "sourceLabel": "usgs",
    "upstreamMethod": "GET",
    "urlTemplate": "https://waterservices.usgs.gov/nwis/iv",
    "timeoutMs": 10000,
    "params": {
      "sites": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "USGS site number",
        "example": "01646500",
        "pattern": "^[0-9]{8,15}$"
      }
    },
    "staticQuery": {
      "format": "json",
      "parameterCd": "00060"
    }
  },
  {
    "handlerName": "suverse_eonet_categories",
    "slug": "suverse-eonet-categories",
    "category": "science",
    "sourceLabel": "nasa-eonet",
    "upstreamMethod": "GET",
    "urlTemplate": "https://eonet.gsfc.nasa.gov/api/v3/categories",
    "timeoutMs": 10000,
    "params": {}
  },
  {
    "handlerName": "suverse_met_search",
    "slug": "suverse-met-search",
    "category": "culture",
    "sourceLabel": "metmuseum",
    "upstreamMethod": "GET",
    "urlTemplate": "https://collectionapi.metmuseum.org/public/collection/v1/search",
    "timeoutMs": 10000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search keyword",
        "example": "sunflowers"
      }
    },
    "staticQuery": {
      "hasImages": "true"
    }
  },
  {
    "handlerName": "suverse_met_object",
    "slug": "suverse-met-object",
    "category": "culture",
    "sourceLabel": "metmuseum",
    "upstreamMethod": "GET",
    "urlTemplate": "https://collectionapi.metmuseum.org/public/collection/v1/objects/{objectID}",
    "timeoutMs": 10000,
    "params": {
      "objectID": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Met object id",
        "example": "436524",
        "pattern": "^[0-9]{1,7}$"
      }
    }
  },
  {
    "handlerName": "suverse_artic_search",
    "slug": "suverse-artic-search",
    "category": "culture",
    "sourceLabel": "artic",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.artic.edu/api/v1/artworks/search",
    "timeoutMs": 10000,
    "params": {
      "q": {
        "in": "query",
        "required": true,
        "type": "string",
        "description": "Search keyword",
        "example": "monet"
      }
    },
    "staticQuery": {
      "limit": "10"
    }
  },
  {
    "handlerName": "suverse_pokemon",
    "slug": "suverse-pokemon",
    "category": "games",
    "sourceLabel": "pokeapi",
    "upstreamMethod": "GET",
    "urlTemplate": "https://pokeapi.co/api/v2/pokemon/{name}",
    "timeoutMs": 10000,
    "params": {
      "name": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "Pokemon name",
        "example": "pikachu",
        "pattern": "^[a-zA-Z-]{2,30}$",
        "transform": "lower"
      }
    }
  },
  {
    "handlerName": "suverse_nws_station_obs",
    "slug": "suverse-nws-station-obs",
    "category": "weather",
    "sourceLabel": "nws.weather.gov",
    "upstreamMethod": "GET",
    "urlTemplate": "https://api.weather.gov/stations/{stationId}/observations/latest",
    "headers": {
      "User-Agent": "SuVersePay data@suverse.io"
    },
    "timeoutMs": 10000,
    "params": {
      "stationId": {
        "in": "path",
        "required": true,
        "type": "string",
        "description": "NWS station id, e.g. KNYC",
        "example": "KNYC",
        "pattern": "^[A-Za-z0-9]{3,6}$",
        "transform": "upper"
      }
    }
  }
];
