/**
 * GENERATED by scripts/pipeline/wrap-batch.mjs from batch "batch-012".
 * Do not hand-edit — re-run the pipeline. 10 endpoints.
 */
import type { DeclarativeSpec } from "./types.js";

export const SPECS_BATCH_012: DeclarativeSpec[] = [
  {
    "handlerName": "suverse_swpc_solar_flare_latest",
    "slug": "suverse-swpc-solar-flare-latest",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/json/goes/primary/xray-flares-latest.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_solar_flares_7day",
    "slug": "suverse-swpc-solar-flares-7day",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/json/goes/primary/xray-flares-7-day.json",
    "timeoutMs": 15000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_kp_index",
    "slug": "suverse-swpc-kp-index",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_solar_wind_speed",
    "slug": "suverse-swpc-solar-wind-speed",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/products/summary/solar-wind-speed.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_solar_wind_mag",
    "slug": "suverse-swpc-solar-wind-mag",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/products/summary/solar-wind-mag-field.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_f107_flux",
    "slug": "suverse-swpc-f107-flux",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/products/summary/10cm-flux.json",
    "timeoutMs": 12000,
    "params": {}
  },
  {
    "handlerName": "suverse_swpc_space_weather_alerts",
    "slug": "suverse-swpc-space-weather-alerts",
    "category": "space-weather",
    "sourceLabel": "NOAA SWPC",
    "upstreamMethod": "GET",
    "urlTemplate": "https://services.swpc.noaa.gov/products/alerts.json",
    "timeoutMs": 15000,
    "params": {}
  },
  {
    "handlerName": "suverse_fema_disaster_declarations",
    "slug": "suverse-fema-disaster-declarations",
    "category": "government",
    "sourceLabel": "OpenFEMA",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries",
    "timeoutMs": 20000,
    "params": {
      "filter": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "$filter",
        "description": "OData filter expression, e.g. state eq 'CA' or incidentType eq 'Fire'. Omit for the most recent declarations nationwide.",
        "example": "state eq 'CA'"
      },
      "top": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "$top",
        "default": 20,
        "description": "Maximum records to return, 1-200. Default 20.",
        "example": 20
      }
    },
    "staticQuery": {
      "$format": "json"
    }
  },
  {
    "handlerName": "suverse_fema_nfip_claims",
    "slug": "suverse-fema-nfip-claims",
    "category": "government",
    "sourceLabel": "OpenFEMA",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.fema.gov/api/open/v2/FimaNfipClaims",
    "timeoutMs": 25000,
    "params": {
      "filter": {
        "in": "query",
        "required": false,
        "type": "string",
        "upstreamName": "$filter",
        "description": "OData filter expression, e.g. state eq 'TX' or reportedZipCode eq '77001'. Omit for an unfiltered sample.",
        "example": "state eq 'TX'"
      },
      "top": {
        "in": "query",
        "required": false,
        "type": "integer",
        "upstreamName": "$top",
        "default": 20,
        "description": "Maximum claim records to return, 1-200. Default 20.",
        "example": 20
      }
    },
    "staticQuery": {
      "$format": "json"
    }
  },
  {
    "handlerName": "suverse_gdacs_disaster_events",
    "slug": "suverse-gdacs-disaster-events",
    "category": "hazard",
    "sourceLabel": "GDACS",
    "upstreamMethod": "GET",
    "urlTemplate": "https://www.gdacs.org/gdacsapi/api/events/geteventlist/EVENTS4APP",
    "timeoutMs": 25000,
    "params": {},
    "pick": [
      "type",
      "features",
      "bbox"
    ]
  }
];
