// Generate a fresh BIP-39 mnemonic, derive the default Ethereum HD account
// at m/44'/60'/0'/0/0, and print ONLY the address. The mnemonic is written
// to .env.evm-sepolia (mode 600, gitignored).
import { existsSync, writeFileSync, chmodSync } from "node:fs";
import { generateMnemonic, english } from "viem/accounts";
import { deriveEvmAccount } from "../src/index.js";

const envPath = "/home/govhub/suverse-pay/.env.evm-sepolia";
if (existsSync(envPath)) {
  console.error(`refusing to overwrite existing ${envPath}`);
  process.exit(1);
}

const mnemonic = generateMnemonic(english);
const account = deriveEvmAccount(mnemonic);

const contents = [
  "# Generated by scripts/dev/gen-evm-sepolia-wallet.mts.",
  "# DO NOT COMMIT. Used by scripts/smoke/real-evm/ to sign EIP-3009",
  "# payloads on Base Sepolia testnet. Mode 600.",
  "",
  `EVM_TESTNET_MNEMONIC="${mnemonic}"`,
  `EVM_TESTNET_ADDRESS=${account.address}`,
  "",
].join("\n");

writeFileSync(envPath, contents, { encoding: "utf8" });
chmodSync(envPath, 0o600);

console.log("Wallet generated.");
console.log("Address:", account.address);
console.log("Stored at:", envPath, "(mode 600)");
