import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Webhook signature scheme — Stripe-compatible.
 *
 * On send:
 *   header = `X-Suverse-Pay-Signature: t=<unix_seconds>,v1=<hex>`
 *   v1 = HMAC_SHA256(secret_plaintext, `${unix_seconds}.${body}`)
 *
 * On receive (customer side):
 *   parse the header → get `t` and `v1`
 *   recompute v1 using your stored secret + the raw request body
 *   compare via constant-time equality
 *   reject if `t` is older than your tolerance (default 5 minutes —
 *     stops replay of an old captured payload)
 *
 * Why this format:
 *   - `t=` in the signed payload binds the signature to a moment in
 *     time, defeating "capture a webhook, replay it tomorrow"
 *   - constant-time compare is the only safe primitive for HMAC equality
 *   - keeping the wire format identical to Stripe's means receivers
 *     can reuse battle-tested libraries (stripe-node, stripe-php, etc.
 *     all parse this exact shape via `stripe.webhooks.constructEvent`)
 *
 * The plaintext secret is generated by `generateSecretPlaintext()`,
 * shown to the customer EXACTLY ONCE at endpoint creation time, and
 * stored as a sha256 hash in webhook_endpoints.secret_hash. The hash
 * is what the worker reads at delivery time — see
 * `hashSecretForStorage` + `findEndpointSecret` in endpoints-store.ts.
 */

export const SIGNATURE_HEADER = "X-Suverse-Pay-Signature";
export const EVENT_ID_HEADER = "X-Suverse-Pay-Event-Id";
export const EVENT_TYPE_HEADER = "X-Suverse-Pay-Event-Type";

/** Stripe-style secret format. `whsec_` prefix is widely recognised. */
export function generateSecretPlaintext(): string {
  // 32 random bytes → 64 base64url chars after the prefix. ~256 bits
  // of entropy — sufficient even though the hash is sha256 (no salt).
  return `whsec_${randomBytes(32).toString("base64url")}`;
}

/** Storage-side hash. Matches the resource-key + admin-key pattern. */
export function hashSecretForStorage(plaintext: string): string {
  return createHash("sha256").update(plaintext, "utf8").digest("hex");
}

export interface SignArgs {
  /** Raw HMAC secret as the customer would store it client-side. */
  secret: string;
  /** Raw JSON body bytes that will be sent. */
  body: string;
  /** Unix seconds. Caller passes Date.now()/1000 in production; tests pin it. */
  timestamp: number;
}

/**
 * Compute the header value to attach as `X-Suverse-Pay-Signature`.
 * The format is `t=<ts>,v1=<hex>`; `v1` is the only scheme today,
 * future scheme upgrades can add `,v2=...` alongside without
 * breaking existing receivers (they MUST ignore unknown schemes).
 */
export function signWebhook(args: SignArgs): string {
  const signed = `${args.timestamp}.${args.body}`;
  const v1 = createHmac("sha256", args.secret).update(signed).digest("hex");
  return `t=${args.timestamp},v1=${v1}`;
}

export interface VerifyArgs {
  secret: string;
  body: string;
  /** The literal `X-Suverse-Pay-Signature` header value. */
  header: string;
  /**
   * Reject if `t` is more than this many seconds away from `now`.
   * Default 300 (5 minutes). Stripe's default; widely accepted.
   */
  toleranceSeconds?: number;
  /** Override now() for tests. */
  now?: number;
}

/** Verification result — caller treats false as "reject the request". */
export function verifyWebhook(args: VerifyArgs): boolean {
  const tolerance = args.toleranceSeconds ?? 300;
  const now = args.now ?? Math.floor(Date.now() / 1000);
  const parts = args.header.split(",");
  let timestamp: number | null = null;
  let v1: string | null = null;
  for (const part of parts) {
    const eq = part.indexOf("=");
    if (eq === -1) continue;
    const k = part.slice(0, eq).trim();
    const v = part.slice(eq + 1).trim();
    if (k === "t") timestamp = Number(v);
    else if (k === "v1") v1 = v;
  }
  if (timestamp === null || v1 === null) return false;
  if (!Number.isFinite(timestamp)) return false;
  if (Math.abs(now - timestamp) > tolerance) return false;
  const expected = createHmac("sha256", args.secret)
    .update(`${timestamp}.${args.body}`)
    .digest("hex");
  // Both sides must be the same length; if not, timingSafeEqual throws.
  if (expected.length !== v1.length) return false;
  return timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(v1, "hex"));
}
