-- GENERATED by wrap-batch.mjs — batch batch-001 — 24 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- treasury :: suverse-treasury-avg-rates ($0.005)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-treasury-avg-rates', 'suverse-treasury-avg-rates', 'https://proxy.suverse.io/v1/data/suverse-treasury-avg-rates', 'POST',
    'US Treasury Average Interest Rates', 'Average interest rates paid on US Treasury securities including bills, notes, bonds, TIPS, and Floating Rate Notes from the official Treasury FiscalData service, most recent records first. Returns security type, security description, average interest rate, and record date. Critical for AI agents tracking the cost of federal debt, rate trends, and macro yield analysis.', 'Average interest rates on US Treasury securities (bills, notes, bonds, TIPS, FRNs) from official Treasury FiscalData, latest first: security type, rate, and record date. For AI agents tracking federal debt cost, yields, and macro rate trends.', 5000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_treasury_avg_rates'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'US Treasury Average Interest Rates', 'Average interest rates paid on US Treasury securities including bills, notes, bonds, TIPS, and Floating Rate Notes from the official Treasury FiscalData service, most recent records first. Returns security type, security description, average interest rate, and record date. Critical for AI agents tracking the cost of federal debt, rate trends, and macro yield analysis.', 'https://proxy.suverse.io/v1/data/suverse-treasury-avg-rates',
  ARRAY['treasury','yields','rates','bonds','macro'], 5000, 5000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-treasury-avg-rates', 'treasury',
  '{}', '{"source":"treasury.fiscaldata","data":{"data":[{"record_date":"2026-05-31","security_desc":"Treasury Notes","avg_interest_rate_amt":"3.012"}],"meta":{"count":16}}}', 'Average interest rates on US Treasury securities (bills, notes, bonds, TIPS, FRNs) from official Treasury FiscalData, latest first: security type, rate, and record date. For AI agents tracking federal debt cost, yields, and macro rate trends.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- treasury :: suverse-treasury-debt-to-penny ($0.005)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-treasury-debt-to-penny', 'suverse-treasury-debt-to-penny', 'https://proxy.suverse.io/v1/data/suverse-treasury-debt-to-penny', 'POST',
    'US National Debt To The Penny', 'The total US public debt outstanding to the penny from the official Treasury FiscalData service, most recent record first. Returns total public debt outstanding, debt held by the public, intragovernmental holdings, and record date. Critical for AI agents tracking the federal debt ceiling, fiscal trajectory, and macro risk signals tied to government borrowing.', 'Total US public debt outstanding to the penny from official Treasury FiscalData, latest record: total debt, debt held by public, intragovernmental holdings, record date. For AI agents tracking the debt ceiling, fiscal trajectory, and macro risk.', 5000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_treasury_debt_to_penny'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'US National Debt To The Penny', 'The total US public debt outstanding to the penny from the official Treasury FiscalData service, most recent record first. Returns total public debt outstanding, debt held by the public, intragovernmental holdings, and record date. Critical for AI agents tracking the federal debt ceiling, fiscal trajectory, and macro risk signals tied to government borrowing.', 'https://proxy.suverse.io/v1/data/suverse-treasury-debt-to-penny',
  ARRAY['treasury','national-debt','fiscal','macro','government'], 5000, 5000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-treasury-debt-to-penny', 'treasury',
  '{}', '{"source":"treasury.fiscaldata","data":{"data":[{"record_date":"2026-06-17","tot_pub_debt_out_amt":"37210000000000.00","debt_held_public_amt":"29000000000000.00"}]}}', 'Total US public debt outstanding to the penny from official Treasury FiscalData, latest record: total debt, debt held by public, intragovernmental holdings, record date. For AI agents tracking the debt ceiling, fiscal trajectory, and macro risk.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- treasury :: suverse-treasury-exchange-rates ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-treasury-exchange-rates', 'suverse-treasury-exchange-rates', 'https://proxy.suverse.io/v1/data/suverse-treasury-exchange-rates', 'POST',
    'US Treasury Reporting Rates Of Exchange', 'Official US Treasury quarterly reporting rates of exchange used by federal agencies to convert foreign currency balances to US dollars, filtered by country. Returns country, currency, exchange rate, and effective date. Useful for AI agents performing government grade currency conversion, cross border accounting, and treasury compliant FX reference lookups.', 'Official US Treasury quarterly reporting rates of exchange by country: currency, exchange rate, effective date. For AI agents doing government grade FX conversion, cross border accounting, and treasury compliant currency reference lookups.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_treasury_exchange_rates'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'US Treasury Reporting Rates Of Exchange', 'Official US Treasury quarterly reporting rates of exchange used by federal agencies to convert foreign currency balances to US dollars, filtered by country. Returns country, currency, exchange rate, and effective date. Useful for AI agents performing government grade currency conversion, cross border accounting, and treasury compliant FX reference lookups.', 'https://proxy.suverse.io/v1/data/suverse-treasury-exchange-rates',
  ARRAY['treasury','forex','exchange-rates','government','fx'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-treasury-exchange-rates', 'treasury',
  '{}', '{"source":"treasury.fiscaldata","data":{"data":[{"country":"Canada","currency":"Dollar","exchange_rate":"1.36","effective_date":"2026-03-31"}]}}', 'Official US Treasury quarterly reporting rates of exchange by country: currency, exchange rate, effective date. For AI agents doing government grade FX conversion, cross border accounting, and treasury compliant currency reference lookups.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- macro :: suverse-macro-indicator ($0.005)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-macro-indicator', 'suverse-macro-indicator', 'https://proxy.suverse.io/v1/data/suverse-macro-indicator', 'POST',
    'World Bank Macro Indicator Time Series', 'Any World Bank macroeconomic indicator time series for any country by ISO code and indicator code, such as GDP, inflation, population, or trade. Returns yearly values with indicator name, country, year, and value from the World Bank Open Data service. Critical for AI agents performing country macro analysis, sovereign risk scoring, and cross country economic comparison.', 'Any World Bank macroeconomic indicator time series for any country by ISO code and indicator code (GDP, inflation, population, trade): yearly values with name, country, year, value. For AI agents doing macro analysis, sovereign risk, and country comparison.', 5000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_macro_indicator'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'World Bank Macro Indicator Time Series', 'Any World Bank macroeconomic indicator time series for any country by ISO code and indicator code, such as GDP, inflation, population, or trade. Returns yearly values with indicator name, country, year, and value from the World Bank Open Data service. Critical for AI agents performing country macro analysis, sovereign risk scoring, and cross country economic comparison.', 'https://proxy.suverse.io/v1/data/suverse-macro-indicator',
  ARRAY['macro','worldbank','economic-indicators','gdp','inflation'], 5000, 5000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-macro-indicator', 'macro',
  '{"country":"US","indicator":"NY.GDP.MKTP.CD"}', '{"source":"worldbank","data":[{"page":1,"pages":1},[{"country":{"value":"United States"},"date":"2024","value":29200000000000}]]}', 'Any World Bank macroeconomic indicator time series for any country by ISO code and indicator code (GDP, inflation, population, trade): yearly values with name, country, year, value. For AI agents doing macro analysis, sovereign risk, and country comparison.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- macro :: suverse-macro-gdp ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-macro-gdp', 'suverse-macro-gdp', 'https://proxy.suverse.io/v1/data/suverse-macro-gdp', 'POST',
    'Country GDP Time Series', 'Gross Domestic Product in current US dollars for any country by ISO code as a yearly time series from World Bank Open Data. Returns country name, year, and GDP value for trend and growth analysis. Critical for AI agents sizing economies, computing growth rates, building macro dashboards, and comparing national output across countries and years.', 'Gross Domestic Product in current US dollars for any country by ISO code as a yearly time series from World Bank: country, year, GDP value. For AI agents sizing economies, computing growth, building macro dashboards, and comparing national output.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_macro_gdp'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Country GDP Time Series', 'Gross Domestic Product in current US dollars for any country by ISO code as a yearly time series from World Bank Open Data. Returns country name, year, and GDP value for trend and growth analysis. Critical for AI agents sizing economies, computing growth rates, building macro dashboards, and comparing national output across countries and years.', 'https://proxy.suverse.io/v1/data/suverse-macro-gdp',
  ARRAY['macro','gdp','worldbank','economy','growth'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-macro-gdp', 'macro',
  '{"country":"US"}', '{"source":"worldbank","data":[{"page":1},[{"country":{"value":"United States"},"date":"2024","value":29200000000000}]]}', 'Gross Domestic Product in current US dollars for any country by ISO code as a yearly time series from World Bank: country, year, GDP value. For AI agents sizing economies, computing growth, building macro dashboards, and comparing national output.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- macro :: suverse-macro-cpi-inflation ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-macro-cpi-inflation', 'suverse-macro-cpi-inflation', 'https://proxy.suverse.io/v1/data/suverse-macro-cpi-inflation', 'POST',
    'Country CPI Inflation Time Series', 'Annual consumer price inflation as a percentage for any country by ISO code as a yearly time series from World Bank Open Data. Returns country name, year, and inflation rate for macro and monetary analysis. Critical for AI agents tracking inflation regimes, real return adjustments, central bank policy context, and cross country price stability comparison.', 'Annual consumer price inflation percent for any country by ISO code as a yearly time series from World Bank: country, year, inflation rate. For AI agents tracking inflation regimes, real returns, monetary policy context, and price stability comparison.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_macro_cpi_inflation'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Country CPI Inflation Time Series', 'Annual consumer price inflation as a percentage for any country by ISO code as a yearly time series from World Bank Open Data. Returns country name, year, and inflation rate for macro and monetary analysis. Critical for AI agents tracking inflation regimes, real return adjustments, central bank policy context, and cross country price stability comparison.', 'https://proxy.suverse.io/v1/data/suverse-macro-cpi-inflation',
  ARRAY['macro','inflation','cpi','worldbank','monetary'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-macro-cpi-inflation', 'macro',
  '{"country":"US"}', '{"source":"worldbank","data":[{"page":1},[{"country":{"value":"United States"},"date":"2024","value":2.9}]]}', 'Annual consumer price inflation percent for any country by ISO code as a yearly time series from World Bank: country, year, inflation rate. For AI agents tracking inflation regimes, real returns, monetary policy context, and price stability comparison.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- macro :: suverse-macro-unemployment ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-macro-unemployment', 'suverse-macro-unemployment', 'https://proxy.suverse.io/v1/data/suverse-macro-unemployment', 'POST',
    'Country Unemployment Rate Time Series', 'Total unemployment as a percentage of the labor force for any country by ISO code as a yearly time series from World Bank Open Data modeled ILO estimates. Returns country name, year, and unemployment rate. Critical for AI agents assessing labor market health, recession signals, macro regime context, and cross country employment comparison.', 'Total unemployment percent of labor force for any country by ISO code as a yearly time series from World Bank ILO estimates: country, year, rate. For AI agents assessing labor health, recession signals, macro regime, and employment comparison.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_macro_unemployment'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Country Unemployment Rate Time Series', 'Total unemployment as a percentage of the labor force for any country by ISO code as a yearly time series from World Bank Open Data modeled ILO estimates. Returns country name, year, and unemployment rate. Critical for AI agents assessing labor market health, recession signals, macro regime context, and cross country employment comparison.', 'https://proxy.suverse.io/v1/data/suverse-macro-unemployment',
  ARRAY['macro','unemployment','labor','worldbank','jobs'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-macro-unemployment', 'macro',
  '{"country":"US"}', '{"source":"worldbank","data":[{"page":1},[{"country":{"value":"United States"},"date":"2024","value":4.1}]]}', 'Total unemployment percent of labor force for any country by ISO code as a yearly time series from World Bank ILO estimates: country, year, rate. For AI agents assessing labor health, recession signals, macro regime, and employment comparison.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sec-filings :: suverse-sec-company-concept ($0.008)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sec-company-concept', 'suverse-sec-company-concept', 'https://proxy.suverse.io/v1/data/suverse-sec-company-concept', 'POST',
    'SEC EDGAR Company XBRL Concept', 'Full reported history of one XBRL financial concept for a US public company by SEC CIK number, such as Revenues or Assets, from SEC EDGAR company concept data. Returns every period, value, unit, form, and filing for that concept. Critical for AI agents extracting structured fundamentals, building financial models, and tracking a single line item across filings.', 'Full reported history of one XBRL financial concept (Revenues, Assets, NetIncomeLoss) for a US public company by SEC CIK from SEC EDGAR: every period, value, unit, form, filing. For AI agents extracting structured fundamentals and building models.', 8000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sec_company_concept'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'SEC EDGAR Company XBRL Concept', 'Full reported history of one XBRL financial concept for a US public company by SEC CIK number, such as Revenues or Assets, from SEC EDGAR company concept data. Returns every period, value, unit, form, and filing for that concept. Critical for AI agents extracting structured fundamentals, building financial models, and tracking a single line item across filings.', 'https://proxy.suverse.io/v1/data/suverse-sec-company-concept',
  ARRAY['sec','edgar','xbrl','fundamentals','stocks'], 8000, 8000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sec-company-concept', 'sec-filings',
  '{"cik":"320193","tag":"Revenues"}', '{"source":"sec.edgar","data":{"cik":320193,"taxonomy":"us-gaap","tag":"Revenues","units":{"USD":[{"fy":2025,"fp":"FY","form":"10-K","val":416000000000}]}}}', 'Full reported history of one XBRL financial concept (Revenues, Assets, NetIncomeLoss) for a US public company by SEC CIK from SEC EDGAR: every period, value, unit, form, filing. For AI agents extracting structured fundamentals and building models.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sec-filings :: suverse-sec-company-facts ($0.009)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sec-company-facts', 'suverse-sec-company-facts', 'https://proxy.suverse.io/v1/data/suverse-sec-company-facts', 'POST',
    'SEC EDGAR Company Facts Bundle', 'All XBRL company facts for a US public company by SEC CIK number in one call from SEC EDGAR, covering every reported financial concept across all filings. Returns the entity name and the full us-gaap and dei fact set with periods and values. Critical for AI agents pulling a complete fundamentals snapshot, screening, or seeding a financial knowledge base.', 'All XBRL company facts for a US public company by SEC CIK in one call from SEC EDGAR: entity name plus the full us-gaap and dei fact set with periods and values. For AI agents pulling complete fundamentals, screening, or seeding a knowledge base.', 9000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sec_company_facts'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'SEC EDGAR Company Facts Bundle', 'All XBRL company facts for a US public company by SEC CIK number in one call from SEC EDGAR, covering every reported financial concept across all filings. Returns the entity name and the full us-gaap and dei fact set with periods and values. Critical for AI agents pulling a complete fundamentals snapshot, screening, or seeding a financial knowledge base.', 'https://proxy.suverse.io/v1/data/suverse-sec-company-facts',
  ARRAY['sec','edgar','xbrl','fundamentals','financials'], 9000, 9000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sec-company-facts', 'sec-filings',
  '{"cik":"320193"}', '{"source":"sec.edgar","data":{"cik":320193,"entityName":"Apple Inc.","facts":{"us-gaap":{"Assets":{"units":{"USD":[{"fy":2025,"val":365000000000}]}}}}}}', 'All XBRL company facts for a US public company by SEC CIK in one call from SEC EDGAR: entity name plus the full us-gaap and dei fact set with periods and values. For AI agents pulling complete fundamentals, screening, or seeding a knowledge base.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sec-filings :: suverse-sec-submissions ($0.007)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sec-submissions', 'suverse-sec-submissions', 'https://proxy.suverse.io/v1/data/suverse-sec-submissions', 'POST',
    'SEC EDGAR Company Submissions', 'Recent SEC EDGAR submission history for a US public company by CIK number, including 10-K, 10-Q, 8-K, and other forms with accession numbers and dates. Returns entity profile fields plus the recent filings index of form types, filing dates, and document references. Critical for AI agents monitoring corporate disclosures, material events, and filing cadence.', 'Recent SEC EDGAR submission history for a US public company by CIK: 10-K, 10-Q, 8-K and other forms with accession numbers and dates, plus entity profile. For AI agents monitoring corporate disclosures, material events, and filing cadence.', 7000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sec_submissions'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'SEC EDGAR Company Submissions', 'Recent SEC EDGAR submission history for a US public company by CIK number, including 10-K, 10-Q, 8-K, and other forms with accession numbers and dates. Returns entity profile fields plus the recent filings index of form types, filing dates, and document references. Critical for AI agents monitoring corporate disclosures, material events, and filing cadence.', 'https://proxy.suverse.io/v1/data/suverse-sec-submissions',
  ARRAY['sec','edgar','filings','disclosures','stocks'], 7000, 7000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sec-submissions', 'sec-filings',
  '{"cik":"320193"}', '{"source":"sec.edgar","data":{"cik":"320193","name":"Apple Inc.","tickers":["AAPL"],"filings":{"recent":{"form":["10-Q","8-K"],"filingDate":["2026-05-02","2026-04-30"]}}}}', 'Recent SEC EDGAR submission history for a US public company by CIK: 10-K, 10-Q, 8-K and other forms with accession numbers and dates, plus entity profile. For AI agents monitoring corporate disclosures, material events, and filing cadence.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-weather-current ($0.003)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-weather-current', 'suverse-weather-current', 'https://proxy.suverse.io/v1/data/suverse-weather-current', 'POST',
    'Current Weather Conditions', 'Current weather conditions for any latitude and longitude from the Open-Meteo forecast service, no key required. Returns temperature, wind speed, wind direction, and weather code for the requested point. Critical for AI agents that condition decisions on real time weather, such as logistics, travel, energy demand, agriculture, and outdoor event planning.', 'Current weather conditions for any latitude and longitude from Open-Meteo: temperature, wind speed, wind direction, weather code. For AI agents conditioning on real time weather, such as logistics, travel, energy demand, agriculture, and event planning.', 3000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_weather_current'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Current Weather Conditions', 'Current weather conditions for any latitude and longitude from the Open-Meteo forecast service, no key required. Returns temperature, wind speed, wind direction, and weather code for the requested point. Critical for AI agents that condition decisions on real time weather, such as logistics, travel, energy demand, agriculture, and outdoor event planning.', 'https://proxy.suverse.io/v1/data/suverse-weather-current',
  ARRAY['weather','current','temperature','wind','meteorology'], 3000, 3000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-weather-current', 'weather',
  '{"latitude":40.71,"longitude":-74.01}', '{"source":"open-meteo","data":{"latitude":40.71,"longitude":-74.01,"current_weather":{"temperature":21.3,"windspeed":11.2,"winddirection":200,"weathercode":1}}}', 'Current weather conditions for any latitude and longitude from Open-Meteo: temperature, wind speed, wind direction, weather code. For AI agents conditioning on real time weather, such as logistics, travel, energy demand, agriculture, and event planning.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-weather-forecast ($0.003)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-weather-forecast', 'suverse-weather-forecast', 'https://proxy.suverse.io/v1/data/suverse-weather-forecast', 'POST',
    'Seven Day Weather Forecast', 'Seven day daily weather forecast for any latitude and longitude from the Open-Meteo forecast service, no key required. Returns daily maximum and minimum temperature and total precipitation per day in the local timezone. Critical for AI agents planning ahead on weather sensitive operations such as travel, agriculture, construction, retail demand, and energy load forecasting.', 'Seven day daily weather forecast for any latitude and longitude from Open-Meteo: daily max and min temperature and total precipitation per day in local time. For AI agents planning weather sensitive operations like travel, agriculture, retail, and energy load.', 3000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_weather_forecast'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Seven Day Weather Forecast', 'Seven day daily weather forecast for any latitude and longitude from the Open-Meteo forecast service, no key required. Returns daily maximum and minimum temperature and total precipitation per day in the local timezone. Critical for AI agents planning ahead on weather sensitive operations such as travel, agriculture, construction, retail demand, and energy load forecasting.', 'https://proxy.suverse.io/v1/data/suverse-weather-forecast',
  ARRAY['weather','forecast','temperature','precipitation','planning'], 3000, 3000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-weather-forecast', 'weather',
  '{"latitude":40.71,"longitude":-74.01}', '{"source":"open-meteo","data":{"daily":{"time":["2026-06-19"],"temperature_2m_max":[28.1],"temperature_2m_min":[19.4],"precipitation_sum":[0]}}}', 'Seven day daily weather forecast for any latitude and longitude from Open-Meteo: daily max and min temperature and total precipitation per day in local time. For AI agents planning weather sensitive operations like travel, agriculture, retail, and energy load.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-weather-historical ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-weather-historical', 'suverse-weather-historical', 'https://proxy.suverse.io/v1/data/suverse-weather-historical', 'POST',
    'Historical Daily Weather', 'Historical daily weather for any latitude and longitude over a date range from the Open-Meteo archive service, no key required. Returns daily maximum and minimum temperature and precipitation for each day in the requested window. Critical for AI agents backtesting weather sensitive strategies, building climatology baselines, and reconciling past events with conditions.', 'Historical daily weather for any latitude and longitude over a date range from the Open-Meteo archive: daily max and min temperature and precipitation per day. For AI agents backtesting weather strategies, building climatology baselines, and event reconciliation.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_weather_historical'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Historical Daily Weather', 'Historical daily weather for any latitude and longitude over a date range from the Open-Meteo archive service, no key required. Returns daily maximum and minimum temperature and precipitation for each day in the requested window. Critical for AI agents backtesting weather sensitive strategies, building climatology baselines, and reconciling past events with conditions.', 'https://proxy.suverse.io/v1/data/suverse-weather-historical',
  ARRAY['weather','historical','climate','archive','backtest'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-weather-historical', 'weather',
  '{"latitude":40.71,"longitude":-74.01,"start_date":"2025-01-01","end_date":"2025-01-31"}', '{"source":"open-meteo","data":{"daily":{"time":["2025-01-01"],"temperature_2m_max":[3.2],"temperature_2m_min":[-2.1],"precipitation_sum":[1.4]}}}', 'Historical daily weather for any latitude and longitude over a date range from the Open-Meteo archive: daily max and min temperature and precipitation per day. For AI agents backtesting weather strategies, building climatology baselines, and event reconciliation.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-air-quality ($0.003)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-air-quality', 'suverse-air-quality', 'https://proxy.suverse.io/v1/data/suverse-air-quality', 'POST',
    'Air Quality Pollutant Levels', 'Hourly air quality for any latitude and longitude from the Open-Meteo air quality service, no key required. Returns particulate matter PM10 and PM2.5 plus carbon monoxide, ozone, and nitrogen dioxide concentrations. Critical for AI agents in health, environmental, logistics, and insurance contexts that need pollutant exposure data without paying for a commercial air quality provider.', 'Hourly air quality for any latitude and longitude from Open-Meteo: PM10, PM2.5, carbon monoxide, ozone, nitrogen dioxide concentrations. For AI agents in health, environmental, logistics, and insurance contexts needing pollutant exposure data.', 3000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_air_quality'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Air Quality Pollutant Levels', 'Hourly air quality for any latitude and longitude from the Open-Meteo air quality service, no key required. Returns particulate matter PM10 and PM2.5 plus carbon monoxide, ozone, and nitrogen dioxide concentrations. Critical for AI agents in health, environmental, logistics, and insurance contexts that need pollutant exposure data without paying for a commercial air quality provider.', 'https://proxy.suverse.io/v1/data/suverse-air-quality',
  ARRAY['air-quality','pollution','pm25','environment','health'], 3000, 3000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-air-quality', 'weather',
  '{"latitude":40.71,"longitude":-74.01}', '{"source":"open-meteo","data":{"hourly":{"time":["2026-06-19T00:00"],"pm2_5":[8.1],"pm10":[14.2],"ozone":[62]}}}', 'Hourly air quality for any latitude and longitude from Open-Meteo: PM10, PM2.5, carbon monoxide, ozone, nitrogen dioxide concentrations. For AI agents in health, environmental, logistics, and insurance contexts needing pollutant exposure data.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-marine-forecast ($0.003)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-marine-forecast', 'suverse-marine-forecast', 'https://proxy.suverse.io/v1/data/suverse-marine-forecast', 'POST',
    'Marine Wave Forecast', 'Hourly marine wave forecast for any coastal latitude and longitude from the Open-Meteo marine service, no key required. Returns wave height, wave direction, and wave period for the requested point. Critical for AI agents in shipping, maritime logistics, offshore energy, fishing, and coastal risk that need sea state data without a commercial marine weather subscription.', 'Hourly marine wave forecast for any coastal latitude and longitude from Open-Meteo: wave height, direction, and period. For AI agents in shipping, maritime logistics, offshore energy, fishing, and coastal risk needing sea state data.', 3000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_marine_forecast'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Marine Wave Forecast', 'Hourly marine wave forecast for any coastal latitude and longitude from the Open-Meteo marine service, no key required. Returns wave height, wave direction, and wave period for the requested point. Critical for AI agents in shipping, maritime logistics, offshore energy, fishing, and coastal risk that need sea state data without a commercial marine weather subscription.', 'https://proxy.suverse.io/v1/data/suverse-marine-forecast',
  ARRAY['marine','waves','maritime','shipping','ocean'], 3000, 3000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-marine-forecast', 'weather',
  '{"latitude":40.5,"longitude":-69.5}', '{"source":"open-meteo","data":{"hourly":{"time":["2026-06-19T00:00"],"wave_height":[1.2],"wave_period":[7.1],"wave_direction":[180]}}}', 'Hourly marine wave forecast for any coastal latitude and longitude from Open-Meteo: wave height, direction, and period. For AI agents in shipping, maritime logistics, offshore energy, fishing, and coastal risk needing sea state data.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- weather :: suverse-weather-alerts ($0.003)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-weather-alerts', 'suverse-weather-alerts', 'https://proxy.suverse.io/v1/data/suverse-weather-alerts', 'POST',
    'US Active Weather Alerts', 'Active US National Weather Service alerts for a state, including warnings, watches, and advisories for severe storms, floods, heat, and winter weather. Returns each alert event, severity, urgency, area description, and effective and expiry times. Critical for AI agents in logistics, insurance, travel, and safety that must react to official hazard alerts in real time.', 'Active US National Weather Service alerts for a state: warnings, watches, advisories for storms, floods, heat, winter weather, with event, severity, urgency, area, and timing. For AI agents in logistics, insurance, travel, and safety reacting to hazards.', 3000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_weather_alerts'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'US Active Weather Alerts', 'Active US National Weather Service alerts for a state, including warnings, watches, and advisories for severe storms, floods, heat, and winter weather. Returns each alert event, severity, urgency, area description, and effective and expiry times. Critical for AI agents in logistics, insurance, travel, and safety that must react to official hazard alerts in real time.', 'https://proxy.suverse.io/v1/data/suverse-weather-alerts',
  ARRAY['weather','alerts','nws','hazards','safety'], 3000, 3000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-weather-alerts', 'weather',
  '{"area":"CA"}', '{"source":"nws.weather.gov","data":{"features":[{"properties":{"event":"Heat Advisory","severity":"Moderate","areaDesc":"Los Angeles County","expires":"2026-06-20T03:00:00-07:00"}}]}}', 'Active US National Weather Service alerts for a state: warnings, watches, advisories for storms, floods, heat, winter weather, with event, severity, urgency, area, and timing. For AI agents in logistics, insurance, travel, and safety reacting to hazards.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- cybersecurity :: suverse-cve-lookup ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-cve-lookup', 'suverse-cve-lookup', 'https://proxy.suverse.io/v1/data/suverse-cve-lookup', 'POST',
    'CVE Vulnerability Lookup', 'Full detail for a single CVE vulnerability by identifier from the NIST National Vulnerability Database. Returns the description, CVSS severity scores and vector, affected configurations, references, and published and modified dates. Critical for AI agents in security operations triaging vulnerabilities, enriching alerts, prioritizing patching, and answering is this CVE exploitable questions.', 'Full detail for a single CVE by identifier from the NIST National Vulnerability Database: description, CVSS scores and vector, affected configs, references, dates. For AI security agents triaging vulnerabilities, enriching alerts, and prioritizing patching.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_cve_lookup'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'CVE Vulnerability Lookup', 'Full detail for a single CVE vulnerability by identifier from the NIST National Vulnerability Database. Returns the description, CVSS severity scores and vector, affected configurations, references, and published and modified dates. Critical for AI agents in security operations triaging vulnerabilities, enriching alerts, prioritizing patching, and answering is this CVE exploitable questions.', 'https://proxy.suverse.io/v1/data/suverse-cve-lookup',
  ARRAY['cybersecurity','cve','vulnerability','nvd','cvss'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-cve-lookup', 'cybersecurity',
  '{"cve_id":"CVE-2021-44228"}', '{"source":"nvd.nist","data":{"totalResults":1,"vulnerabilities":[{"cve":{"id":"CVE-2021-44228","metrics":{"cvssMetricV31":[{"cvssData":{"baseScore":10,"baseSeverity":"CRITICAL"}}]}}}]}}', 'Full detail for a single CVE by identifier from the NIST National Vulnerability Database: description, CVSS scores and vector, affected configs, references, dates. For AI security agents triaging vulnerabilities, enriching alerts, and prioritizing patching.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- cybersecurity :: suverse-cve-search ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-cve-search', 'suverse-cve-search', 'https://proxy.suverse.io/v1/data/suverse-cve-search', 'POST',
    'CVE Keyword Search', 'Search the NIST National Vulnerability Database for CVE vulnerabilities matching a keyword such as a product, vendor, or technology name. Returns up to twenty matching CVEs with identifiers, descriptions, and CVSS severity. Critical for AI agents doing security research, software bill of materials risk checks, vendor due diligence, and mapping a product name to known vulnerabilities.', 'Search the NIST National Vulnerability Database for CVEs matching a keyword (product, vendor, technology): up to twenty CVEs with ids, descriptions, CVSS severity. For AI agents doing security research, SBOM risk checks, and vendor due diligence.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_cve_search'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'CVE Keyword Search', 'Search the NIST National Vulnerability Database for CVE vulnerabilities matching a keyword such as a product, vendor, or technology name. Returns up to twenty matching CVEs with identifiers, descriptions, and CVSS severity. Critical for AI agents doing security research, software bill of materials risk checks, vendor due diligence, and mapping a product name to known vulnerabilities.', 'https://proxy.suverse.io/v1/data/suverse-cve-search',
  ARRAY['cybersecurity','cve','search','nvd','vulnerability'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-cve-search', 'cybersecurity',
  '{"keyword":"log4j"}', '{"source":"nvd.nist","data":{"totalResults":42,"vulnerabilities":[{"cve":{"id":"CVE-2021-44228"}}]}}', 'Search the NIST National Vulnerability Database for CVEs matching a keyword (product, vendor, technology): up to twenty CVEs with ids, descriptions, CVSS severity. For AI agents doing security research, SBOM risk checks, and vendor due diligence.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- cybersecurity :: suverse-cisa-kev ($0.004)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-cisa-kev', 'suverse-cisa-kev', 'https://proxy.suverse.io/v1/data/suverse-cisa-kev', 'POST',
    'CISA Known Exploited Vulnerabilities', 'The full CISA Known Exploited Vulnerabilities catalog, the authoritative US government list of CVEs confirmed exploited in the wild. Returns each catalog entry with CVE id, vendor, product, vulnerability name, date added, and required action due date. Critical for AI agents prioritizing patching by real world exploitation, feeding risk scoring, and enforcing the CISA remediation deadlines.', 'The full CISA Known Exploited Vulnerabilities catalog, the US government list of CVEs confirmed exploited in the wild: CVE id, vendor, product, name, date added, due date. For AI agents prioritizing patching by real exploitation and enforcing deadlines.', 4000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_cisa_kev'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'CISA Known Exploited Vulnerabilities', 'The full CISA Known Exploited Vulnerabilities catalog, the authoritative US government list of CVEs confirmed exploited in the wild. Returns each catalog entry with CVE id, vendor, product, vulnerability name, date added, and required action due date. Critical for AI agents prioritizing patching by real world exploitation, feeding risk scoring, and enforcing the CISA remediation deadlines.', 'https://proxy.suverse.io/v1/data/suverse-cisa-kev',
  ARRAY['cybersecurity','cisa','kev','exploited','patching'], 4000, 4000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-cisa-kev', 'cybersecurity',
  '{}', '{"source":"cisa.kev","data":{"count":1100,"vulnerabilities":[{"cveID":"CVE-2021-44228","vendorProject":"Apache","product":"Log4j","dueDate":"2021-12-24"}]}}', 'The full CISA Known Exploited Vulnerabilities catalog, the US government list of CVEs confirmed exploited in the wild: CVE id, vendor, product, name, date added, due date. For AI agents prioritizing patching by real exploitation and enforcing deadlines.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-sports-team ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sports-team', 'suverse-sports-team', 'https://proxy.suverse.io/v1/data/suverse-sports-team', 'POST',
    'Sports Team Profile Lookup', 'Profile lookup for any sports team by name across soccer, basketball, baseball, American football, and more from TheSportsDB. Returns team identifier, league, sport, formed year, stadium, country, and descriptive metadata. Useful for AI agents enriching sports queries, resolving team names to identifiers, and building sports knowledge for chat, fantasy, and analytics use cases.', 'Profile lookup for any sports team by name across soccer, basketball, baseball, American football and more from TheSportsDB: id, league, sport, formed year, stadium, country. For AI agents enriching sports queries and resolving team names to ids.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sports_team'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Sports Team Profile Lookup', 'Profile lookup for any sports team by name across soccer, basketball, baseball, American football, and more from TheSportsDB. Returns team identifier, league, sport, formed year, stadium, country, and descriptive metadata. Useful for AI agents enriching sports queries, resolving team names to identifiers, and building sports knowledge for chat, fantasy, and analytics use cases.', 'https://proxy.suverse.io/v1/data/suverse-sports-team',
  ARRAY['sports','teams','soccer','basketball','reference'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sports-team', 'sports',
  '{"team":"Arsenal"}', '{"source":"thesportsdb","data":{"teams":[{"idTeam":"133604","strTeam":"Arsenal","strLeague":"English Premier League","strStadium":"Emirates Stadium"}]}}', 'Profile lookup for any sports team by name across soccer, basketball, baseball, American football and more from TheSportsDB: id, league, sport, formed year, stadium, country. For AI agents enriching sports queries and resolving team names to ids.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-sports-league-table ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sports-league-table', 'suverse-sports-league-table', 'https://proxy.suverse.io/v1/data/suverse-sports-league-table', 'POST',
    'Sports League Standings Table', 'League standings table for a given league and season from TheSportsDB, covering major soccer and other team sport leagues. Returns each team with rank, played, win, draw, loss, goals for and against, goal difference, and points. Useful for AI agents answering standings questions, building sports dashboards, and powering fantasy and prediction features.', 'League standings table for a league and season from TheSportsDB: each team with rank, played, win, draw, loss, goals for and against, goal difference, points. For AI agents answering standings questions and powering sports dashboards and fantasy.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sports_league_table'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Sports League Standings Table', 'League standings table for a given league and season from TheSportsDB, covering major soccer and other team sport leagues. Returns each team with rank, played, win, draw, loss, goals for and against, goal difference, and points. Useful for AI agents answering standings questions, building sports dashboards, and powering fantasy and prediction features.', 'https://proxy.suverse.io/v1/data/suverse-sports-league-table',
  ARRAY['sports','standings','league-table','soccer','stats'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sports-league-table', 'sports',
  '{"league_id":"4328","season":"2025-2026"}', '{"source":"thesportsdb","data":{"table":[{"intRank":"1","strTeam":"Arsenal","intPoints":"75","intGoalDifference":"40"}]}}', 'League standings table for a league and season from TheSportsDB: each team with rank, played, win, draw, loss, goals for and against, goal difference, points. For AI agents answering standings questions and powering sports dashboards and fantasy.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-sports-events-day ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-sports-events-day', 'suverse-sports-events-day', 'https://proxy.suverse.io/v1/data/suverse-sports-events-day', 'POST',
    'Sports Events By Date', 'All sports events scheduled on a given date, optionally filtered by sport, from TheSportsDB. Returns each event with the two teams, league, sport, venue, scheduled time, and final score when available. Useful for AI agents building daily sports briefings, answering what games are on questions, and feeding schedule context into fantasy and betting research workflows.', 'All sports events on a given date, optionally filtered by sport, from TheSportsDB: teams, league, sport, venue, time, and final score when available. For AI agents building daily sports briefings and answering what games are on questions.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_sports_events_day'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Sports Events By Date', 'All sports events scheduled on a given date, optionally filtered by sport, from TheSportsDB. Returns each event with the two teams, league, sport, venue, scheduled time, and final score when available. Useful for AI agents building daily sports briefings, answering what games are on questions, and feeding schedule context into fantasy and betting research workflows.', 'https://proxy.suverse.io/v1/data/suverse-sports-events-day',
  ARRAY['sports','schedule','events','scores','fixtures'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-sports-events-day', 'sports',
  '{"date":"2026-06-19","sport":"Soccer"}', '{"source":"thesportsdb","data":{"events":[{"strEvent":"Arsenal vs Chelsea","strLeague":"English Premier League","dateEvent":"2026-06-19"}]}}', 'All sports events on a given date, optionally filtered by sport, from TheSportsDB: teams, league, sport, venue, time, and final score when available. For AI agents building daily sports briefings and answering what games are on questions.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-mlb-schedule ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-mlb-schedule', 'suverse-mlb-schedule', 'https://proxy.suverse.io/v1/data/suverse-mlb-schedule', 'POST',
    'MLB Game Schedule By Date', 'Official Major League Baseball game schedule for a given date from the MLB StatsAPI, no key required. Returns each game with the home and away teams, scheduled time, venue, game status, and score when the game is live or final. Useful for AI agents building baseball briefings, tracking live games, and feeding schedule and result context into fantasy and analytics workflows.', 'Official MLB game schedule for a given date from MLB StatsAPI: each game with home and away teams, time, venue, status, and score when live or final. For AI agents building baseball briefings, tracking live games, and feeding fantasy and analytics.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_mlb_schedule'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'MLB Game Schedule By Date', 'Official Major League Baseball game schedule for a given date from the MLB StatsAPI, no key required. Returns each game with the home and away teams, scheduled time, venue, game status, and score when the game is live or final. Useful for AI agents building baseball briefings, tracking live games, and feeding schedule and result context into fantasy and analytics workflows.', 'https://proxy.suverse.io/v1/data/suverse-mlb-schedule',
  ARRAY['sports','mlb','baseball','schedule','scores'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-mlb-schedule', 'sports',
  '{"date":"2026-06-19"}', '{"source":"mlb.statsapi","data":{"totalGames":15,"dates":[{"date":"2026-06-19","games":[{"teams":{"home":{"team":{"name":"New York Yankees"}},"away":{"team":{"name":"Boston Red Sox"}}}}]}]}}', 'Official MLB game schedule for a given date from MLB StatsAPI: each game with home and away teams, time, venue, status, and score when live or final. For AI agents building baseball briefings, tracking live games, and feeding fantasy and analytics.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-mlb-standings ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-mlb-standings', 'suverse-mlb-standings', 'https://proxy.suverse.io/v1/data/suverse-mlb-standings', 'POST',
    'MLB Standings By Season', 'Official Major League Baseball standings for a season from the MLB StatsAPI, no key required, covering the American and National leagues. Returns each team with wins, losses, winning percentage, games back, and division rank. Useful for AI agents answering standings and playoff race questions, building baseball dashboards, and powering fantasy and prediction features.', 'Official MLB standings for a season from MLB StatsAPI across the American and National leagues: each team with wins, losses, win percentage, games back, division rank. For AI agents answering playoff race questions and building baseball dashboards.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x260fbe1ec46968ee02e5b972507d7bb7f09f82b0', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_mlb_standings'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'MLB Standings By Season', 'Official Major League Baseball standings for a season from the MLB StatsAPI, no key required, covering the American and National leagues. Returns each team with wins, losses, winning percentage, games back, and division rank. Useful for AI agents answering standings and playoff race questions, building baseball dashboards, and powering fantasy and prediction features.', 'https://proxy.suverse.io/v1/data/suverse-mlb-standings',
  ARRAY['sports','mlb','baseball','standings','stats'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-mlb-standings', 'sports',
  '{"season":"2026"}', '{"source":"mlb.statsapi","data":{"records":[{"division":{"id":201},"teamRecords":[{"team":{"name":"New York Yankees"},"wins":50,"losses":28,"divisionRank":"1"}]}]}}', 'Official MLB standings for a season from MLB StatsAPI across the American and National leagues: each team with wins, losses, win percentage, games back, division rank. For AI agents answering playoff race questions and building baseball dashboards.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
