-- GENERATED by wrap-batch.mjs — batch batch-007 — 7 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- token-risk :: token-safety-eth ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'token-safety-eth', 'token-safety-eth', 'https://proxy.suverse.io/v1/data/token-safety-eth', 'POST',
    'Ethereum Token Safety Verdict', 'Security verdict for an Ethereum (mainnet) ERC-20 token from GoPlus: honeypot flag, buy/sell tax, open-source status, owner/mint/blacklist powers, LP holder concentration and trading-cannot-sell risks. One contract per call.', 'GoPlus security verdict for any Ethereum ERC-20: honeypot flag, buy/sell tax, is-open-source, owner/mint/pause/blacklist powers, LP holders, cannot-sell risk. Pass a contract address, get the full risk object.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'token_safety_eth'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Ethereum Token Safety Verdict', 'Security verdict for an Ethereum (mainnet) ERC-20 token from GoPlus: honeypot flag, buy/sell tax, open-source status, owner/mint/blacklist powers, LP holder concentration and trading-cannot-sell risks. One contract per call.', 'https://proxy.suverse.io/v1/data/token-safety-eth',
  ARRAY['token-risk','security','ethereum','erc20','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'token-safety-eth', 'token-risk',
  '{"contract_addresses":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"}', '{"result":{"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48":{"is_honeypot":"0","buy_tax":"0","sell_tax":"0","is_open_source":"1","is_proxy":"1","owner_address":"","cannot_sell_all":"0","holder_count":"2700000"}}}', 'GoPlus security verdict for any Ethereum ERC-20: honeypot flag, buy/sell tax, is-open-source, owner/mint/pause/blacklist powers, LP holders, cannot-sell risk. Pass a contract address, get the full risk object.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- token-risk :: token-safety-base ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'token-safety-base', 'token-safety-base', 'https://proxy.suverse.io/v1/data/token-safety-base', 'POST',
    'Base Token Safety Verdict', 'Security verdict for a Base (chain 8453) ERC-20 token from GoPlus: honeypot flag, buy/sell tax, open-source status, owner/mint/blacklist powers, LP holder concentration and cannot-sell risks. One contract per call. Fills the EVM gap next to our Solana token-check.', 'GoPlus security verdict for any Base ERC-20: honeypot flag, buy/sell tax, is-open-source, owner/mint/pause/blacklist powers, LP holders, cannot-sell risk. Pass a Base contract address, get the full risk object.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'token_safety_base'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Base Token Safety Verdict', 'Security verdict for a Base (chain 8453) ERC-20 token from GoPlus: honeypot flag, buy/sell tax, open-source status, owner/mint/blacklist powers, LP holder concentration and cannot-sell risks. One contract per call. Fills the EVM gap next to our Solana token-check.', 'https://proxy.suverse.io/v1/data/token-safety-base',
  ARRAY['token-risk','security','base','erc20','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'token-safety-base', 'token-risk',
  '{"contract_addresses":"0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"}', '{"result":{"0x833589fcd6edb6e08f4c7c32d4f71b54bda02913":{"is_honeypot":"0","buy_tax":"0","sell_tax":"0","is_open_source":"1","owner_address":"","cannot_sell_all":"0"}}}', 'GoPlus security verdict for any Base ERC-20: honeypot flag, buy/sell tax, is-open-source, owner/mint/pause/blacklist powers, LP holders, cannot-sell risk. Pass a Base contract address, get the full risk object.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- token-risk :: token-authority-solana ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'token-authority-solana', 'token-authority-solana', 'https://proxy.suverse.io/v1/data/token-authority-solana', 'POST',
    'Solana Token Authority & Risk Check', 'Solana SPL token risk check from GoPlus: mint authority, freeze authority, balance-mutable authority, transfer-hook and closable status, plus metadata-mutable flags. Surfaces the authority risks that matter most for SPL rug-safety. One mint per call.', 'GoPlus Solana SPL risk: mint authority, freeze authority, balance-mutable authority, transfer-hook, closable and metadata-mutable flags. Pass a mint address, get the authority/risk object.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'token_authority_solana'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Solana Token Authority & Risk Check', 'Solana SPL token risk check from GoPlus: mint authority, freeze authority, balance-mutable authority, transfer-hook and closable status, plus metadata-mutable flags. Surfaces the authority risks that matter most for SPL rug-safety. One mint per call.', 'https://proxy.suverse.io/v1/data/token-authority-solana',
  ARRAY['token-risk','security','solana','spl','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'token-authority-solana', 'token-risk',
  '{"contract_addresses":"So11111111111111111111111111111111111111112"}', '{"result":{"So11111111111111111111111111111111111111112":{"mintable":{"status":"0","authority":[]},"freezable":{"status":"0","authority":[]},"balance_mutable_authority":{"status":"0","authority":[]},"closable":{"status":"0","authority":[]}}}}', 'GoPlus Solana SPL risk: mint authority, freeze authority, balance-mutable authority, transfer-hook, closable and metadata-mutable flags. Pass a mint address, get the authority/risk object.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- token-risk :: token-quicklook ($0.020)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'token-quicklook', 'token-quicklook', 'https://proxy.suverse.io/v1/data/token-quicklook', 'POST',
    'Token Quicklook (Price, Liquidity, Volume)', 'Fast market snapshot for any token across Base, Ethereum, Solana and more via DexScreener: best trading pairs with price USD, FDV, market cap, 24h volume, liquidity and price-change windows. Pass a token contract/mint address.', 'DexScreener token snapshot across chains: top pairs with price USD, FDV, market cap, 24h volume, liquidity, and 5m/1h/6h/24h price change. Pass a token contract or Solana mint; multi-chain auto-detected.', 20000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'token_quicklook'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Token Quicklook (Price, Liquidity, Volume)', 'Fast market snapshot for any token across Base, Ethereum, Solana and more via DexScreener: best trading pairs with price USD, FDV, market cap, 24h volume, liquidity and price-change windows. Pass a token contract/mint address.', 'https://proxy.suverse.io/v1/data/token-quicklook',
  ARRAY['token-risk','dex','market-data','price','x402'], 20000, 20000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'token-quicklook', 'token-risk',
  '{"address":"0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"}', '{"schemaVersion":"1.0.0","pairs":[{"chainId":"base","dexId":"aerodrome","priceUsd":"1.00","fdv":0,"liquidity":{"usd":5000000},"volume":{"h24":1200000},"priceChange":{"h24":0.01}}]}', 'DexScreener token snapshot across chains: top pairs with price USD, FDV, market cap, 24h volume, liquidity, and 5m/1h/6h/24h price change. Pass a token contract or Solana mint; multi-chain auto-detected.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- wallet-analytics :: wallet-scam-check ($0.030)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'wallet-scam-check', 'wallet-scam-check', 'https://proxy.suverse.io/v1/data/wallet-scam-check', 'POST',
    'Wallet Scam & Sanction Check', 'Address risk screen from GoPlus for any EVM wallet: cybercrime, money-laundering, financial-crime, sanctioned, phishing, blackmail, stealing-attack, fake-KYC and malicious-contract-deployer flags. Pass an address (chain_id optional, default Ethereum).', 'GoPlus address risk screen for any EVM wallet: cybercrime, money-laundering, financial-crime, sanctioned, phishing, blackmail, stealing-attack and malicious-deployer flags. Pass an address; chain_id optional (default 1).', 30000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'wallet_scam_check'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Wallet Scam & Sanction Check', 'Address risk screen from GoPlus for any EVM wallet: cybercrime, money-laundering, financial-crime, sanctioned, phishing, blackmail, stealing-attack, fake-KYC and malicious-contract-deployer flags. Pass an address (chain_id optional, default Ethereum).', 'https://proxy.suverse.io/v1/data/wallet-scam-check',
  ARRAY['wallet-analytics','security','aml','evm','x402'], 30000, 30000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'wallet-scam-check', 'wallet-analytics',
  '{"address":"0x0000000000000000000000000000000000000000","chain_id":"1"}', '{"result":{"cybercrime":"0","money_laundering":"0","financial_crime":"0","sanctioned":"0","phishing_activities":"0","blacklist_doubt":"0","stealing_attack":"0","number_of_malicious_contracts_created":"0"}}', 'GoPlus address risk screen for any EVM wallet: cybercrime, money-laundering, financial-crime, sanctioned, phishing, blackmail, stealing-attack and malicious-deployer flags. Pass an address; chain_id optional (default 1).', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- dex-analytics :: dex-trending-pools ($0.010)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'dex-trending-pools', 'dex-trending-pools', 'https://proxy.suverse.io/v1/data/dex-trending-pools', 'POST',
    'Trending DEX Pools by Network', 'Currently trending liquidity pools on a given network (eth, base, solana, arbitrum, etc.) from GeckoTerminal: base/quote token, price USD, 24h volume, liquidity (reserve USD), price-change windows and transaction counts. Bounded top list.', 'GeckoTerminal trending DEX pools for a network (eth/base/solana/arbitrum...): base & quote token, price USD, 24h volume, reserve liquidity, price change and tx counts. Pass network; bounded top list.', 10000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'dex_trending_pools'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Trending DEX Pools by Network', 'Currently trending liquidity pools on a given network (eth, base, solana, arbitrum, etc.) from GeckoTerminal: base/quote token, price USD, 24h volume, liquidity (reserve USD), price-change windows and transaction counts. Bounded top list.', 'https://proxy.suverse.io/v1/data/dex-trending-pools',
  ARRAY['dex-analytics','dex','pools','trending','x402'], 10000, 10000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'dex-trending-pools', 'dex-analytics',
  '{"network":"eth","page":"1"}', '{"data":[{"id":"eth_0x...","type":"pool","attributes":{"name":"WETH / USDC","base_token_price_usd":"3500.0","reserve_in_usd":"12000000","volume_usd":{"h24":"8000000"}}}]}', 'GeckoTerminal trending DEX pools for a network (eth/base/solana/arbitrum...): base & quote token, price USD, 24h volume, reserve liquidity, price change and tx counts. Pass network; bounded top list.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- dex-analytics :: dex-new-pools ($0.010)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'dex-new-pools', 'dex-new-pools', 'https://proxy.suverse.io/v1/data/dex-new-pools', 'POST',
    'Newly Created DEX Pools by Network', 'Freshly created liquidity pools on a given network (eth, base, solana, etc.) from GeckoTerminal: base/quote token, pool address, price USD, initial liquidity (reserve USD) and creation time. Useful for new-listing and early-liquidity monitoring.', 'GeckoTerminal newest DEX pools for a network (eth/base/solana...): base & quote token, pool address, price USD, reserve liquidity and creation time. Pass network; bounded feed of fresh listings.', 10000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'dex_new_pools'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Newly Created DEX Pools by Network', 'Freshly created liquidity pools on a given network (eth, base, solana, etc.) from GeckoTerminal: base/quote token, pool address, price USD, initial liquidity (reserve USD) and creation time. Useful for new-listing and early-liquidity monitoring.', 'https://proxy.suverse.io/v1/data/dex-new-pools',
  ARRAY['dex-analytics','dex','pools','new-listings','x402'], 10000, 10000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'dex-new-pools', 'dex-analytics',
  '{"network":"base","page":"1"}', '{"data":[{"id":"base_0x...","type":"pool","attributes":{"name":"NEW / WETH","base_token_price_usd":"0.0003","reserve_in_usd":"45000","pool_created_at":"2026-06-21T00:00:00Z"}}]}', 'GeckoTerminal newest DEX pools for a network (eth/base/solana...): base & quote token, pool address, price USD, reserve liquidity and creation time. Pass network; bounded feed of fresh listings.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
