-- GENERATED by wrap-batch.mjs — batch batch-012 — 10 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- space-weather :: suverse-swpc-solar-flare-latest ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-solar-flare-latest', 'suverse-swpc-solar-flare-latest', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-flare-latest', 'POST',
    'Latest Solar Flare', 'The most recent solar flare detected by the GOES X-ray sensors, from NOAA''s Space Weather Prediction Center. Returns the flare class (A, B, C, M or X) with its peak X-ray flux, and the begin, peak and end times of the event. The fastest single call to answer whether the Sun has just flared and how strongly.', 'Most recent GOES solar flare from NOAA SWPC: flare class (A/B/C/M/X), peak X-ray flux, and begin, peak and end times. No parameters. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_solar_flare_latest'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Latest Solar Flare', 'The most recent solar flare detected by the GOES X-ray sensors, from NOAA''s Space Weather Prediction Center. Returns the flare class (A, B, C, M or X) with its peak X-ray flux, and the begin, peak and end times of the event. The fastest single call to answer whether the Sun has just flared and how strongly.', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-flare-latest',
  ARRAY['space-weather','solar','flare','noaa','swpc','goes','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-solar-flare-latest', 'space-weather',
  '{}', '[{"max_class":"C2.1","begin_time":"2026-07-27T22:14:00Z","max_time":"2026-07-27T22:31:00Z","max_xrlong":0.0000021}]', 'Most recent GOES solar flare from NOAA SWPC: flare class (A/B/C/M/X), peak X-ray flux, and begin, peak and end times. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-solar-flares-7day ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-solar-flares-7day', 'suverse-swpc-solar-flares-7day', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-flares-7day', 'POST',
    'Solar Flares, Last 7 Days', 'Every solar flare recorded by the GOES X-ray sensors over the past seven days from NOAA''s Space Weather Prediction Center, each with its class, peak flux and begin/peak/end timestamps. Use it to judge current solar activity levels and flare cadence rather than a single point-in-time reading.', 'All GOES solar flares from the last 7 days via NOAA SWPC, each with class, peak X-ray flux and begin, peak and end times. No parameters. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_solar_flares_7day'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Solar Flares, Last 7 Days', 'Every solar flare recorded by the GOES X-ray sensors over the past seven days from NOAA''s Space Weather Prediction Center, each with its class, peak flux and begin/peak/end timestamps. Use it to judge current solar activity levels and flare cadence rather than a single point-in-time reading.', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-flares-7day',
  ARRAY['space-weather','solar','flare','history','noaa','swpc','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-solar-flares-7day', 'space-weather',
  '{}', '[{"max_class":"M1.4","begin_time":"2026-07-24T09:02:00Z","max_time":"2026-07-24T09:18:00Z"}]', 'All GOES solar flares from the last 7 days via NOAA SWPC, each with class, peak X-ray flux and begin, peak and end times. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-kp-index ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-kp-index', 'suverse-swpc-kp-index', 'https://proxy.suverse.io/v1/data/suverse-swpc-kp-index', 'POST',
    'Planetary K-Index (Geomagnetic Activity)', 'The planetary K-index time series from NOAA SWPC, the standard 0-9 measure of global geomagnetic disturbance sampled every three hours. Kp of 5 or above is a geomagnetic storm. Use it to detect active storm conditions that affect HF radio, GPS accuracy, satellite drag and power-grid induced currents.', 'Planetary K-index series from NOAA SWPC: the 0-9 global geomagnetic activity measure at 3-hour cadence. Kp 5+ means a geomagnetic storm. No parameters. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_kp_index'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Planetary K-Index (Geomagnetic Activity)', 'The planetary K-index time series from NOAA SWPC, the standard 0-9 measure of global geomagnetic disturbance sampled every three hours. Kp of 5 or above is a geomagnetic storm. Use it to detect active storm conditions that affect HF radio, GPS accuracy, satellite drag and power-grid induced currents.', 'https://proxy.suverse.io/v1/data/suverse-swpc-kp-index',
  ARRAY['space-weather','geomagnetic','kp-index','storm','noaa','swpc','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-kp-index', 'space-weather',
  '{}', '[["time_tag","Kp","a_running","station_count"],["2026-07-27 21:00:00","3.00","12","8"]]', 'Planetary K-index series from NOAA SWPC: the 0-9 global geomagnetic activity measure at 3-hour cadence. Kp 5+ means a geomagnetic storm. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-solar-wind-speed ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-solar-wind-speed', 'suverse-swpc-solar-wind-speed', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-wind-speed', 'POST',
    'Real-Time Solar Wind Speed', 'Current solar wind bulk speed in km/s measured at the L1 Lagrange point by NOAA''s real-time solar wind monitors, with the observation timestamp. Elevated speed above roughly 500 km/s signals a high-speed stream or coronal-hole outflow and typically precedes geomagnetic disturbance at Earth by hours.', 'Current solar wind bulk speed in km/s at the L1 point from NOAA SWPC, with observation timestamp. Elevated speed precedes geomagnetic disturbance. No parameters. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_solar_wind_speed'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Real-Time Solar Wind Speed', 'Current solar wind bulk speed in km/s measured at the L1 Lagrange point by NOAA''s real-time solar wind monitors, with the observation timestamp. Elevated speed above roughly 500 km/s signals a high-speed stream or coronal-hole outflow and typically precedes geomagnetic disturbance at Earth by hours.', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-wind-speed',
  ARRAY['space-weather','solar-wind','l1','noaa','swpc','realtime','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-solar-wind-speed', 'space-weather',
  '{}', '{"TimeStamp":"2026-07-28 04:20:00","WindSpeed":"412.6"}', 'Current solar wind bulk speed in km/s at the L1 point from NOAA SWPC, with observation timestamp. Elevated speed precedes geomagnetic disturbance. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-solar-wind-mag ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-solar-wind-mag', 'suverse-swpc-solar-wind-mag', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-wind-mag', 'POST',
    'Interplanetary Magnetic Field (Bz/Bt)', 'Current interplanetary magnetic field readings at L1 from NOAA SWPC: total field strength Bt and the north-south component Bz in nanotesla, with timestamp. A strongly southward Bz is the single best short-term predictor of geomagnetic storming, because it couples solar wind energy into Earth''s magnetosphere.', 'Interplanetary magnetic field at L1 from NOAA SWPC: total field Bt and north-south Bz in nT with timestamp. Southward Bz is the key storm predictor. No parameters. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_solar_wind_mag'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Interplanetary Magnetic Field (Bz/Bt)', 'Current interplanetary magnetic field readings at L1 from NOAA SWPC: total field strength Bt and the north-south component Bz in nanotesla, with timestamp. A strongly southward Bz is the single best short-term predictor of geomagnetic storming, because it couples solar wind energy into Earth''s magnetosphere.', 'https://proxy.suverse.io/v1/data/suverse-swpc-solar-wind-mag',
  ARRAY['space-weather','imf','bz','magnetosphere','noaa','swpc','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-solar-wind-mag', 'space-weather',
  '{}', '{"TimeStamp":"2026-07-28 04:20:00","Bt":"5.1","Bz":"-2.4"}', 'Interplanetary magnetic field at L1 from NOAA SWPC: total field Bt and north-south Bz in nT with timestamp. Southward Bz is the key storm predictor. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-f107-flux ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-f107-flux', 'suverse-swpc-f107-flux', 'https://proxy.suverse.io/v1/data/suverse-swpc-f107-flux', 'POST',
    'F10.7 cm Solar Radio Flux', 'The current 10.7 cm solar radio flux value from NOAA SWPC, the standard proxy for solar activity and EUV output. F10.7 drives thermospheric density and therefore satellite drag, and is the primary input to ionospheric and orbital-decay models. Returned with its observation timestamp.', 'Current F10.7 cm solar radio flux from NOAA SWPC, the standard solar activity proxy driving satellite drag and ionospheric models, with timestamp. No parameters. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_f107_flux'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'F10.7 cm Solar Radio Flux', 'The current 10.7 cm solar radio flux value from NOAA SWPC, the standard proxy for solar activity and EUV output. F10.7 drives thermospheric density and therefore satellite drag, and is the primary input to ionospheric and orbital-decay models. Returned with its observation timestamp.', 'https://proxy.suverse.io/v1/data/suverse-swpc-f107-flux',
  ARRAY['space-weather','f107','solar-flux','satellite-drag','noaa','swpc','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-f107-flux', 'space-weather',
  '{}', '{"TimeStamp":"2026-07-28 04:00:00","Flux":"168"}', 'Current F10.7 cm solar radio flux from NOAA SWPC, the standard solar activity proxy driving satellite drag and ionospheric models, with timestamp. No parameters. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- space-weather :: suverse-swpc-space-weather-alerts ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-swpc-space-weather-alerts', 'suverse-swpc-space-weather-alerts', 'https://proxy.suverse.io/v1/data/suverse-swpc-space-weather-alerts', 'POST',
    'Space Weather Alerts, Watches and Warnings', 'The active NOAA SWPC alert stream: geomagnetic storm watches and warnings, radio blackout alerts and solar radiation storm notices, each with its issue time, serial number, NOAA scale and full advisory text. This is the official operational feed used to decide whether space weather is actionable right now.', 'Official NOAA SWPC alerts, watches and warnings: geomagnetic storms, radio blackouts and radiation storms with issue time, NOAA scale and full advisory text. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_swpc_space_weather_alerts'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Space Weather Alerts, Watches and Warnings', 'The active NOAA SWPC alert stream: geomagnetic storm watches and warnings, radio blackout alerts and solar radiation storm notices, each with its issue time, serial number, NOAA scale and full advisory text. This is the official operational feed used to decide whether space weather is actionable right now.', 'https://proxy.suverse.io/v1/data/suverse-swpc-space-weather-alerts',
  ARRAY['space-weather','alerts','geomagnetic-storm','radio-blackout','noaa','swpc','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-swpc-space-weather-alerts', 'space-weather',
  '{}', '[{"product_id":"WATA20","issue_datetime":"2026-07-27 18:00:00","message":"Space Weather Message Code: WATA20"}]', 'Official NOAA SWPC alerts, watches and warnings: geomagnetic storms, radio blackouts and radiation storms with issue time, NOAA scale and full advisory text. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-fema-disaster-declarations ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-fema-disaster-declarations', 'suverse-fema-disaster-declarations', 'https://proxy.suverse.io/v1/data/suverse-fema-disaster-declarations', 'POST',
    'FEMA Disaster Declarations', 'Federally declared disasters from FEMA''s OpenFEMA dataset: declaration number and type, incident type (hurricane, flood, fire, severe storm), the declaring state and county, incident begin and end dates, and which assistance programs were authorised. Filter with an OData expression to scope by state, incident type or year.', 'US federal disaster declarations from OpenFEMA: declaration and incident type, state, county, incident dates and authorised assistance programs. OData filter supported. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_fema_disaster_declarations'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'FEMA Disaster Declarations', 'Federally declared disasters from FEMA''s OpenFEMA dataset: declaration number and type, incident type (hurricane, flood, fire, severe storm), the declaring state and county, incident begin and end dates, and which assistance programs were authorised. Filter with an OData expression to scope by state, incident type or year.', 'https://proxy.suverse.io/v1/data/suverse-fema-disaster-declarations',
  ARRAY['government','fema','disaster','emergency','hazard','open-data','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-fema-disaster-declarations', 'government',
  '{"filter":"state eq ''CA''","top":20}', '{"DisasterDeclarationsSummaries":[{"disasterNumber":4769,"state":"CA","incidentType":"Fire","declarationDate":"2026-03-11T00:00:00.000Z"}]}', 'US federal disaster declarations from OpenFEMA: declaration and incident type, state, county, incident dates and authorised assistance programs. OData filter supported. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-fema-nfip-claims ($0.150)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-fema-nfip-claims', 'suverse-fema-nfip-claims', 'https://proxy.suverse.io/v1/data/suverse-fema-nfip-claims', 'POST',
    'FEMA NFIP Flood Insurance Claims', 'Redacted National Flood Insurance Program claim records from FEMA''s OpenFEMA dataset: date of loss, state, county and ZIP, flood zone, occupancy type, year of construction and the amounts paid on building and contents claims. The concrete record of where flood losses actually get paid, for underwriting and property risk work.', 'FEMA NFIP flood insurance claims: date of loss, state, county, ZIP, flood zone, occupancy and amounts paid on building and contents. OData filter supported. Keyless.', 150000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_fema_nfip_claims'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'FEMA NFIP Flood Insurance Claims', 'Redacted National Flood Insurance Program claim records from FEMA''s OpenFEMA dataset: date of loss, state, county and ZIP, flood zone, occupancy type, year of construction and the amounts paid on building and contents claims. The concrete record of where flood losses actually get paid, for underwriting and property risk work.', 'https://proxy.suverse.io/v1/data/suverse-fema-nfip-claims',
  ARRAY['government','fema','flood','insurance','nfip','property-risk','x402'], 150000, 150000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-fema-nfip-claims', 'government',
  '{"filter":"state eq ''TX''","top":20}', '{"FimaNfipClaims":[{"state":"TX","dateOfLoss":"2025-07-04","floodZone":"AE","amountPaidOnBuildingClaim":41250}]}', 'FEMA NFIP flood insurance claims: date of loss, state, county, ZIP, flood zone, occupancy and amounts paid on building and contents. OData filter supported. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- hazard :: suverse-gdacs-disaster-events ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-gdacs-disaster-events', 'suverse-gdacs-disaster-events', 'https://proxy.suverse.io/v1/data/suverse-gdacs-disaster-events', 'POST',
    'Global Disaster Alerts', 'Current worldwide disaster events from GDACS, the joint UN and European Commission Global Disaster Alert and Coordination System. Returns earthquakes, tropical cyclones, floods, volcanic eruptions, droughts and wildfires as GeoJSON features with alert level (green, orange, red), severity, affected population estimate and event geometry.', 'Worldwide disaster events from GDACS (UN/EC): earthquakes, cyclones, floods, volcanoes, droughts and wildfires as GeoJSON with alert level, severity and population affected. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_gdacs_disaster_events'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Global Disaster Alerts', 'Current worldwide disaster events from GDACS, the joint UN and European Commission Global Disaster Alert and Coordination System. Returns earthquakes, tropical cyclones, floods, volcanic eruptions, droughts and wildfires as GeoJSON features with alert level (green, orange, red), severity, affected population estimate and event geometry.', 'https://proxy.suverse.io/v1/data/suverse-gdacs-disaster-events',
  ARRAY['hazard','disaster','gdacs','earthquake','cyclone','flood','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-gdacs-disaster-events', 'hazard',
  '{}', '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"eventtype":"TC","alertlevel":"Orange"}}]}', 'Worldwide disaster events from GDACS (UN/EC): earthquakes, cyclones, floods, volcanoes, droughts and wildfires as GeoJSON with alert level, severity and population affected. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
