-- GENERATED by wrap-batch.mjs — batch batch-e2e — 1 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- macro :: suverse-e2e-worldbank-population ($0.002)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-e2e-worldbank-population', 'suverse-e2e-worldbank-population', 'https://proxy.suverse.io/v1/data/suverse-e2e-worldbank-population', 'POST',
    'Country Population Time Series', 'Total population for any country by ISO code as a yearly time series from World Bank Open Data, no key. Returns country, year, and population. End to end pipeline auto indexing test endpoint for the wrap pipeline; also a genuinely useful macro series for AI agents sizing markets and demographics.', 'Total population for any country by ISO code as a yearly time series from World Bank Open Data, no key: country, year, population. For AI agents sizing markets and demographics. Pipeline auto-index verification endpoint.', 2000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0x2d50131399DDb89de63eEe353EeDa2c7AB97DFBA', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_e2e_worldbank_population'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Country Population Time Series', 'Total population for any country by ISO code as a yearly time series from World Bank Open Data, no key. Returns country, year, and population. End to end pipeline auto indexing test endpoint for the wrap pipeline; also a genuinely useful macro series for AI agents sizing markets and demographics.', 'https://proxy.suverse.io/v1/data/suverse-e2e-worldbank-population',
  ARRAY['macro','population','worldbank','demographics','economy'], 2000, 2000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-e2e-worldbank-population', 'macro',
  '{"country":"US"}', '{"source":"worldbank","data":[{"page":1},[{"country":{"value":"United States"},"date":"2024","value":335000000}]]}', 'Total population for any country by ISO code as a yearly time series from World Bank Open Data, no key: country, year, population. For AI agents sizing markets and demographics. Pipeline auto-index verification endpoint.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
