-- GENERATED by wrap-batch.mjs — batch batch-013 — 10 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- government :: suverse-usaspending-agencies ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-usaspending-agencies', 'suverse-usaspending-agencies', 'https://proxy.suverse.io/v1/data/suverse-usaspending-agencies', 'POST',
    'US Federal Top-Tier Agencies', 'The full roster of US federal top-tier agencies from USAspending.gov, the Treasury''s official federal spending portal. Each entry carries the agency name, abbreviation, toptier code, CGAC/agency identifiers and the current-year budget authority. This is the lookup table needed to address every other federal spending query by agency code.', 'All US federal top-tier agencies from USAspending.gov with name, abbreviation, toptier code and current-year budget authority. The agency-code lookup for federal spending queries. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_usaspending_agencies'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'US Federal Top-Tier Agencies', 'The full roster of US federal top-tier agencies from USAspending.gov, the Treasury''s official federal spending portal. Each entry carries the agency name, abbreviation, toptier code, CGAC/agency identifiers and the current-year budget authority. This is the lookup table needed to address every other federal spending query by agency code.', 'https://proxy.suverse.io/v1/data/suverse-usaspending-agencies',
  ARRAY['government','usaspending','federal','budget','agency','open-data','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-usaspending-agencies', 'government',
  '{}', '{"results":[{"agency_name":"Department of Defense","abbreviation":"DOD","toptier_code":"097"}]}', 'All US federal top-tier agencies from USAspending.gov with name, abbreviation, toptier code and current-year budget authority. The agency-code lookup for federal spending queries. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-usaspending-agency-budget ($0.150)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-usaspending-agency-budget', 'suverse-usaspending-agency-budget', 'https://proxy.suverse.io/v1/data/suverse-usaspending-agency-budget', 'POST',
    'Federal Agency Budgetary Resources', 'Budgetary resources and obligation totals for one US federal agency by its toptier code, from USAspending.gov. Returns total budgetary resources, obligated amounts and outlays broken out by fiscal year, so an agent can see how much an agency was given and how much it has actually spent. Pass the three-digit toptier agency code.', 'Budgetary resources for a US federal agency by toptier code from USAspending.gov: total resources, obligations and outlays by fiscal year. Keyless.', 150000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_usaspending_agency_budget'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Federal Agency Budgetary Resources', 'Budgetary resources and obligation totals for one US federal agency by its toptier code, from USAspending.gov. Returns total budgetary resources, obligated amounts and outlays broken out by fiscal year, so an agent can see how much an agency was given and how much it has actually spent. Pass the three-digit toptier agency code.', 'https://proxy.suverse.io/v1/data/suverse-usaspending-agency-budget',
  ARRAY['government','usaspending','budget','obligations','federal','fiscal','x402'], 150000, 150000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-usaspending-agency-budget', 'government',
  '{"code":"012"}', '{"toptier_code":"012","agency_data_by_year":[{"fiscal_year":2026,"total_budgetary_resources":285000000000}]}', 'Budgetary resources for a US federal agency by toptier code from USAspending.gov: total resources, obligations and outlays by fiscal year. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-ukpolice-forces ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ukpolice-forces', 'suverse-ukpolice-forces', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-forces', 'POST',
    'UK Police Forces', 'The complete list of territorial police forces in England, Wales and Northern Ireland from the Home Office open data service, each with its machine identifier and display name. The identifier returned here is what every other UK policing query is keyed on, including force detail and street-level crime lookups.', 'All UK police forces from the Home Office open data service with machine id and display name. The lookup for every other UK policing query. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ukpolice_forces'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'UK Police Forces', 'The complete list of territorial police forces in England, Wales and Northern Ireland from the Home Office open data service, each with its machine identifier and display name. The identifier returned here is what every other UK policing query is keyed on, including force detail and street-level crime lookups.', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-forces',
  ARRAY['government','police','uk','crime','open-data','law-enforcement','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ukpolice-forces', 'government',
  '{}', '[{"id":"metropolitan","name":"Metropolitan Police Service"}]', 'All UK police forces from the Home Office open data service with machine id and display name. The lookup for every other UK policing query. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-ukpolice-force-detail ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ukpolice-force-detail', 'suverse-ukpolice-force-detail', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-force-detail', 'POST',
    'UK Police Force Detail', 'Full profile for one UK police force from the Home Office open data service: display name, description, telephone contact and the force''s official website and social-media engagement channels. Pass the force identifier from the forces list, for example metropolitan, west-midlands or police-scotland.', 'Profile for one UK police force: name, description, telephone and official website plus engagement channels. Pass a force id such as metropolitan. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ukpolice_force_detail'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'UK Police Force Detail', 'Full profile for one UK police force from the Home Office open data service: display name, description, telephone contact and the force''s official website and social-media engagement channels. Pass the force identifier from the forces list, for example metropolitan, west-midlands or police-scotland.', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-force-detail',
  ARRAY['government','police','uk','force','open-data','law-enforcement','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ukpolice-force-detail', 'government',
  '{"force":"metropolitan"}', '{"id":"metropolitan","name":"Metropolitan Police Service","telephone":"101"}', 'Profile for one UK police force: name, description, telephone and official website plus engagement channels. Pass a force id such as metropolitan. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-ukpolice-crime-categories ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ukpolice-crime-categories', 'suverse-ukpolice-crime-categories', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-crime-categories', 'POST',
    'UK Crime Categories', 'The valid street-level crime categories for a given month from the UK Home Office open data service, such as burglary, violent-crime, vehicle-crime, anti-social-behaviour and drugs. Categories change over time, so the month matters. These are the exact category identifiers used to filter UK crime queries.', 'Valid UK street-level crime categories for a given month (burglary, violent-crime, drugs and more) from Home Office open data. Pass a YYYY-MM date. Keyless.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ukpolice_crime_categories'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'UK Crime Categories', 'The valid street-level crime categories for a given month from the UK Home Office open data service, such as burglary, violent-crime, vehicle-crime, anti-social-behaviour and drugs. Categories change over time, so the month matters. These are the exact category identifiers used to filter UK crime queries.', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-crime-categories',
  ARRAY['government','police','uk','crime','taxonomy','open-data','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ukpolice-crime-categories', 'government',
  '{"date":"2026-05"}', '[{"url":"burglary","name":"Burglary"},{"url":"drugs","name":"Drugs"}]', 'Valid UK street-level crime categories for a given month (burglary, violent-crime, drugs and more) from Home Office open data. Pass a YYYY-MM date. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- government :: suverse-ukpolice-crimes-at-location ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ukpolice-crimes-at-location', 'suverse-ukpolice-crimes-at-location', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-crimes-at-location', 'POST',
    'UK Crimes at a Location', 'Street-level crimes recorded at the police-defined location nearest a coordinate for a given month, from the UK Home Office open data service. Each record carries the crime category, month, approximate street, and the outcome status where one has been recorded. Scoped to the nearest reporting point so the response stays small.', 'UK street-level crimes at the reporting point nearest a lat/lng for a given month: category, street, month and outcome status. Home Office open data. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ukpolice_crimes_at_location'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'UK Crimes at a Location', 'Street-level crimes recorded at the police-defined location nearest a coordinate for a given month, from the UK Home Office open data service. Each record carries the crime category, month, approximate street, and the outcome status where one has been recorded. Scoped to the nearest reporting point so the response stays small.', 'https://proxy.suverse.io/v1/data/suverse-ukpolice-crimes-at-location',
  ARRAY['government','police','uk','crime','location','open-data','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ukpolice-crimes-at-location', 'government',
  '{"lat":"51.5074","lng":"-0.1278","date":"2026-05"}', '[{"category":"theft-from-the-person","month":"2026-05","location":{"street":{"name":"On or near Nightclub"}}}]', 'UK street-level crimes at the reporting point nearest a lat/lng for a given month: category, street, month and outcome status. Home Office open data. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- finance :: suverse-ecb-policy-rate ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ecb-policy-rate', 'suverse-ecb-policy-rate', 'https://proxy.suverse.io/v1/data/suverse-ecb-policy-rate', 'POST',
    'ECB Main Refinancing Rate', 'The European Central Bank''s main refinancing operations rate, the euro area''s headline policy interest rate, straight from the ECB Data Portal SDMX service. Returns the observation series with dates and levels so an agent can read the current rate and the recent path of ECB policy. Control history depth with lastNObservations.', 'ECB main refinancing operations rate, the euro area headline policy rate, from the ECB Data Portal with dates and levels. Control depth via lastNObservations. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ecb_policy_rate'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'ECB Main Refinancing Rate', 'The European Central Bank''s main refinancing operations rate, the euro area''s headline policy interest rate, straight from the ECB Data Portal SDMX service. Returns the observation series with dates and levels so an agent can read the current rate and the recent path of ECB policy. Control history depth with lastNObservations.', 'https://proxy.suverse.io/v1/data/suverse-ecb-policy-rate',
  ARRAY['finance','ecb','interest-rate','policy-rate','eurozone','macro','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ecb-policy-rate', 'finance',
  '{"lastNObservations":10}', '{"dataSets":[{"series":{}}],"structure":{}}', 'ECB main refinancing operations rate, the euro area headline policy rate, from the ECB Data Portal with dates and levels. Control depth via lastNObservations. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- finance :: suverse-ecb-yield-curve-10y ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-ecb-yield-curve-10y', 'suverse-ecb-yield-curve-10y', 'https://proxy.suverse.io/v1/data/suverse-ecb-yield-curve-10y', 'POST',
    'Euro Area 10-Year Government Yield Curve', 'The euro area AAA-rated government bond spot yield at the 10-year maturity from the ECB Data Portal''s official yield curve series. This is the reference long-term risk-free rate for the euro area, used to price duration, discount cash flows and read the market''s long-run growth and inflation expectations. Depth is controlled by lastNObservations.', 'Euro area AAA government bond 10-year spot yield from the ECB Data Portal official yield curve. The euro reference long-term risk-free rate. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_ecb_yield_curve_10y'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Euro Area 10-Year Government Yield Curve', 'The euro area AAA-rated government bond spot yield at the 10-year maturity from the ECB Data Portal''s official yield curve series. This is the reference long-term risk-free rate for the euro area, used to price duration, discount cash flows and read the market''s long-run growth and inflation expectations. Depth is controlled by lastNObservations.', 'https://proxy.suverse.io/v1/data/suverse-ecb-yield-curve-10y',
  ARRAY['finance','ecb','yield-curve','bonds','eurozone','rates','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-ecb-yield-curve-10y', 'finance',
  '{"lastNObservations":10}', '{"dataSets":[{"series":{}}],"structure":{}}', 'Euro area AAA government bond 10-year spot yield from the ECB Data Portal official yield curve. The euro reference long-term risk-free rate. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- finance :: suverse-cftc-commitments-of-traders ($0.200)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-cftc-commitments-of-traders', 'suverse-cftc-commitments-of-traders', 'https://proxy.suverse.io/v1/data/suverse-cftc-commitments-of-traders', 'POST',
    'CFTC Commitments of Traders', 'Positioning data from the US Commodity Futures Trading Commission''s Commitments of Traders report, the weekly breakdown of who is long and short in the futures markets by trader class - commercial hedgers, non-commercial speculators and non-reportable positions - with open interest. The standard dataset for reading speculative positioning in commodities, rates and FX futures.', 'CFTC Commitments of Traders: weekly futures positioning by trader class (commercial, non-commercial, non-reportable) with open interest. Filter with a Socrata where clause. Keyless.', 200000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_cftc_commitments_of_traders'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'CFTC Commitments of Traders', 'Positioning data from the US Commodity Futures Trading Commission''s Commitments of Traders report, the weekly breakdown of who is long and short in the futures markets by trader class - commercial hedgers, non-commercial speculators and non-reportable positions - with open interest. The standard dataset for reading speculative positioning in commodities, rates and FX futures.', 'https://proxy.suverse.io/v1/data/suverse-cftc-commitments-of-traders',
  ARRAY['finance','cftc','futures','positioning','commodities','cot','x402'], 200000, 200000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-cftc-commitments-of-traders', 'finance',
  '{"limit":20}', '[{"market_and_exchange_names":"GOLD - COMMODITY EXCHANGE INC.","open_interest_all":"512345"}]', 'CFTC Commitments of Traders: weekly futures positioning by trader class (commercial, non-commercial, non-reportable) with open interest. Filter with a Socrata where clause. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- crypto :: suverse-l2beat-scaling-summary ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-l2beat-scaling-summary', 'suverse-l2beat-scaling-summary', 'https://proxy.suverse.io/v1/data/suverse-l2beat-scaling-summary', 'POST',
    'Ethereum L2 Scaling Summary', 'The full L2Beat scaling summary: every tracked Ethereum layer-2 with its total value secured, market share, 7-day change, stage classification (Stage 0/1/2), technology category such as optimistic or ZK rollup, and the risk profile L2Beat assigns. The reference dataset for comparing L2s on security maturity rather than TVL alone.', 'L2Beat scaling summary: every tracked Ethereum L2 with value secured, market share, 7d change, stage classification, rollup type and risk profile. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_l2beat_scaling_summary'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Ethereum L2 Scaling Summary', 'The full L2Beat scaling summary: every tracked Ethereum layer-2 with its total value secured, market share, 7-day change, stage classification (Stage 0/1/2), technology category such as optimistic or ZK rollup, and the risk profile L2Beat assigns. The reference dataset for comparing L2s on security maturity rather than TVL alone.', 'https://proxy.suverse.io/v1/data/suverse-l2beat-scaling-summary',
  ARRAY['crypto','l2','ethereum','rollup','tvl','l2beat','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-l2beat-scaling-summary', 'crypto',
  '{}', '{"success":true,"data":{"projects":{}}}', 'L2Beat scaling summary: every tracked Ethereum L2 with value secured, market share, 7d change, stage classification, rollup type and risk profile. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
