-- GENERATED by gen-batch-008.mjs — 5 in-house internal_handler endpoints.
-- Idempotent UPSERT. Reuses reskey reskey_1166628d + active pool payTo.
BEGIN;

-- smart-money-token-rankings (internal_handler=smart_money_token_rankings, $0.030)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'smart-money-token-rankings', 'smart-money-token-rankings', 'https://proxy.suverse.io/v1/data/smart-money-token-rankings', 'POST',
    'Smart-Money Token Rankings', 'Tokens ranked by aggregate smart-money score over the trailing 30 days, from our own smart-money-tracker netflow cache. Each row carries buy/sell/net USD flow, unique smart traders, smart-money score and momentum rank, with symbol decoration. Pass chain (base or solana, default solana) and limit (1-100).', 'Tokens ranked by smart-money score (30d) from our tracker: buy/sell/net USD flow, unique smart traders, smart-money score, momentum rank, symbol. chain=base|solana, limit<=100. In-house data, not a third-party proxy.', 30000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true, false, 'smart_money_token_rankings'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, category, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, sample_request_json,
  sample_response_json, description_bazaar, proxy_config_id
)
SELECT gen_random_uuid(), 'Smart-Money Token Rankings', 'Tokens ranked by aggregate smart-money score over the trailing 30 days, from our own smart-money-tracker netflow cache. Each row carries buy/sell/net USD flow, unique smart traders, smart-money score and momentum rank, with symbol decoration. Pass chain (base or solana, default solana) and limit (1-100).', 'https://proxy.suverse.io/v1/data/smart-money-token-rankings', 'smart-money',
  ARRAY['smart-money','rankings','tokens','netflow','solana','base'], 30000, 30000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'], 'approved',
  proxy_ins.resource_key_id, 'smart-money-token-rankings', '{"chain":"solana","limit":20}', '{"kind":"rankings","chain":"solana","time_window":"30d","count":1,"tokens":[{"token":"GaPb...pump","symbol":"EXAMPLE","net_flow_usd":12500,"unique_traders":14,"smart_money_score":88.3,"momentum_rank":1}],"data_quality":{"computed_at":"2026-06-21T22:36:06.000Z","stale":false,"row_count":1}}', 'Tokens ranked by smart-money score (30d) from our tracker: buy/sell/net USD flow, unique smart traders, smart-money score, momentum rank, symbol. chain=base|solana, limit<=100. In-house data, not a third-party proxy.', proxy_ins.id
FROM proxy_ins ON CONFLICT DO NOTHING;

-- smart-money-accumulation (internal_handler=smart_money_accumulation, $0.030)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'smart-money-accumulation', 'smart-money-accumulation', 'https://proxy.suverse.io/v1/data/smart-money-accumulation', 'POST',
    'Smart-Money Accumulation', 'Tokens being accumulated by smart money: the largest POSITIVE smart-money net USD inflow over the trailing 30 days, from our tracker netflow cache. Buy/sell/net flow, unique smart traders, smart-money score per token, symbol decoration. Pass chain (base or solana) and limit.', 'Tokens with the biggest smart-money net INFLOW (30d) from our tracker: buy/sell/net USD, unique traders, smart-money score, symbol. chain=base|solana, limit<=100. In-house data.', 30000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true, false, 'smart_money_accumulation'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, category, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, sample_request_json,
  sample_response_json, description_bazaar, proxy_config_id
)
SELECT gen_random_uuid(), 'Smart-Money Accumulation', 'Tokens being accumulated by smart money: the largest POSITIVE smart-money net USD inflow over the trailing 30 days, from our tracker netflow cache. Buy/sell/net flow, unique smart traders, smart-money score per token, symbol decoration. Pass chain (base or solana) and limit.', 'https://proxy.suverse.io/v1/data/smart-money-accumulation', 'smart-money',
  ARRAY['smart-money','accumulation','inflow','tokens','solana','base'], 30000, 30000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'], 'approved',
  proxy_ins.resource_key_id, 'smart-money-accumulation', '{"chain":"solana","limit":20}', '{"kind":"accumulation","chain":"solana","time_window":"30d","count":1,"tokens":[{"token":"So111...","symbol":"EXAMPLE","net_flow_usd":50000,"unique_traders":22,"smart_money_score":71}],"data_quality":{"computed_at":"2026-06-21T22:36:06.000Z","stale":false,"row_count":1}}', 'Tokens with the biggest smart-money net INFLOW (30d) from our tracker: buy/sell/net USD, unique traders, smart-money score, symbol. chain=base|solana, limit<=100. In-house data.', proxy_ins.id
FROM proxy_ins ON CONFLICT DO NOTHING;

-- smart-money-distribution (internal_handler=smart_money_distribution, $0.030)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'smart-money-distribution', 'smart-money-distribution', 'https://proxy.suverse.io/v1/data/smart-money-distribution', 'POST',
    'Smart-Money Distribution', 'Tokens being distributed (sold) by smart money: the largest NEGATIVE smart-money net USD flow over the trailing 30 days, from our tracker netflow cache. Buy/sell/net flow, unique smart traders, smart-money score per token, symbol decoration. Pass chain (base or solana) and limit.', 'Tokens with the biggest smart-money net OUTFLOW (30d) from our tracker: buy/sell/net USD, unique traders, smart-money score, symbol. chain=base|solana, limit<=100. In-house data.', 30000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true, false, 'smart_money_distribution'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, category, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, sample_request_json,
  sample_response_json, description_bazaar, proxy_config_id
)
SELECT gen_random_uuid(), 'Smart-Money Distribution', 'Tokens being distributed (sold) by smart money: the largest NEGATIVE smart-money net USD flow over the trailing 30 days, from our tracker netflow cache. Buy/sell/net flow, unique smart traders, smart-money score per token, symbol decoration. Pass chain (base or solana) and limit.', 'https://proxy.suverse.io/v1/data/smart-money-distribution', 'smart-money',
  ARRAY['smart-money','distribution','outflow','tokens','solana','base'], 30000, 30000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'], 'approved',
  proxy_ins.resource_key_id, 'smart-money-distribution', '{"chain":"solana","limit":20}', '{"kind":"distribution","chain":"solana","time_window":"30d","count":1,"tokens":[{"token":"Dob5...","symbol":"EXAMPLE","net_flow_usd":-31500,"unique_traders":9,"smart_money_score":40}],"data_quality":{"computed_at":"2026-06-21T22:36:06.000Z","stale":false,"row_count":1}}', 'Tokens with the biggest smart-money net OUTFLOW (30d) from our tracker: buy/sell/net USD, unique traders, smart-money score, symbol. chain=base|solana, limit<=100. In-house data.', proxy_ins.id
FROM proxy_ins ON CONFLICT DO NOTHING;

-- smart-money-top-wallets (internal_handler=smart_money_top_wallets, $0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'smart-money-top-wallets', 'smart-money-top-wallets', 'https://proxy.suverse.io/v1/data/smart-money-top-wallets', 'POST',
    'Smart-Money Top Wallets', 'The smart-money wallet leaderboard: eligible wallets (hybrid gate: skill score >=60, confidence >=50, not quarantined) ranked by score then trailing 90-day PnL, from our smart-money-tracker scoring table. Each row carries address, tier, score, win rate, 90d PnL, realized PnL, profit factor, trade count, median holding time. Pass chain (base or solana) and limit.', 'Smart-money wallet leaderboard from our tracker: eligible wallets ranked by skill score then 90d PnL. address, tier, score, win rate, 90d/realized PnL, profit factor, holding time. chain=base|solana. In-house scoring data.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true, false, 'smart_money_top_wallets'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, category, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, sample_request_json,
  sample_response_json, description_bazaar, proxy_config_id
)
SELECT gen_random_uuid(), 'Smart-Money Top Wallets', 'The smart-money wallet leaderboard: eligible wallets (hybrid gate: skill score >=60, confidence >=50, not quarantined) ranked by score then trailing 90-day PnL, from our smart-money-tracker scoring table. Each row carries address, tier, score, win rate, 90d PnL, realized PnL, profit factor, trade count, median holding time. Pass chain (base or solana) and limit.', 'https://proxy.suverse.io/v1/data/smart-money-top-wallets', 'smart-money',
  ARRAY['smart-money','leaderboard','wallets','copy-trading','pnl','solana'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'], 'approved',
  proxy_ins.resource_key_id, 'smart-money-top-wallets', '{"chain":"solana","limit":20}', '{"kind":"top_wallets","chain":"solana","count":1,"wallets":[{"address":"Dkc...P67Z","tier":"elite","score":93.3,"win_rate":0.71,"pnl_90d_usd":26553,"profit_factor":3.1,"trade_count_90d":42}],"data_quality":{"computed_at":"2026-06-20T21:32:08.000Z","stale":false,"row_count":1}}', 'Smart-money wallet leaderboard from our tracker: eligible wallets ranked by skill score then 90d PnL. address, tier, score, win rate, 90d/realized PnL, profit factor, holding time. chain=base|solana. In-house scoring data.', proxy_ins.id
FROM proxy_ins ON CONFLICT DO NOTHING;

-- wallet-label-lookup (internal_handler=wallet_label_lookup, $0.020)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'wallet-label-lookup', 'wallet-label-lookup', 'https://proxy.suverse.io/v1/data/wallet-label-lookup', 'POST',
    'Wallet Entity Label', 'Entity label for any wallet from our heuristic-labeling table: is it a contract, a CEX deposit address, a market maker, a token deployer, an LP actor or a probable bot, with the supporting evidence and confidence. Accepts an EVM (0x+40hex) or Solana base58 address; chain auto-detected. An unlabeled address returns labeled:false (absence is information), never an error.', 'Entity label for any wallet from our labeler: contract / CEX-deposit / market-maker / deployer / LP-actor / probable-bot, with evidence + confidence. EVM or Solana address, chain auto-detected. In-house heuristic labels.', 20000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true, false, 'wallet_label_lookup'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, category, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, sample_request_json,
  sample_response_json, description_bazaar, proxy_config_id
)
SELECT gen_random_uuid(), 'Wallet Entity Label', 'Entity label for any wallet from our heuristic-labeling table: is it a contract, a CEX deposit address, a market maker, a token deployer, an LP actor or a probable bot, with the supporting evidence and confidence. Accepts an EVM (0x+40hex) or Solana base58 address; chain auto-detected. An unlabeled address returns labeled:false (absence is information), never an error.', 'https://proxy.suverse.io/v1/data/wallet-label-lookup', 'wallet-analytics',
  ARRAY['wallet','label','entity','market-maker','cex','deployer','evm','solana'], 20000, 20000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'], 'approved',
  proxy_ins.resource_key_id, 'wallet-label-lookup', '{"address":"0x4446adc0b8136ffc55ddb7a488ba5509ace2a5ef"}', '{"address":"0x4446adc0b8136ffc55ddb7a488ba5509ace2a5ef","chain":"base","labeled":true,"summary":"Labeled as: market_maker (confidence high).","labels":["market_maker"],"flags":{"is_contract":false,"is_cex_deposit":false,"is_market_maker":true,"is_deployer":false,"is_lp_actor":false,"is_probable_bot":false},"source_confidence":"high","last_observed_at":"2026-06-21T15:32:14.000Z"}', 'Entity label for any wallet from our labeler: contract / CEX-deposit / market-maker / deployer / LP-actor / probable-bot, with evidence + confidence. EVM or Solana address, chain auto-detected. In-house heuristic labels.', proxy_ins.id
FROM proxy_ins ON CONFLICT DO NOTHING;

COMMIT;
