-- GENERATED by wrap-batch.mjs — batch batch-015 — 12 endpoints.
-- Idempotent (UPSERT). Reuses reskey reskey_1166628d + proven payTo trio.
BEGIN;

-- sports :: suverse-espn-scoreboard ($0.120)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-espn-scoreboard', 'suverse-espn-scoreboard', 'https://proxy.suverse.io/v1/data/suverse-espn-scoreboard', 'POST',
    'Live Sports Scoreboard', 'Current scoreboard for any league ESPN covers: fixtures, live and final scores, period or clock state, venue, broadcast and competitor records. Works across soccer, basketball, football, baseball, hockey and more by passing the sport and league slug, for example soccer/eng.1, basketball/nba or football/nfl.', 'Live scoreboard for any ESPN-covered league: fixtures, scores, clock state, venue and competitor records. Pass sport and league, e.g. soccer/eng.1 or basketball/nba. Keyless.', 120000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_espn_scoreboard'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Live Sports Scoreboard', 'Current scoreboard for any league ESPN covers: fixtures, live and final scores, period or clock state, venue, broadcast and competitor records. Works across soccer, basketball, football, baseball, hockey and more by passing the sport and league slug, for example soccer/eng.1, basketball/nba or football/nfl.', 'https://proxy.suverse.io/v1/data/suverse-espn-scoreboard',
  ARRAY['sports','scores','espn','live','soccer','nba','x402'], 120000, 120000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-espn-scoreboard', 'sports',
  '{"sport":"soccer","league":"eng.1"}', '{"leagues":[{"name":"English Premier League"}],"events":[]}', 'Live scoreboard for any ESPN-covered league: fixtures, scores, clock state, venue and competitor records. Pass sport and league, e.g. soccer/eng.1 or basketball/nba. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-espn-teams ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-espn-teams', 'suverse-espn-teams', 'https://proxy.suverse.io/v1/data/suverse-espn-teams', 'POST',
    'League Team Directory', 'Every team in an ESPN-covered league with its identifier, display name, abbreviation, location, colours, logos and links. This is the lookup table an agent needs before querying team-specific data, and it works uniformly across soccer, basketball, football, baseball and hockey.', 'All teams in an ESPN-covered league with id, name, abbreviation, location, colours and logos. Pass sport and league, e.g. basketball/nba. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_espn_teams'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'League Team Directory', 'Every team in an ESPN-covered league with its identifier, display name, abbreviation, location, colours, logos and links. This is the lookup table an agent needs before querying team-specific data, and it works uniformly across soccer, basketball, football, baseball and hockey.', 'https://proxy.suverse.io/v1/data/suverse-espn-teams',
  ARRAY['sports','teams','espn','directory','league','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-espn-teams', 'sports',
  '{"sport":"basketball","league":"nba"}', '{"sports":[{"leagues":[{"teams":[{"team":{"displayName":"Boston Celtics","abbreviation":"BOS"}}]}]}]}', 'All teams in an ESPN-covered league with id, name, abbreviation, location, colours and logos. Pass sport and league, e.g. basketball/nba. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-f1-race-results ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-f1-race-results', 'suverse-f1-race-results', 'https://proxy.suverse.io/v1/data/suverse-f1-race-results', 'POST',
    'Formula 1 Race Results', 'Full classification for a Formula 1 grand prix from the Jolpica-F1 API, the community-maintained successor to Ergast. Returns every driver''s finishing position, constructor, grid slot, laps completed, status, race time or gap, points scored and fastest lap. Pass the season year and the round number.', 'Formula 1 race classification from Jolpica-F1 (Ergast successor): position, driver, constructor, grid, laps, status, time, points and fastest lap. Pass season and round. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_f1_race_results'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Formula 1 Race Results', 'Full classification for a Formula 1 grand prix from the Jolpica-F1 API, the community-maintained successor to Ergast. Returns every driver''s finishing position, constructor, grid slot, laps completed, status, race time or gap, points scored and fastest lap. Pass the season year and the round number.', 'https://proxy.suverse.io/v1/data/suverse-f1-race-results',
  ARRAY['sports','formula1','f1','motorsport','results','jolpica','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-f1-race-results', 'sports',
  '{"season":"2025","round":"1"}', '{"MRData":{"RaceTable":{"Races":[{"raceName":"Australian Grand Prix","Results":[]}]}}}', 'Formula 1 race classification from Jolpica-F1 (Ergast successor): position, driver, constructor, grid, laps, status, time, points and fastest lap. Pass season and round. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-f1-driver-standings ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-f1-driver-standings', 'suverse-f1-driver-standings', 'https://proxy.suverse.io/v1/data/suverse-f1-driver-standings', 'POST',
    'Formula 1 Driver Standings', 'World Drivers'' Championship standings for a Formula 1 season from the Jolpica-F1 API: each driver''s championship position, points total, wins, constructor and driver metadata including nationality and permanent number. Pass the season year to get the final or current standings for that championship.', 'Formula 1 World Drivers'' Championship standings for a season from Jolpica-F1: position, points, wins, constructor and driver details. Pass a season year. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_f1_driver_standings'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Formula 1 Driver Standings', 'World Drivers'' Championship standings for a Formula 1 season from the Jolpica-F1 API: each driver''s championship position, points total, wins, constructor and driver metadata including nationality and permanent number. Pass the season year to get the final or current standings for that championship.', 'https://proxy.suverse.io/v1/data/suverse-f1-driver-standings',
  ARRAY['sports','formula1','f1','standings','championship','jolpica','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-f1-driver-standings', 'sports',
  '{"season":"2025"}', '{"MRData":{"StandingsTable":{"StandingsLists":[{"DriverStandings":[]}]}}}', 'Formula 1 World Drivers'' Championship standings for a season from Jolpica-F1: position, points, wins, constructor and driver details. Pass a season year. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-chesscom-player-stats ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-chesscom-player-stats', 'suverse-chesscom-player-stats', 'https://proxy.suverse.io/v1/data/suverse-chesscom-player-stats', 'POST',
    'Chess.com Player Ratings and Record', 'Rating and record breakdown for any Chess.com account: current, best and lowest ratings across blitz, bullet, rapid and daily, with win/loss/draw counts for each format, plus tactics and puzzle-rush bests and any FIDE rating on file. Pass the username.', 'Chess.com player ratings and record: current, best and lowest across blitz, bullet, rapid and daily with W/L/D counts, plus tactics and puzzle rush bests. Pass a username. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_chesscom_player_stats'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Chess.com Player Ratings and Record', 'Rating and record breakdown for any Chess.com account: current, best and lowest ratings across blitz, bullet, rapid and daily, with win/loss/draw counts for each format, plus tactics and puzzle-rush bests and any FIDE rating on file. Pass the username.', 'https://proxy.suverse.io/v1/data/suverse-chesscom-player-stats',
  ARRAY['games','chess','chess-com','rating','elo','player','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-chesscom-player-stats', 'games',
  '{"username":"hikaru"}', '{"chess_blitz":{"last":{"rating":3200},"record":{"win":12000,"loss":3000,"draw":1500}}}', 'Chess.com player ratings and record: current, best and lowest across blitz, bullet, rapid and daily with W/L/D counts, plus tactics and puzzle rush bests. Pass a username. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-chesscom-player-profile ($0.080)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-chesscom-player-profile', 'suverse-chesscom-player-profile', 'https://proxy.suverse.io/v1/data/suverse-chesscom-player-profile', 'POST',
    'Chess.com Player Profile', 'Public profile for a Chess.com account: display name, title, country, followers, league, join and last-online timestamps, streaming status and verification flags. Combine with the stats endpoint to get a full picture of a player before analysing their games.', 'Chess.com public player profile: name, title, country, followers, league, join and last-online times and streamer status. Pass a username. Keyless.', 80000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_chesscom_player_profile'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Chess.com Player Profile', 'Public profile for a Chess.com account: display name, title, country, followers, league, join and last-online timestamps, streaming status and verification flags. Combine with the stats endpoint to get a full picture of a player before analysing their games.', 'https://proxy.suverse.io/v1/data/suverse-chesscom-player-profile',
  ARRAY['games','chess','chess-com','profile','player','x402'], 80000, 80000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-chesscom-player-profile', 'games',
  '{"username":"hikaru"}', '{"username":"hikaru","title":"GM","country":"https://api.chess.com/pub/country/US","followers":1200000}', 'Chess.com public player profile: name, title, country, followers, league, join and last-online times and streamer status. Pass a username. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- sports :: suverse-bundesliga-table ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-bundesliga-table', 'suverse-bundesliga-table', 'https://proxy.suverse.io/v1/data/suverse-bundesliga-table', 'POST',
    'German Football League Table', 'Current league table for a German football division from OpenLigaDB: each team''s position implied by points, matches played, wins, draws, losses, goals for and against, goal difference and points. Pass the league shortcut such as bl1 for Bundesliga or bl2 for 2. Bundesliga, plus the season start year.', 'German football league table from OpenLigaDB: matches played, W/D/L, goals for and against, goal difference and points. Pass league shortcut (bl1, bl2) and season year. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_bundesliga_table'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'German Football League Table', 'Current league table for a German football division from OpenLigaDB: each team''s position implied by points, matches played, wins, draws, losses, goals for and against, goal difference and points. Pass the league shortcut such as bl1 for Bundesliga or bl2 for 2. Bundesliga, plus the season start year.', 'https://proxy.suverse.io/v1/data/suverse-bundesliga-table',
  ARRAY['sports','football','bundesliga','germany','table','openligadb','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-bundesliga-table', 'sports',
  '{"league":"bl1","season":"2025"}', '[{"teamName":"FC Bayern Munchen","points":62,"matches":26,"goalDiff":45}]', 'German football league table from OpenLigaDB: matches played, W/D/L, goals for and against, goal difference and points. Pass league shortcut (bl1, bl2) and season year. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-steam-app-details ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-steam-app-details', 'suverse-steam-app-details', 'https://proxy.suverse.io/v1/data/suverse-steam-app-details', 'POST',
    'Steam Game Details', 'Storefront record for any Steam title: name, type, short and detailed description, developers and publishers, release date, current and discounted price with currency, supported platforms, Metacritic score, genres, categories and system requirements. Pass the Steam application id.', 'Steam storefront details for a game: name, description, developers, publishers, release date, price and discount, platforms, Metacritic, genres and system requirements. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_steam_app_details'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Steam Game Details', 'Storefront record for any Steam title: name, type, short and detailed description, developers and publishers, release date, current and discounted price with currency, supported platforms, Metacritic score, genres, categories and system requirements. Pass the Steam application id.', 'https://proxy.suverse.io/v1/data/suverse-steam-app-details',
  ARRAY['games','steam','gaming','pricing','store','pc','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-steam-app-details', 'games',
  '{"appids":"440","cc":"us"}', '{"440":{"success":true,"data":{"name":"Team Fortress 2","type":"game","is_free":true}}}', 'Steam storefront details for a game: name, description, developers, publishers, release date, price and discount, platforms, Metacritic, genres and system requirements. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-steam-player-count ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-steam-player-count', 'suverse-steam-player-count', 'https://proxy.suverse.io/v1/data/suverse-steam-player-count', 'POST',
    'Steam Concurrent Player Count', 'The number of players currently in-game for a Steam title, straight from the Steam Web API. A single cheap call that answers how alive a game is right now, useful for tracking launch performance, seasonal spikes and long-term decline. Pass the Steam application id.', 'Live concurrent player count for a Steam game from the Steam Web API. Pass a Steam app id. The cheapest read on how alive a game is right now. Keyless.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_steam_player_count'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Steam Concurrent Player Count', 'The number of players currently in-game for a Steam title, straight from the Steam Web API. A single cheap call that answers how alive a game is right now, useful for tracking launch performance, seasonal spikes and long-term decline. Pass the Steam application id.', 'https://proxy.suverse.io/v1/data/suverse-steam-player-count',
  ARRAY['games','steam','players','concurrency','gaming','metrics','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-steam-player-count', 'games',
  '{"appid":"440"}', '{"response":{"player_count":51234,"result":1}}', 'Live concurrent player count for a Steam game from the Steam Web API. Pass a Steam app id. The cheapest read on how alive a game is right now. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-steamspy-app-stats ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-steamspy-app-stats', 'suverse-steamspy-app-stats', 'https://proxy.suverse.io/v1/data/suverse-steamspy-app-stats', 'POST',
    'SteamSpy Ownership and Playtime', 'SteamSpy''s estimated ownership and engagement figures for a Steam title: owners banded range, average and median playtime both lifetime and over the last two weeks, current and peak concurrent users, price and discount, positive and negative review counts, developer, publisher, genre and user tags.', 'SteamSpy estimates for a Steam game: owners range, average and median playtime, concurrent users, price, review counts, developer, publisher, genre and tags. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_steamspy_app_stats'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'SteamSpy Ownership and Playtime', 'SteamSpy''s estimated ownership and engagement figures for a Steam title: owners banded range, average and median playtime both lifetime and over the last two weeks, current and peak concurrent users, price and discount, positive and negative review counts, developer, publisher, genre and user tags.', 'https://proxy.suverse.io/v1/data/suverse-steamspy-app-stats',
  ARRAY['games','steam','steamspy','ownership','playtime','analytics','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-steamspy-app-stats', 'games',
  '{"appid":"440"}', '{"appid":440,"name":"Team Fortress 2","owners":"50,000,000 .. 100,000,000","average_forever":6200}', 'SteamSpy estimates for a Steam game: owners range, average and median playtime, concurrent users, price, review counts, developer, publisher, genre and tags. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-scryfall-card-search ($0.100)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-scryfall-card-search', 'suverse-scryfall-card-search', 'https://proxy.suverse.io/v1/data/suverse-scryfall-card-search', 'POST',
    'Magic: The Gathering Card Search', 'Search Magic: The Gathering cards through Scryfall using its full query syntax. Returns matching cards with mana cost, type line, oracle text, power and toughness, rarity, set, artist, images, current USD/EUR market prices and format legality across standard, modern, commander and more. Far richer than a name lookup.', 'Search Magic: The Gathering cards via Scryfall query syntax. Returns mana cost, oracle text, rarity, set, images, market prices and format legality across all formats. Keyless.', 100000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_scryfall_card_search'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Magic: The Gathering Card Search', 'Search Magic: The Gathering cards through Scryfall using its full query syntax. Returns matching cards with mana cost, type line, oracle text, power and toughness, rarity, set, artist, images, current USD/EUR market prices and format legality across standard, modern, commander and more. Far richer than a name lookup.', 'https://proxy.suverse.io/v1/data/suverse-scryfall-card-search',
  ARRAY['games','mtg','magic','scryfall','tcg','cards','x402'], 100000, 100000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-scryfall-card-search', 'games',
  '{"q":"lightning bolt"}', '{"object":"list","total_cards":42,"data":[{"name":"Lightning Bolt","mana_cost":"{R}","type_line":"Instant"}]}', 'Search Magic: The Gathering cards via Scryfall query syntax. Returns mana cost, oracle text, rarity, set, images, market prices and format legality across all formats. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

-- games :: suverse-deck-of-cards-shuffle ($0.050)
WITH proxy_ins AS (
  INSERT INTO seller_proxy_configs (
    id, resource_key_id, endpoint_slug, public_slug, original_url, original_method,
    display_name, description, description_bazaar, price_atomic, accepted_networks,
    pay_to_evm, pay_to_solana, pay_to_cosmos, forward_auth_scheme, is_active,
    upstream_x402_enabled, internal_handler
  ) VALUES (
    gen_random_uuid(), 'reskey_1166628d', 'suverse-deck-of-cards-shuffle', 'suverse-deck-of-cards-shuffle', 'https://proxy.suverse.io/v1/data/suverse-deck-of-cards-shuffle', 'POST',
    'Shuffled Playing Card Deck', 'Create and shuffle a fresh deck of standard playing cards and get back a deck identifier plus the number of cards remaining. The returned deck id can be reused for subsequent draws, making this a verifiable shuffle primitive for card games, randomised sampling and agent-run simulations.', 'Create and shuffle a standard playing card deck, returning a reusable deck id and remaining count. A shuffle primitive for card games and randomised sampling. Keyless.', 50000, ARRAY['eip155:8453','solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp','cosmos:noble-1'],
    '0xe90316121189715CDc2515B7C2673658b810b751', 'CBYMYxfMGdA98qkzrYqTzTiQhP3H2scU95EB4ZxoRxuM', 'noble1z5g7vts3pfjsgschfjrhq5s3ze6etxjl5lj2rj', 'static', true,
    false, 'suverse_deck_of_cards_shuffle'
  )
  ON CONFLICT (resource_key_id, endpoint_slug) DO UPDATE
    SET internal_handler = EXCLUDED.internal_handler, public_slug = EXCLUDED.public_slug,
        display_name = EXCLUDED.display_name, description = EXCLUDED.description,
        description_bazaar = EXCLUDED.description_bazaar, price_atomic = EXCLUDED.price_atomic,
        accepted_networks = EXCLUDED.accepted_networks, pay_to_evm = EXCLUDED.pay_to_evm,
        pay_to_solana = EXCLUDED.pay_to_solana, pay_to_cosmos = EXCLUDED.pay_to_cosmos,
        is_active = true, updated_at = now()
  RETURNING id, resource_key_id
)
INSERT INTO catalog_listings (
  id, title, description, endpoint_url, tags, price_atomic_min, price_atomic_max,
  price_unit, networks, status, resource_key_id, slug, category,
  sample_request_json, sample_response_json, description_bazaar, proxy_config_id
)
SELECT
  gen_random_uuid(), 'Shuffled Playing Card Deck', 'Create and shuffle a fresh deck of standard playing cards and get back a deck identifier plus the number of cards remaining. The returned deck id can be reused for subsequent draws, making this a verifiable shuffle primitive for card games, randomised sampling and agent-run simulations.', 'https://proxy.suverse.io/v1/data/suverse-deck-of-cards-shuffle',
  ARRAY['games','cards','deck','shuffle','random','simulation','x402'], 50000, 50000, 'per-call', ARRAY['eip155:8453','solana:mainnet','cosmos:noble-1'],
  'approved', proxy_ins.resource_key_id, 'suverse-deck-of-cards-shuffle', 'games',
  '{"deck_count":1}', '{"success":true,"deck_id":"3p40paa87x90","shuffled":true,"remaining":52}', 'Create and shuffle a standard playing card deck, returning a reusable deck id and remaining count. A shuffle primitive for card games and randomised sampling. Keyless.', proxy_ins.id
FROM proxy_ins
ON CONFLICT DO NOTHING;

COMMIT;
